//! Renders the per-project `litellm-config.yaml` (ADR-072).
//!
//! The file lands at `<data_dir>/litellm/<project>/config.yaml` (0600,
//! atomic) and is mounted `:ro` at `/config` in the `litellm` container.
//! It carries NO secrets: every key is referenced as
//! `os.environ/SPW_KEY_<PROVIDER_ID>`, resolved inside the container by
//! the entrypoint from the `/tokens` mount.
//!
//! INVARIANT (validated in the Phase 0 spike): the rendered config and the
//! container environment must never define Anthropic credentials under
//! their canonical names (`ANTHROPIC_API_KEY`/`ANTHROPIC_AUTH_TOKEN`).
//! LiteLLM's `/anthropic` passthrough route forwards the client's
//! `Authorization` header (the subscription OAuth token) only while the
//! proxy itself holds no Anthropic credential — a canonical name would
//! silently override every passthrough call.

use crate::config::{LlmConfig, LlmProviderKind};
use std::path::{Path, PathBuf};

/// Port the litellm container listens on (fixed in its entrypoint).
pub const LITELLM_PORT: u16 = 4000;

/// In-network base URL of the proxy as the claude container sees it.
pub const LITELLM_BASE_URL: &str = "http://litellm:4000";

/// Subscription sessions use the passthrough route — OAuth `Authorization`
/// forwarded verbatim to api.anthropic.com.
pub const LITELLM_ANTHROPIC_PASSTHROUGH_URL: &str = "http://litellm:4000/anthropic";

/// `SPW_KEY_<ID>` env name for a provider id (hyphens → underscores,
/// uppercased — same normalisation as `plugin::derive_worker_env`).
pub fn spw_key_env_name(provider_id: &str) -> String {
    format!(
        "SPW_KEY_{}",
        provider_id.to_ascii_uppercase().replace('-', "_")
    )
}

/// Path of the rendered config: `<data_dir>/litellm/<project>/config.yaml`.
pub fn litellm_config_path_in(data_dir: &Path, project: &str) -> PathBuf {
    data_dir.join("litellm").join(project).join("config.yaml")
}

/// Renders the litellm config for the project's provider set. Pure —
/// no filesystem access; `write_litellm_config_in` persists the result.
pub fn render_litellm_config(llm: &LlmConfig) -> String {
    let mut model_list = String::new();

    for entry in &llm.providers {
        // ids are slug-validated on resolve (migrate_llm_to_v2); the YAML
        // below embeds them bare, so re-check defensively.
        if !crate::plugin::is_valid_slug(&entry.id) {
            log::warn!("litellm config: skipping provider with invalid id");
            continue;
        }
        let key_ref = format!("os.environ/{}", spw_key_env_name(&entry.id));
        match entry.kind {
            // Subscription traffic never enters model_list: it rides the
            // built-in /anthropic passthrough with the client's own OAuth
            // Authorization header.
            LlmProviderKind::AnthropicOauth => {}
            LlmProviderKind::AnthropicApiKey => {
                model_list.push_str(&format!(
                    "  - model_name: \"anthropic/*\"\n    litellm_params:\n      model: \"anthropic/*\"\n      api_key: {key_ref}\n",
                ));
            }
            LlmProviderKind::OpenRouter => {
                model_list.push_str(&format!(
                    "  - model_name: \"openrouter/*\"\n    litellm_params:\n      model: \"openrouter/*\"\n      api_key: {key_ref}\n",
                ));
            }
            LlmProviderKind::Local | LlmProviderKind::OpenAiCompat | LlmProviderKind::Custom => {
                let Some(base_url) = entry.base_url.as_deref() else {
                    log::warn!(
                        "litellm config: provider '{}' has no base_url — skipped",
                        entry.id
                    );
                    continue;
                };
                // Container-side URL: the claude/litellm containers reach a
                // host-side server via host.docker.internal (ADR-062); the
                // stored base_url already uses that alias (validate_base_url).
                let api_base = ensure_v1_suffix(base_url);
                let api_key = if entry.has_api_key {
                    key_ref.clone()
                } else {
                    // llama.cpp/Ollama ignore the key but litellm's OpenAI
                    // client requires one.
                    "\"dummy\"".to_string()
                };
                model_list.push_str(&format!(
                    "  - model_name: \"{id}/*\"\n    litellm_params:\n      model: \"openai/*\"\n      api_base: \"{api_base}\"\n      api_key: {api_key}\n",
                    id = entry.id,
                ));
            }
        }
    }

    format!(
        "# GENERATED by speedwave-runtime (ADR-072) — do not edit.\n\
         # Secrets are env references resolved by the container entrypoint;\n\
         # this file must never contain a key value.\n\
         model_list:\n{model_list}\n\
         litellm_settings:\n  \
           drop_params: true\n  \
           callbacks: litellm_callback.speedwave_usage_logger\n\n\
         general_settings: {{}}\n"
    )
}

/// Appends `/v1` to an OpenAI-compatible base URL when absent — litellm's
/// `openai/` provider expects the versioned root.
fn ensure_v1_suffix(base_url: &str) -> String {
    let trimmed = base_url.trim_end_matches('/');
    if trimmed.ends_with("/v1") {
        trimmed.to_string()
    } else {
        format!("{trimmed}/v1")
    }
}

/// Renders and atomically persists the config (0600 + fsync) under
/// `<data_dir>/litellm/<project>/config.yaml`.
pub fn write_litellm_config_in(
    data_dir: &Path,
    project: &str,
    llm: &LlmConfig,
) -> anyhow::Result<PathBuf> {
    crate::validation::validate_project_name(project)?;
    let path = litellm_config_path_in(data_dir, project);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
        crate::fs_perms::ensure_owner_only_dir(parent)?;
    }
    let content = render_litellm_config(llm);
    crate::fs_perms::write_restricted_file_atomic(&path, &content)?;
    Ok(path)
}

/// Validates and persists one provider's API key under the llm token
/// namespace. Mirrors the ADR-040 local-llm key rules: strips an
/// accidental `Bearer ` prefix, rejects control characters (CRLF header
/// injection), rejects empty values.
pub fn write_llm_provider_key_in(
    data_dir: &Path,
    project: &str,
    provider_id: &str,
    key: &str,
) -> anyhow::Result<PathBuf> {
    let value = key.trim();
    let value = value.strip_prefix("Bearer ").unwrap_or(value).trim();
    if value.is_empty() {
        anyhow::bail!("API key must not be empty");
    }
    if value.chars().any(|c| c.is_control()) {
        anyhow::bail!("API key must not contain control characters");
    }
    let path = super::tokens::llm_provider_key_path_in(data_dir, project, provider_id)?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
        crate::fs_perms::ensure_owner_only_dir(parent)?;
    }
    crate::fs_perms::write_restricted_file_atomic(&path, value)?;
    Ok(path)
}

/// Removes one provider's key file (e.g. provider deleted in Settings).
/// Missing file is not an error.
pub fn remove_llm_provider_key_in(
    data_dir: &Path,
    project: &str,
    provider_id: &str,
) -> anyhow::Result<()> {
    let path = super::tokens::llm_provider_key_path_in(data_dir, project, provider_id)?;
    match std::fs::remove_file(&path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.into()),
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use crate::config::{LlmActive, LlmProviderEntry};

    fn entry(id: &str, kind: LlmProviderKind) -> LlmProviderEntry {
        LlmProviderEntry {
            id: id.into(),
            kind,
            base_url: None,
            has_api_key: false,
            context_tokens: None,
            has_custom_headers: false,
        }
    }

    #[test]
    fn spw_key_env_name_normalises_like_worker_env() {
        assert_eq!(spw_key_env_name("openrouter"), "SPW_KEY_OPENROUTER");
        assert_eq!(spw_key_env_name("my-anthropic"), "SPW_KEY_MY_ANTHROPIC");
    }

    /// Golden file: the full provider mix renders exactly this YAML.
    #[test]
    fn render_full_provider_mix_golden() {
        let llm = LlmConfig {
            providers: vec![
                entry("anthropic", LlmProviderKind::AnthropicOauth),
                LlmProviderEntry {
                    has_api_key: true,
                    ..entry("anthropic-key", LlmProviderKind::AnthropicApiKey)
                },
                LlmProviderEntry {
                    base_url: Some("http://host.docker.internal:9000".into()),
                    ..entry("local", LlmProviderKind::Local)
                },
                LlmProviderEntry {
                    has_api_key: true,
                    ..entry("openrouter", LlmProviderKind::OpenRouter)
                },
            ],
            active: Some(LlmActive {
                provider_id: "local".into(),
                model: Some("qwen3".into()),
            }),
            ..Default::default()
        };

        let expected = "\
# GENERATED by speedwave-runtime (ADR-072) — do not edit.
# Secrets are env references resolved by the container entrypoint;
# this file must never contain a key value.
model_list:
  - model_name: \"anthropic/*\"
    litellm_params:
      model: \"anthropic/*\"
      api_key: os.environ/SPW_KEY_ANTHROPIC_KEY
  - model_name: \"local/*\"
    litellm_params:
      model: \"openai/*\"
      api_base: \"http://host.docker.internal:9000/v1\"
      api_key: \"dummy\"
  - model_name: \"openrouter/*\"
    litellm_params:
      model: \"openrouter/*\"
      api_key: os.environ/SPW_KEY_OPENROUTER

litellm_settings:
  drop_params: true
  callbacks: litellm_callback.speedwave_usage_logger

general_settings: {}
";
        assert_eq!(render_litellm_config(&llm), expected);
    }

    #[test]
    fn render_never_embeds_key_values_or_canonical_names() {
        let llm = LlmConfig {
            providers: vec![
                LlmProviderEntry {
                    has_api_key: true,
                    ..entry("openrouter", LlmProviderKind::OpenRouter)
                },
                LlmProviderEntry {
                    has_api_key: true,
                    ..entry("anthropic-key", LlmProviderKind::AnthropicApiKey)
                },
            ],
            ..Default::default()
        };
        let yaml = render_litellm_config(&llm);
        assert!(!yaml.contains("ANTHROPIC_API_KEY"));
        assert!(!yaml.contains("ANTHROPIC_AUTH_TOKEN"));
        assert!(!yaml.contains("sk-"));
        assert!(yaml.contains("os.environ/SPW_KEY_OPENROUTER"));
    }

    #[test]
    fn render_oauth_only_has_empty_model_list() {
        let llm = LlmConfig {
            providers: vec![entry("anthropic", LlmProviderKind::AnthropicOauth)],
            ..Default::default()
        };
        let yaml = render_litellm_config(&llm);
        assert!(
            yaml.contains("model_list:\n\nlitellm_settings"),
            "oauth-only config must not add model_list entries: {yaml}"
        );
    }

    #[test]
    fn render_skips_local_without_base_url_and_invalid_ids() {
        let mut bad_id = entry("ok-id", LlmProviderKind::OpenRouter);
        bad_id.id = "Bad.Id".into();
        let llm = LlmConfig {
            providers: vec![entry("local", LlmProviderKind::Local), bad_id],
            ..Default::default()
        };
        let yaml = render_litellm_config(&llm);
        assert!(!yaml.contains("local/*"), "no base_url → skipped: {yaml}");
        assert!(!yaml.contains("Bad.Id"), "invalid id → skipped: {yaml}");
    }

    #[test]
    fn ensure_v1_suffix_variants() {
        assert_eq!(ensure_v1_suffix("http://h:9000"), "http://h:9000/v1");
        assert_eq!(ensure_v1_suffix("http://h:9000/"), "http://h:9000/v1");
        assert_eq!(ensure_v1_suffix("http://h:9000/v1"), "http://h:9000/v1");
        assert_eq!(ensure_v1_suffix("http://h:9000/v1/"), "http://h:9000/v1");
    }

    #[test]
    fn write_config_creates_restricted_file() {
        let dir = tempfile::tempdir().unwrap();
        let llm = LlmConfig {
            providers: vec![entry("anthropic", LlmProviderKind::AnthropicOauth)],
            ..Default::default()
        };
        let path = write_litellm_config_in(dir.path(), "proj", &llm).unwrap();
        assert!(path.is_file());
        assert!(path.ends_with("litellm/proj/config.yaml"));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600, "config must be owner-only");
        }
    }

    #[test]
    fn write_key_validates_and_strips_bearer() {
        let dir = tempfile::tempdir().unwrap();
        let path =
            write_llm_provider_key_in(dir.path(), "proj", "openrouter", "Bearer sk-or-v1-abc ")
                .unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "sk-or-v1-abc");

        assert!(write_llm_provider_key_in(dir.path(), "proj", "openrouter", "  ").is_err());
        assert!(
            write_llm_provider_key_in(dir.path(), "proj", "openrouter", "evil\r\nheader").is_err()
        );
        assert!(write_llm_provider_key_in(dir.path(), "proj", "../escape", "v").is_err());
    }

    #[test]
    fn remove_key_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        write_llm_provider_key_in(dir.path(), "proj", "openrouter", "sk-x").unwrap();
        remove_llm_provider_key_in(dir.path(), "proj", "openrouter").unwrap();
        // Second removal: missing file is fine.
        remove_llm_provider_key_in(dir.path(), "proj", "openrouter").unwrap();
        assert!(remove_llm_provider_key_in(dir.path(), "proj", "../x").is_err());
    }
}
