export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'chore', 'revert'],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'runtime',
        'cli',
        'desktop',
        'tauri',
        'mcp',
        'mcp-hub',
        'mcp-shared',
        'mcp-slack',
        'mcp-sharepoint',
        'mcp-redmine',
        'mcp-gitlab',
        'mcp-gemini',
        'mcp-os',
        'containers',
        'ci',
        'docs',
        'e2e',
        'deps',
        'ide-bridge',
        'lint',
        'config',
        'daemon',
      ],
    ],
    'scope-empty': [1, 'never'],
  },
};
