use serde::{Deserialize, Serialize};
use speedwave_runtime::{build, compose, config, consts, runtime};
use std::path::PathBuf;

// ---------------------------------------------------------------------------
// Setup state — persisted to ~/.speedwave/setup_state.json for resume support
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Default, Clone)]
pub struct SetupState {
    pub current_step: u8,
    pub runtime_ready: bool,
    pub vm_ready: bool,
    pub project_created: Option<String>,
    pub tokens_configured: Vec<String>,
    pub images_built: bool,
    pub containers_started: bool,
    pub cli_linked: bool,
}

impl SetupState {
    fn state_path() -> anyhow::Result<PathBuf> {
        let home =
            dirs::home_dir().ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?;
        Ok(home.join(consts::DATA_DIR).join("setup_state.json"))
    }

    pub fn load() -> Self {
        Self::state_path()
            .ok()
            .and_then(|p| Self::load_from(&p).ok())
            .unwrap_or_default()
    }

    /// Loads setup state from a specific file path.
    fn load_from(path: &std::path::Path) -> anyhow::Result<Self> {
        let content = std::fs::read_to_string(path)?;
        let state: Self = serde_json::from_str(&content)?;
        Ok(state)
    }

    pub fn save(&self) -> anyhow::Result<()> {
        let path = Self::state_path()?;
        self.save_to(&path)
    }

    /// Saves setup state to a specific file path (atomic write via rename).
    fn save_to(&self, path: &std::path::Path) -> anyhow::Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let json = serde_json::to_string_pretty(self)?;
        let tmp_path = path.with_extension("json.tmp");
        std::fs::write(&tmp_path, &json)?;
        std::fs::rename(&tmp_path, path)?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Step 2: Check and install container runtime
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize)]
pub enum RuntimeStatus {
    Ready,
    NotInstalled,
}

pub fn check_runtime() -> anyhow::Result<RuntimeStatus> {
    let rt = runtime::detect_runtime();
    if rt.is_available() {
        let mut state = SetupState::load();
        state.runtime_ready = true;
        state.save()?;
        Ok(RuntimeStatus::Ready)
    } else {
        Ok(RuntimeStatus::NotInstalled)
    }
}

pub fn install_runtime() -> anyhow::Result<()> {
    let rt = runtime::detect_runtime();
    rt.ensure_ready()?;

    let mut state = SetupState::load();
    state.runtime_ready = true;
    state.save()?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Step 3: Initialize VM (macOS only — Lima)
// ---------------------------------------------------------------------------

/// Default Lima VM configuration for Speedwave.
/// Uses Apple Virtualization Framework (vz) with containerd + nerdctl.
#[cfg(target_os = "macos")]
const LIMA_CONFIG: &str = r#"# Speedwave Lima VM — auto-generated by setup wizard
vmType: vz
vmOpts:
  vz:
    rosetta:
      enabled: true
      binfmt: true
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
cpus: 4
memory: "8GiB"
disk: "30GiB"
mountType: virtiofs
networks:
  - vzNAT: true
mounts:
  - location: "~"
    writable: true
containerd:
  system: true
  user: false
"#;

/// Returns a `Command` for `limactl` with bundled-binary resolution and
/// isolated `LIMA_HOME`. Delegates to [`speedwave_runtime::binary::command`]
/// which resolves the binary path and ensures LIMA_HOME is set.
#[cfg(target_os = "macos")]
fn limactl_command() -> std::process::Command {
    speedwave_runtime::binary::command("limactl")
}

/// Escapes a path for safe interpolation inside PowerShell single-quoted strings.
/// PowerShell single-quoted strings only require doubling of single quotes.
#[cfg(target_os = "windows")]
fn ps_escape(path: &std::path::Path) -> String {
    path.display().to_string().replace('\'', "''")
}

/// Selects the rootfs URL and SHA256 hash for the current host architecture.
#[cfg(target_os = "windows")]
fn wsl_rootfs_for_arch() -> anyhow::Result<(&'static str, &'static str)> {
    match std::env::consts::ARCH {
        "x86_64" => Ok((
            consts::WSL_ROOTFS_URL_AMD64,
            consts::WSL_ROOTFS_SHA256_AMD64,
        )),
        "aarch64" => Ok((
            consts::WSL_ROOTFS_URL_ARM64,
            consts::WSL_ROOTFS_SHA256_ARM64,
        )),
        arch => anyhow::bail!("Unsupported architecture for WSL2 rootfs: {}", arch),
    }
}

/// Selects the nerdctl-full SHA256 hash for the current host architecture.
#[cfg(target_os = "windows")]
fn nerdctl_sha256_for_arch() -> anyhow::Result<&'static str> {
    match std::env::consts::ARCH {
        "x86_64" => Ok(consts::NERDCTL_FULL_SHA256_AMD64),
        "aarch64" => Ok(consts::NERDCTL_FULL_SHA256_ARM64),
        arch => anyhow::bail!("Unsupported architecture for nerdctl-full: {}", arch),
    }
}

/// Returns the path to a bundled resource file, if it exists.
/// Checks `SPEEDWAVE_RESOURCES_DIR` env var first (development/testing),
/// then the standard Tauri resource directory (production).
#[cfg(target_os = "windows")]
fn find_bundled_resource(relative_path: &str) -> Option<PathBuf> {
    // Check SPEEDWAVE_RESOURCES_DIR env var (development/testing)
    if let Ok(resources_dir) = std::env::var("SPEEDWAVE_RESOURCES_DIR") {
        let path = PathBuf::from(&resources_dir).join(relative_path);
        if path.exists() {
            return Some(path);
        }
    }
    // Check next to the current executable (Tauri production layout)
    if let Ok(exe) = std::env::current_exe() {
        if let Some(exe_dir) = exe.parent() {
            let path = exe_dir.join(relative_path);
            if path.exists() {
                return Some(path);
            }
        }
    }
    None
}

/// Verifies SHA256 of a file using PowerShell. Returns `true` if the hash matches.
#[cfg(target_os = "windows")]
fn verify_sha256_ps(file_path: &std::path::Path, expected_sha256: &str) -> bool {
    let escaped = ps_escape(file_path);
    let cmd = format!(
        "(Get-FileHash -Path '{}' -Algorithm SHA256).Hash.ToLower()",
        escaped
    );
    let output = std::process::Command::new("powershell")
        .args(["-NoProfile", "-Command", &cmd])
        .output();
    match output {
        Ok(o) if o.status.success() => {
            let actual = String::from_utf8_lossy(&o.stdout).trim().to_string();
            actual == expected_sha256
        }
        _ => false,
    }
}

pub fn init_vm() -> anyhow::Result<()> {
    #[cfg(target_os = "macos")]
    {
        init_vm_macos()?;
    }

    #[cfg(target_os = "windows")]
    {
        init_vm_windows()?;
    }

    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        init_vm_linux()?;
    }

    let mut state = SetupState::load();
    state.vm_ready = true;
    state.save()?;

    Ok(())
}

#[cfg(target_os = "macos")]
fn init_vm_macos() -> anyhow::Result<()> {
    // Ensure lima.yaml exists
    let data_dir = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?
        .join(consts::DATA_DIR);
    std::fs::create_dir_all(&data_dir)?;
    let lima_config = data_dir.join("lima.yaml");
    if !lima_config.exists() {
        std::fs::write(&lima_config, LIMA_CONFIG)?;
    }

    // Check if Lima VM exists
    let list_output = limactl_command()
        .args(["list", "--format", "{{.Name}}"])
        .output()?;
    let list_str = String::from_utf8_lossy(&list_output.stdout);

    if !list_str
        .lines()
        .any(|line| line.trim() == consts::LIMA_VM_NAME)
    {
        // VM does not exist — create it
        let output = limactl_command()
            .args([
                "create",
                &format!("--name={}", consts::LIMA_VM_NAME),
                "--tty=false",
            ])
            .arg(&lima_config)
            .output()?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("limactl create failed: {}", stderr.trim());
        }
    }

    // Start VM if not running
    let info_output = limactl_command()
        .args(["list", "--format", "{{.Status}}", consts::LIMA_VM_NAME])
        .output()?;
    let status_str = String::from_utf8_lossy(&info_output.stdout);

    if !status_str.trim().eq_ignore_ascii_case("running") {
        let output = limactl_command()
            .args(["start", consts::LIMA_VM_NAME])
            .output()?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("limactl start failed: {}", stderr.trim());
        }
    }

    // Wait for containerd to be ready inside VM (up to 30s)
    let mut ready = false;
    for _ in 0..15 {
        let verify = limactl_command()
            .args([
                "shell",
                consts::LIMA_VM_NAME,
                "--",
                "sudo",
                "nerdctl",
                "info",
            ])
            .output()?;
        if verify.status.success() {
            ready = true;
            break;
        }
        std::thread::sleep(std::time::Duration::from_secs(2));
    }
    if !ready {
        anyhow::bail!(
            "containerd did not become ready inside VM after 30s. \
             Try running: limactl shell {} -- sudo nerdctl info",
            consts::LIMA_VM_NAME
        );
    }

    Ok(())
}

/// Checks whether `newuidmap` is available (required for rootless containers).
#[cfg(unix)]
#[cfg_attr(target_os = "macos", allow(dead_code))]
fn check_uidmap(newuidmap_bin: &str) -> anyhow::Result<()> {
    // newuidmap has no --help flag; use `command -v` to test existence
    let ok = std::process::Command::new("sh")
        .args(["-c", &format!("command -v '{}'", newuidmap_bin)])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !ok {
        anyhow::bail!(consts::UIDMAP_MISSING_MSG);
    }
    Ok(())
}

/// Runs `containerd-rootless-setuptool.sh install` using the given binary path.
#[cfg(unix)]
#[cfg_attr(target_os = "macos", allow(dead_code))]
fn start_rootless_containerd(setup_tool: &str) -> anyhow::Result<()> {
    let output = std::process::Command::new(setup_tool)
        .arg("install")
        .output()?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!(
            "Failed to start rootless containerd: {}\n\
             Ensure systemd --user is available and /etc/subuid + /etc/subgid \
             are configured for your user.",
            stderr.trim()
        );
    }
    Ok(())
}

/// Waits for containerd to become ready by polling `nerdctl info`.
///
/// Retries up to `max_retries` times with `interval` between attempts.
#[cfg(unix)]
#[cfg_attr(target_os = "macos", allow(dead_code))]
fn wait_for_containerd(
    nerdctl_bin: &str,
    max_retries: u32,
    interval: std::time::Duration,
) -> anyhow::Result<()> {
    for _ in 0..max_retries {
        let verify = std::process::Command::new(nerdctl_bin)
            .arg("info")
            .output()?;
        if verify.status.success() {
            return Ok(());
        }
        std::thread::sleep(interval);
    }
    anyhow::bail!(
        "containerd did not become ready after {}s. \
         Try running: containerd-rootless-setuptool.sh install",
        max_retries as u64 * interval.as_secs()
    );
}

/// Initializes rootless containerd on Linux using the bundled nerdctl-full.
///
/// Steps:
/// 1. Verify `newuidmap` (uidmap package) is installed — required for rootless containers
/// 2. Run `containerd-rootless-setuptool.sh install` to start containerd as a systemd --user service
/// 3. Wait for containerd readiness (up to 30s, retrying `nerdctl info`)
#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn init_vm_linux() -> anyhow::Result<()> {
    use speedwave_runtime::binary;

    check_uidmap("newuidmap")?;

    let setup_tool = binary::resolve_binary("containerd-rootless-setuptool.sh");
    start_rootless_containerd(&setup_tool)?;

    let nerdctl = binary::resolve_binary("nerdctl");
    wait_for_containerd(&nerdctl, 15, std::time::Duration::from_secs(2))?;

    Ok(())
}

#[cfg(target_os = "windows")]
fn init_vm_windows() -> anyhow::Result<()> {
    ensure_wsl2_available()?;

    let list = std::process::Command::new("wsl.exe")
        .args(["--list", "--quiet"])
        .output()?;
    let list_str = String::from_utf8_lossy(&list.stdout);
    let distro_exists = list_str
        .lines()
        .any(|l| l.trim().trim_matches('\0') == consts::WSL_DISTRO_NAME);

    if !distro_exists {
        import_wsl_distro()?;
    }

    install_nerdctl_full()?;

    Ok(())
}

/// Checks whether WSL2 is available. If not, triggers an elevated install and
/// bails with a restart prompt.
#[cfg(target_os = "windows")]
fn ensure_wsl2_available() -> anyhow::Result<()> {
    let wsl_available = std::process::Command::new("wsl.exe")
        .args(["--status"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    if !wsl_available {
        let status = std::process::Command::new("powershell")
            .args([
                "-Command",
                "Start-Process wsl.exe -ArgumentList '--install','--no-distribution' -Verb RunAs -Wait",
            ])
            .status()?;
        if !status.success() {
            anyhow::bail!(
                "WSL2 installation failed or was cancelled. \
                 Please enable WSL2 manually: wsl --install"
            );
        }
        anyhow::bail!(
            "WSL2 has been installed. Please restart your computer and run Speedwave setup again."
        );
    }

    Ok(())
}

/// Downloads the Ubuntu rootfs (with SHA256 verification) and imports it as a
/// dedicated WSL2 distribution. Checks for a bundled rootfs first (offline
/// install), then falls back to cached download, then fresh download.
#[cfg(target_os = "windows")]
fn import_wsl_distro() -> anyhow::Result<()> {
    use std::process::Command;

    let data_dir = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?
        .join(consts::DATA_DIR);
    let wsl_dir = data_dir.join("wsl");
    let rootfs_path = wsl_dir.join("ubuntu-rootfs.tar.gz");
    std::fs::create_dir_all(&wsl_dir)?;

    let (rootfs_url, expected_sha256) = wsl_rootfs_for_arch()?;

    // Try bundled rootfs first (offline install from NSIS bundle)
    let mut have_valid_rootfs = false;

    if let Some(bundled) = find_bundled_resource("wsl/ubuntu-rootfs.tar.gz") {
        if verify_sha256_ps(&bundled, expected_sha256) {
            // Copy bundled rootfs to the cache location for wsl --import
            std::fs::copy(&bundled, &rootfs_path)?;
            have_valid_rootfs = true;
        }
    }

    // Check cached download
    if !have_valid_rootfs && rootfs_path.exists() {
        if verify_sha256_ps(&rootfs_path, expected_sha256) {
            have_valid_rootfs = true;
        } else {
            let _ = std::fs::remove_file(&rootfs_path);
        }
    }

    // Fall back to download
    if !have_valid_rootfs {
        let escaped_rootfs = ps_escape(&rootfs_path);
        let download_and_verify = format!(
            "$ProgressPreference = 'SilentlyContinue'; \
             Invoke-WebRequest -Uri '{}' -OutFile '{}'; \
             $hash = (Get-FileHash -Path '{}' -Algorithm SHA256).Hash.ToLower(); \
             if ($hash -ne '{}') {{ \
                 Remove-Item '{}' -Force; \
                 Write-Error \"SHA256 mismatch: expected {}, got $hash\"; \
                 exit 1 \
             }}",
            rootfs_url,
            escaped_rootfs,
            escaped_rootfs,
            expected_sha256,
            escaped_rootfs,
            expected_sha256
        );
        let download = Command::new("powershell")
            .args(["-NoProfile", "-Command", &download_and_verify])
            .status()?;
        if !download.success() {
            anyhow::bail!(
                "Failed to download or verify Ubuntu rootfs for WSL2 \
                 (expected SHA256: {})",
                expected_sha256
            );
        }
    }

    let install_dir = wsl_dir.join(consts::WSL_DISTRO_NAME);
    std::fs::create_dir_all(&install_dir)?;
    let status = Command::new("wsl.exe")
        .args([
            "--import",
            consts::WSL_DISTRO_NAME,
            &install_dir.to_string_lossy(),
            &rootfs_path.to_string_lossy(),
        ])
        .status()?;
    if !status.success() {
        anyhow::bail!("Failed to import Speedwave WSL2 distribution");
    }

    Ok(())
}

/// Installs nerdctl-full (containerd + nerdctl + CNI + BuildKit) inside the
/// Speedwave WSL2 distribution if not already present. Checks for a bundled
/// tarball first (offline install), falling back to download if not found.
#[cfg(target_os = "windows")]
fn install_nerdctl_full() -> anyhow::Result<()> {
    use std::process::Command;

    let nerdctl_check = Command::new("wsl.exe")
        .args(["-d", consts::WSL_DISTRO_NAME, "--", "nerdctl", "--version"])
        .output()?;
    if nerdctl_check.status.success() {
        return Ok(());
    }

    // Try bundled nerdctl-full tarball first (offline install from NSIS bundle).
    // If valid, convert its path to WSL and use `cp` instead of `curl` inside the distro.
    let expected_sha256 = nerdctl_sha256_for_arch()?;
    let mut bundled_wsl_path: Option<String> = None;

    if let Some(bundled) = find_bundled_resource("wsl/nerdctl-full.tar.gz") {
        if verify_sha256_ps(&bundled, expected_sha256) {
            let win_path = bundled.to_string_lossy().to_string();
            let wslpath_output = Command::new("wsl.exe")
                .args([
                    "-d",
                    consts::WSL_DISTRO_NAME,
                    "--",
                    "wslpath",
                    "-u",
                    &win_path,
                ])
                .output()?;
            if wslpath_output.status.success() {
                bundled_wsl_path = Some(
                    String::from_utf8_lossy(&wslpath_output.stdout)
                        .trim()
                        .to_string(),
                );
            }
        }
    }

    // Build install script: use bundled file if available, otherwise download
    let source_commands = if let Some(ref wsl_path) = bundled_wsl_path {
        let escaped = wsl_path.replace('\'', "'\\''");
        format!(
            "mkdir -p /tmp/nerdctl-install\ncp '{}' \"/tmp/nerdctl-install/${{TARBALL}}\"",
            escaped
        )
    } else {
        "mkdir -p /tmp/nerdctl-install\ncurl -fsSL \"$URL\" -o \"/tmp/nerdctl-install/${TARBALL}\""
            .to_string()
    };

    let install_script = format!(
        r#"set -e
ARCH=$(uname -m)
case "$ARCH" in
  x86_64) ARCH="amd64"; EXPECTED="{sha256_amd64}" ;;
  aarch64) ARCH="arm64"; EXPECTED="{sha256_arm64}" ;;
  *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac
VERSION="{version}"
TARBALL="nerdctl-full-${{VERSION}}-linux-${{ARCH}}.tar.gz"
URL="https://github.com/containerd/nerdctl/releases/download/v${{VERSION}}/${{TARBALL}}"
{source_commands}
ACTUAL=$(sha256sum "/tmp/nerdctl-install/${{TARBALL}}" | awk '{{print $1}}')
if [ "$EXPECTED" != "$ACTUAL" ]; then
  echo "SHA256 MISMATCH: expected $EXPECTED, got $ACTUAL"
  rm -rf /tmp/nerdctl-install
  exit 1
fi
tar -C /usr/local -xzf "/tmp/nerdctl-install/${{TARBALL}}"
rm -rf /tmp/nerdctl-install
# Configure containerd as a system service so it starts on every WSL session
mkdir -p /etc/systemd/system
cat > /etc/systemd/system/containerd.service <<UNIT
[Unit]
Description=containerd container runtime
After=network.target
[Service]
ExecStart=/usr/local/bin/containerd
Restart=always
[Install]
WantedBy=multi-user.target
UNIT
# Enable and start — works under both systemd and legacy init
if command -v systemctl >/dev/null 2>&1 && systemctl is-system-running >/dev/null 2>&1; then
  systemctl daemon-reload
  systemctl enable --now containerd
else
  containerd &
  for i in $(seq 1 15); do
    if nerdctl info >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done
fi
if ! nerdctl info >/dev/null 2>&1; then
  echo 'containerd did not become ready after 30s' >&2
  exit 1
fi
"#,
        version = consts::NERDCTL_FULL_VERSION,
        sha256_amd64 = consts::NERDCTL_FULL_SHA256_AMD64,
        sha256_arm64 = consts::NERDCTL_FULL_SHA256_ARM64,
        source_commands = source_commands
    );
    let install = Command::new("wsl.exe")
        .args([
            "-d",
            consts::WSL_DISTRO_NAME,
            "--",
            "bash",
            "-c",
            &install_script,
        ])
        .status()?;
    if !install.success() {
        anyhow::bail!(
            "Failed to install nerdctl-full inside {} WSL2 distribution",
            consts::WSL_DISTRO_NAME
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Step 4: Create project
// ---------------------------------------------------------------------------

pub fn create_project(name: &str, dir: &str) -> anyhow::Result<()> {
    compose::init_project_dirs(name)?;

    let mut user_config = config::load_user_config().unwrap_or_default();

    // Add project to user config if not already present
    if !user_config.projects.iter().any(|p| p.name == name) {
        user_config.projects.push(config::ProjectUserEntry {
            name: name.to_string(),
            dir: dir.to_string(),
            claude: None,
            integrations: None,
        });
    }

    // Set as active project
    user_config.active_project = Some(name.to_string());

    // Save user config
    let config_path = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?
        .join(consts::DATA_DIR)
        .join("config.json");
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let json = serde_json::to_string_pretty(&user_config)?;
    let tmp_path = config_path.with_extension("json.tmp");
    std::fs::write(&tmp_path, &json)?;
    std::fs::rename(&tmp_path, &config_path)?;

    // Render and save compose file
    let project_path = std::path::Path::new(dir);
    let resolved = config::resolve_claude_config(project_path, &user_config, name);
    let integrations = config::resolve_integrations(project_path, &user_config, name);
    let yaml = compose::render_compose(name, dir, &resolved, &integrations)?;
    compose::save_compose(name, &yaml)?;

    let mut state = SetupState::load();
    state.project_created = Some(name.to_string());
    state.save()?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Setup completeness check
// ---------------------------------------------------------------------------

/// Returns `true` when all required setup steps have been completed.
///
/// `cli_linked` is intentionally excluded — CLI symlink creation is optional
/// (the Desktop app works without it) and may fail on restricted systems.
pub fn is_setup_complete() -> bool {
    let state = SetupState::load();
    state.runtime_ready
        && state.vm_ready
        && state.project_created.is_some()
        && state.images_built
        && state.containers_started
}

// ---------------------------------------------------------------------------
// Build container images
// ---------------------------------------------------------------------------

pub fn build_images() -> anyhow::Result<()> {
    let rt = runtime::detect_runtime();
    rt.ensure_ready()?;
    build::build_all_images(rt.as_ref())?;

    let mut state = SetupState::load();
    state.images_built = true;
    state.save()?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Start containers for a project
// ---------------------------------------------------------------------------

pub fn start_containers(project: &str) -> anyhow::Result<()> {
    let rt = runtime::detect_runtime();
    rt.ensure_ready()?;

    // Re-render compose.yml before every start. Dynamic config (mcp-os token,
    // auth keys, addons) may have changed since create_project() first rendered it.
    // Without this, WORKER_OS_URL is missing if mcp-os started after project creation.
    let user_config = config::load_user_config().unwrap_or_default();
    let project_dir = user_config
        .projects
        .iter()
        .find(|p| p.name == project)
        .map(|p| p.dir.as_str())
        .ok_or_else(|| {
            anyhow::anyhow!(
                "project '{}' not found in config — cannot render compose.yml",
                project
            )
        })?;
    let project_path = std::path::Path::new(project_dir);
    let resolved = config::resolve_claude_config(project_path, &user_config, project);
    let integrations = config::resolve_integrations(project_path, &user_config, project);
    let yaml = compose::render_compose(project, project_dir, &resolved, &integrations)?;
    compose::save_compose(project, &yaml)?;

    rt.compose_up(project)?;

    let mut state = SetupState::load();
    state.containers_started = true;
    state.save()?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Check Claude auth status inside the container
// ---------------------------------------------------------------------------

pub fn check_claude_auth(project: &str) -> anyhow::Result<bool> {
    let rt = runtime::detect_runtime();
    let container_name = format!("{}_{}_claude", consts::COMPOSE_PREFIX, project);
    let mut cmd =
        rt.container_exec_piped(&container_name, &[consts::CLAUDE_BINARY, "auth", "status"])?;
    let output = cmd.output()?;
    Ok(output.status.success())
}

// ---------------------------------------------------------------------------
// Factory reset — stops containers, destroys VM, wipes setup state
// ---------------------------------------------------------------------------

/// Spawns a command and waits up to `timeout` for it to finish.
/// If it exceeds the timeout, kills the child and returns `Err`.
///
/// Does not capture stdout/stderr — output goes to the parent's streams.
/// Do not use with `Stdio::piped()` as that risks pipe-buffer deadlock.
#[cfg(any(target_os = "macos", test))]
fn run_with_timeout(
    cmd: &mut std::process::Command,
    timeout: std::time::Duration,
) -> anyhow::Result<std::process::ExitStatus> {
    let program = cmd.get_program().to_string_lossy().to_string();
    let mut child = cmd.spawn()?;
    let start = std::time::Instant::now();
    loop {
        match child.try_wait()? {
            Some(status) => return Ok(status),
            None => {
                if start.elapsed() >= timeout {
                    if let Err(e) = child.kill() {
                        log::warn!("run_with_timeout: kill failed: {e}");
                    }
                    let _ = child.wait();
                    anyhow::bail!(
                        "command '{}' timed out after {}s",
                        program,
                        timeout.as_secs()
                    );
                }
                std::thread::sleep(std::time::Duration::from_millis(200));
            }
        }
    }
}

pub fn factory_reset() -> anyhow::Result<()> {
    let state = SetupState::load();

    // 1. Stop containers for the active project (if any) — with timeout
    //    Even is_available() could theoretically hang, so run the entire
    //    "check + compose_down" block with a timeout.
    if let Some(ref project) = state.project_created {
        log::info!("stopping containers for project={project}");
        let project_clone = project.clone();
        // Uses thread+channel (not run_with_timeout) because compose_down goes
        // through the ContainerRuntime trait, which returns Result — not a Command.
        let (tx, rx) = std::sync::mpsc::channel();
        std::thread::spawn(move || {
            let rt = runtime::detect_runtime();
            if rt.is_available() {
                if let Err(e) = rt.compose_down(&project_clone) {
                    log::warn!("compose_down failed: {e}");
                }
            }
            let _ = tx.send(());
        });
        // Wait up to 30s; if anything hangs, limactl delete --force will clean up
        let timeout = std::time::Duration::from_secs(30);
        match rx.recv_timeout(timeout) {
            Ok(()) => {}
            Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {
                log::warn!("compose_down timed out after 30s, continuing");
            }
            Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                log::warn!("compose_down thread panicked, continuing");
            }
        }
    }

    // 2. Destroy VM (macOS only) — force-stop then force-delete, each with timeout
    #[cfg(target_os = "macos")]
    {
        let timeout = std::time::Duration::from_secs(30);

        log::info!("stopping VM");
        let mut stop_cmd = limactl_command();
        stop_cmd.args(["stop", "--force", consts::LIMA_VM_NAME]);
        if let Err(e) = run_with_timeout(&mut stop_cmd, timeout) {
            log::warn!("limactl stop timed out or failed: {e}, continuing");
        }

        log::info!("deleting VM");
        let mut delete_cmd = limactl_command();
        delete_cmd.args(["delete", consts::LIMA_VM_NAME, "--force"]);
        if let Err(e) = run_with_timeout(&mut delete_cmd, timeout) {
            log::warn!("limactl delete timed out or failed: {e}, continuing");
        }
    }

    // 3. Remove CLI binary
    #[cfg(unix)]
    {
        let target = dirs::home_dir()
            .ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?
            .join(".local")
            .join("bin")
            .join(consts::CLI_BINARY);
        let _ = std::fs::remove_file(&target);
    }
    #[cfg(target_os = "windows")]
    {
        let target = dirs::home_dir()
            .ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?
            .join(consts::DATA_DIR)
            .join("bin")
            .join("speedwave.exe");
        let _ = std::fs::remove_file(&target);
    }

    // 4. Wipe setup state + project list (tokens on disk are preserved)
    let data_dir = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?
        .join(consts::DATA_DIR);
    wipe_state_and_config(&data_dir)?;

    Ok(())
}

/// Resets `setup_state.json` and `config.json` inside `data_dir` to defaults.
///
/// Tokens stored in `data_dir/tokens/` are intentionally preserved.
fn wipe_state_and_config(data_dir: &std::path::Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(data_dir)?;

    // Reset setup state (atomic write via rename)
    let state_path = data_dir.join("setup_state.json");
    let default_state = SetupState::default();
    let state_json = serde_json::to_string_pretty(&default_state)?;
    let tmp_state = state_path.with_extension("json.tmp");
    std::fs::write(&tmp_state, &state_json)?;
    std::fs::rename(&tmp_state, &state_path)?;

    // Reset project list (atomic write via rename)
    let config_path = data_dir.join("config.json");
    let default_config = config::SpeedwaveUserConfig::default();
    let config_json = serde_json::to_string_pretty(&default_config)?;
    let tmp_config = config_path.with_extension("json.tmp");
    std::fs::write(&tmp_config, &config_json)?;
    std::fs::rename(&tmp_config, &config_path)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Step 7: Copy CLI binary to user PATH
// ---------------------------------------------------------------------------

/// Resolves the CLI binary bundled in Tauri resources.
///
/// Layout at runtime:
/// - macOS:   `.app/Contents/Resources/cli/speedwave`
/// - Linux deb/rpm: `<exe_dir>/resources/cli/speedwave`
/// - Linux AppImage: `$APPDIR/usr/lib/pl.speedwave.desktop/resources/cli/speedwave`
/// - Windows: `<exe_dir>/resources/cli/speedwave.exe`
/// - Dev mode fallback: `<exe_dir>/speedwave` (existing behaviour)
pub fn resolve_cli_source() -> Option<std::path::PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let exe_dir = exe.parent()?;
    resolve_cli_source_from(exe_dir)
}

/// Inner implementation that resolves the CLI binary relative to a given exe directory.
/// Separated from `resolve_cli_source()` to allow unit testing with mock filesystem layouts.
fn resolve_cli_source_from(exe_dir: &std::path::Path) -> Option<std::path::PathBuf> {
    #[cfg(not(target_os = "windows"))]
    let binary_name = consts::CLI_BINARY;
    #[cfg(target_os = "windows")]
    let binary_name = "speedwave.exe";

    // Production bundle paths
    #[cfg(target_os = "macos")]
    {
        // .app/Contents/MacOS/../Resources/cli/speedwave
        let resources = exe_dir
            .parent()?
            .join("Resources")
            .join("cli")
            .join(binary_name);
        if resources.exists() {
            return Some(resources);
        }
    }

    #[cfg(target_os = "linux")]
    {
        // Standard Tauri resource path (dev mode and deb/rpm packages)
        let resources = exe_dir.join("resources").join("cli").join(binary_name);
        if resources.exists() {
            return Some(resources);
        }
        // AppImage layout: $APPDIR/usr/lib/<identifier>/resources/cli/<binary>
        // exe_dir = $APPDIR/usr/bin/, one level up = $APPDIR/usr/
        let appimage_resources = exe_dir.parent().map(|usr_dir| {
            usr_dir
                .join("lib")
                .join("pl.speedwave.desktop")
                .join("resources")
                .join("cli")
                .join(binary_name)
        });
        if let Some(path) = appimage_resources.filter(|p| p.exists()) {
            return Some(path);
        }
    }

    #[cfg(target_os = "windows")]
    {
        let resources = exe_dir.join("resources").join("cli").join(binary_name);
        if resources.exists() {
            return Some(resources);
        }
    }

    // Dev mode: Makefile copies CLI to desktop/src-tauri/cli/ before `cargo tauri dev`.
    // exe_dir is desktop/src-tauri/target/{debug,release}/ → go up two levels to desktop/src-tauri/cli/
    let dev_cli_dir = exe_dir
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("cli").join(binary_name));
    if let Some(ref path) = dev_cli_dir {
        if path.exists() {
            return Some(path.clone());
        }
    }

    // Dev mode fallback: CLI binary next to the exe
    let dev_path = exe_dir.join(binary_name);
    if dev_path.exists() {
        return Some(dev_path);
    }

    None
}

/// Copies the CLI binary from `source` into `target_dir` and sets executable permissions on Unix.
pub fn copy_cli_binary(
    source: &std::path::Path,
    target_dir: &std::path::Path,
) -> anyhow::Result<()> {
    if !source.exists() {
        anyhow::bail!("CLI source binary not found at {}", source.display());
    }

    std::fs::create_dir_all(target_dir)?;

    #[cfg(target_os = "windows")]
    let dest = target_dir.join("speedwave.exe");
    #[cfg(not(target_os = "windows"))]
    let dest = target_dir.join(consts::CLI_BINARY);

    // On Windows, the target may be locked by a running CLI process.
    // Treat as non-fatal: keep the old binary until the user closes the CLI.
    #[cfg(target_os = "windows")]
    if let Err(e) = std::fs::copy(source, &dest) {
        log::warn!("could not update CLI binary (file in use?): {e}");
        return Ok(());
    }
    #[cfg(not(target_os = "windows"))]
    std::fs::copy(source, &dest)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&dest)?.permissions();
        perms.set_mode(perms.mode() | 0o111);
        std::fs::set_permissions(&dest, perms)?;
    }

    Ok(())
}

/// Ensures `~/.local/bin` is on PATH by appending an `export` line to existing shell
/// config files (`.bashrc`, `.zshrc`, `.profile`) under the given `home` directory.
///
/// Skips files that don't exist or already contain `.local/bin`.
#[cfg(unix)]
fn ensure_local_bin_on_path(home: &std::path::Path) -> anyhow::Result<()> {
    let export_line = "export PATH=\"$HOME/.local/bin:$PATH\"";
    for rc_file in &[".bashrc", ".zshrc", ".profile"] {
        let rc_path = home.join(rc_file);
        if rc_path.exists() {
            let content = std::fs::read_to_string(&rc_path).unwrap_or_default();
            if !content.contains(".local/bin") {
                let mut f = std::fs::OpenOptions::new().append(true).open(&rc_path)?;
                use std::io::Write;
                writeln!(f, "\n# Added by Speedwave setup")?;
                writeln!(f, "{}", export_line)?;
            }
        }
    }
    Ok(())
}

/// Returns the platform-specific path where the CLI binary is installed.
///
/// - Unix: `~/.local/bin/speedwave`
/// - Windows: `~/.speedwave/bin/speedwave.exe`
pub fn cli_install_path() -> Option<std::path::PathBuf> {
    let home = dirs::home_dir()?;

    #[cfg(unix)]
    let path = home.join(".local").join("bin").join(consts::CLI_BINARY);

    #[cfg(target_os = "windows")]
    let path = home
        .join(consts::DATA_DIR)
        .join("bin")
        .join("speedwave.exe");

    Some(path)
}

/// Copies the CLI binary into the user's PATH and updates shell configuration.
///
/// Called both unconditionally on app startup (to keep the CLI in sync after updates)
/// and during the setup wizard finalize step. Both calls are idempotent.
///
/// Uses [`link_cli_from`] internally for the filesystem operations, then updates
/// the persisted [`SetupState`] to mark `cli_linked = true`.
pub fn link_cli() -> anyhow::Result<()> {
    let cli_source = resolve_cli_source().ok_or_else(|| {
        anyhow::anyhow!(
            "CLI binary not found in app bundle. \
             Ensure the CLI is built and placed in the resources directory."
        )
    })?;

    let home =
        dirs::home_dir().ok_or_else(|| anyhow::anyhow!("cannot determine home directory"))?;

    link_cli_from(&cli_source, &home)?;

    // Mark CLI as linked in setup state
    let mut state = SetupState::load();
    state.cli_linked = true;
    state.save()?;

    Ok(())
}

/// Inner implementation that copies the CLI binary and configures PATH using explicit paths.
///
/// Separated from [`link_cli`] for unit testing without depending on `current_exe()` or
/// the real home directory.
fn link_cli_from(cli_source: &std::path::Path, home: &std::path::Path) -> anyhow::Result<()> {
    #[cfg(unix)]
    {
        let local_bin = home.join(".local").join("bin");
        copy_cli_binary(cli_source, &local_bin)?;
        ensure_local_bin_on_path(home)?;
    }

    #[cfg(target_os = "windows")]
    {
        use std::process::Command;

        let cli_dir = home.join(consts::DATA_DIR).join("bin");

        let cli_dir_str = cli_dir.to_string_lossy().to_string();

        if cli_dir_str.contains('\'')
            || cli_dir_str.contains('"')
            || cli_dir_str.contains('`')
            || cli_dir_str.contains('$')
            || cli_dir_str.contains('*')
            || cli_dir_str.contains('?')
        {
            anyhow::bail!(
                "CLI directory path contains unsafe characters: {}",
                cli_dir_str
            );
        }

        copy_cli_binary(cli_source, &cli_dir)?;

        let script = format!(
            r#"
            $currentPath = [Environment]::GetEnvironmentVariable('Path', 'User')
            if ($currentPath -notlike '*{dir}*') {{
                [Environment]::SetEnvironmentVariable('Path', "$currentPath;{dir}", 'User')
                # Broadcast WM_SETTINGCHANGE so new shells pick up the change
                Add-Type -Namespace Win32 -Name NativeMethods -MemberDefinition @'
                    [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
                    public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
'@
                $HWND_BROADCAST = [IntPtr]0xffff
                $WM_SETTINGCHANGE = 0x1a
                $result = [UIntPtr]::Zero
                [Win32.NativeMethods]::SendMessageTimeout($HWND_BROADCAST, $WM_SETTINGCHANGE, [UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$result) | Out-Null
            }}
            "#,
            dir = cli_dir_str
        );

        let status = Command::new("powershell")
            .args([
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-Command",
                &script,
            ])
            .status()?;
        if !status.success() {
            anyhow::bail!("Failed to add CLI to PATH");
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use std::io::Write;

    /// Validates that a path component does not contain traversal or unsafe characters.
    fn validate_path_component(name: &str, label: &str) -> anyhow::Result<()> {
        if name.is_empty() {
            anyhow::bail!("{label} is empty");
        }
        if name.contains('/') || name.contains('\\') || name.contains("..") {
            anyhow::bail!("{label} '{name}' contains path traversal characters");
        }
        if !name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-' || c == '.')
        {
            anyhow::bail!("{label} '{name}' contains invalid characters");
        }
        Ok(())
    }

    /// Writes token files to `data_dir/tokens/<project>/<service>/` with chmod 600.
    fn write_tokens(
        data_dir: &std::path::Path,
        project: &str,
        service: &str,
        tokens: &HashMap<String, String>,
    ) -> anyhow::Result<()> {
        validate_path_component(project, "project name")?;
        validate_path_component(service, "service name")?;
        for key in tokens.keys() {
            validate_path_component(key, "token key")?;
        }

        let token_dir = data_dir.join("tokens").join(project).join(service);
        std::fs::create_dir_all(&token_dir)?;

        for (key, value) in tokens {
            let token_path = token_dir.join(key);

            #[cfg(unix)]
            {
                use std::os::unix::fs::OpenOptionsExt;
                let mut file = std::fs::OpenOptions::new()
                    .write(true)
                    .create(true)
                    .truncate(true)
                    .mode(0o600)
                    .open(&token_path)?;
                std::io::Write::write_all(&mut file, value.as_bytes())?;
            }
            #[cfg(not(unix))]
            {
                std::fs::write(&token_path, value)?;
            }
        }

        Ok(())
    }

    #[test]
    fn wipe_state_and_config_resets_both_files() {
        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        let data_dir = tmp.path();

        // Seed setup_state.json with non-default values
        let state = SetupState {
            current_step: 5,
            runtime_ready: true,
            vm_ready: true,
            project_created: Some("acme".to_string()),
            tokens_configured: vec!["slack".to_string()],
            images_built: true,
            containers_started: true,
            cli_linked: true,
        };
        let state_path = data_dir.join("setup_state.json");
        let mut f = std::fs::File::create(&state_path).expect("create state file");
        f.write_all(serde_json::to_string(&state).expect("serialize").as_bytes())
            .expect("write state");

        // Seed config.json with projects
        let user_config = config::SpeedwaveUserConfig {
            projects: vec![
                config::ProjectUserEntry {
                    name: "acme".to_string(),
                    dir: "/tmp/acme".to_string(),
                    claude: None,
                    integrations: None,
                },
                config::ProjectUserEntry {
                    name: "beta-corp".to_string(),
                    dir: "/tmp/beta-corp".to_string(),
                    claude: None,
                    integrations: None,
                },
            ],
            active_project: Some("acme".to_string()),
            selected_ide: None,
            log_level: None,
        };
        let config_path = data_dir.join("config.json");
        let json = serde_json::to_string(&user_config).expect("serialize config");
        std::fs::write(&config_path, json).expect("write config");

        // Create a tokens directory that should survive the wipe
        let tokens_dir = data_dir.join("tokens").join("acme").join("slack");
        std::fs::create_dir_all(&tokens_dir).expect("create tokens dir");
        std::fs::write(tokens_dir.join("token.txt"), "secret").expect("write token");

        // Run the wipe
        wipe_state_and_config(data_dir).expect("wipe should succeed");

        // Verify setup_state.json is reset to defaults
        let raw = std::fs::read_to_string(&state_path).expect("read state");
        let reset_state: SetupState = serde_json::from_str(&raw).expect("parse state");
        assert_eq!(reset_state.current_step, 0);
        assert!(!reset_state.runtime_ready);
        assert!(!reset_state.vm_ready);
        assert!(reset_state.project_created.is_none());
        assert!(reset_state.tokens_configured.is_empty());
        assert!(!reset_state.images_built);
        assert!(!reset_state.containers_started);

        // Verify config.json has empty project list
        let raw = std::fs::read_to_string(&config_path).expect("read config");
        let reset_config: config::SpeedwaveUserConfig =
            serde_json::from_str(&raw).expect("parse config");
        assert!(
            reset_config.projects.is_empty(),
            "project list should be empty after factory reset"
        );
        assert!(
            reset_config.active_project.is_none(),
            "active_project should be None after factory reset"
        );

        // Verify tokens survived
        assert!(
            tokens_dir.join("token.txt").exists(),
            "tokens should be preserved"
        );
        assert_eq!(
            std::fs::read_to_string(tokens_dir.join("token.txt")).expect("read token"),
            "secret"
        );
    }

    #[test]
    fn wipe_state_and_config_works_on_empty_dir() {
        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        // No files exist — should still succeed and create defaults
        wipe_state_and_config(tmp.path()).expect("wipe on empty dir should succeed");

        let state_path = tmp.path().join("setup_state.json");
        assert!(state_path.exists(), "setup_state.json should be created");

        let config_path = tmp.path().join("config.json");
        assert!(config_path.exists(), "config.json should be created");

        let raw = std::fs::read_to_string(&config_path).expect("read config");
        let cfg: config::SpeedwaveUserConfig = serde_json::from_str(&raw).expect("parse config");
        assert!(cfg.projects.is_empty());
    }

    // ── SetupState save/load roundtrip ──────────────────────────────────────

    #[test]
    fn setup_state_save_and_load_roundtrip() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let path = tmp.path().join("setup_state.json");

        let state = SetupState {
            current_step: 4,
            runtime_ready: true,
            vm_ready: true,
            project_created: Some("myproject".to_string()),
            tokens_configured: vec!["slack".to_string(), "gitlab".to_string()],
            images_built: true,
            containers_started: false,
            cli_linked: false,
        };

        state.save_to(&path).expect("save should succeed");
        let loaded = SetupState::load_from(&path).expect("load should succeed");

        assert_eq!(loaded.current_step, 4);
        assert!(loaded.runtime_ready);
        assert!(loaded.vm_ready);
        assert_eq!(loaded.project_created, Some("myproject".to_string()));
        assert_eq!(loaded.tokens_configured, vec!["slack", "gitlab"]);
        assert!(loaded.images_built);
        assert!(!loaded.containers_started);
    }

    #[test]
    fn setup_state_load_missing_file_returns_error() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let path = tmp.path().join("nonexistent.json");
        assert!(SetupState::load_from(&path).is_err());
    }

    #[test]
    fn setup_state_default_is_all_false() {
        let state = SetupState::default();
        assert_eq!(state.current_step, 0);
        assert!(!state.runtime_ready);
        assert!(!state.vm_ready);
        assert!(state.project_created.is_none());
        assert!(state.tokens_configured.is_empty());
        assert!(!state.images_built);
        assert!(!state.containers_started);
        assert!(!state.cli_linked);
    }

    // ── is_setup_complete logic ─────────────────────────────────────────────

    #[test]
    fn is_setup_complete_requires_all_fields() {
        // All true → complete
        let complete = SetupState {
            current_step: 8,
            runtime_ready: true,
            vm_ready: true,
            project_created: Some("acme".to_string()),
            tokens_configured: vec![],
            images_built: true,
            containers_started: true,
            cli_linked: true,
        };
        assert!(
            complete.runtime_ready
                && complete.vm_ready
                && complete.project_created.is_some()
                && complete.images_built
                && complete.containers_started
        );

        // Missing project → incomplete
        let no_project = SetupState {
            project_created: None,
            ..complete.clone()
        };
        assert!(
            !(no_project.runtime_ready
                && no_project.vm_ready
                && no_project.project_created.is_some()
                && no_project.images_built
                && no_project.containers_started)
        );

        // Images not built → incomplete
        let no_images = SetupState {
            images_built: false,
            project_created: Some("acme".to_string()),
            ..complete.clone()
        };
        assert!(
            !(no_images.runtime_ready
                && no_images.vm_ready
                && no_images.project_created.is_some()
                && no_images.images_built
                && no_images.containers_started)
        );
    }

    // ── write_tokens ────────────────────────────────────────────────────────

    #[test]
    fn write_tokens_creates_files_with_correct_content() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let tokens = HashMap::from([
            ("api_key".to_string(), "xoxb-secret-123".to_string()),
            (
                "webhook_url".to_string(),
                "https://hooks.slack.com/x".to_string(),
            ),
        ]);

        write_tokens(tmp.path(), "acme", "slack", &tokens).expect("write_tokens should succeed");

        let key_path = tmp.path().join("tokens/acme/slack/api_key");
        let url_path = tmp.path().join("tokens/acme/slack/webhook_url");

        assert_eq!(
            std::fs::read_to_string(&key_path).expect("read api_key"),
            "xoxb-secret-123"
        );
        assert_eq!(
            std::fs::read_to_string(&url_path).expect("read webhook_url"),
            "https://hooks.slack.com/x"
        );
    }

    #[cfg(unix)]
    #[test]
    fn write_tokens_sets_chmod_600() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::tempdir().expect("tempdir");
        let tokens = HashMap::from([("secret".to_string(), "value".to_string())]);

        write_tokens(tmp.path(), "proj", "svc", &tokens).expect("write_tokens");

        let path = tmp.path().join("tokens/proj/svc/secret");
        let mode = std::fs::metadata(&path)
            .expect("metadata")
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "token file should be chmod 600");
    }

    #[test]
    fn write_tokens_multiple_services_isolated() {
        let tmp = tempfile::tempdir().expect("tempdir");

        let slack_tokens = HashMap::from([("token".to_string(), "slack-secret".to_string())]);
        let gitlab_tokens = HashMap::from([("token".to_string(), "gitlab-secret".to_string())]);

        write_tokens(tmp.path(), "acme", "slack", &slack_tokens).expect("slack");
        write_tokens(tmp.path(), "acme", "gitlab", &gitlab_tokens).expect("gitlab");

        // Each service has its own isolated directory
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("tokens/acme/slack/token")).expect("read"),
            "slack-secret"
        );
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("tokens/acme/gitlab/token")).expect("read"),
            "gitlab-secret"
        );

        // Verify no cross-contamination
        assert!(!tmp.path().join("tokens/acme/slack/gitlab-secret").exists());
    }

    // -- validate_path_component tests --

    #[test]
    fn validate_path_component_accepts_valid_names() {
        assert!(validate_path_component("slack", "service").is_ok());
        assert!(validate_path_component("my-service", "service").is_ok());
        assert!(validate_path_component("service_v2", "service").is_ok());
        assert!(validate_path_component("config.json", "key").is_ok());
        assert!(validate_path_component("abc123", "key").is_ok());
    }

    #[test]
    fn validate_path_component_rejects_empty() {
        assert!(validate_path_component("", "service").is_err());
    }

    #[test]
    fn validate_path_component_rejects_slash() {
        let err = validate_path_component("../etc/passwd", "service").unwrap_err();
        assert!(err.to_string().contains("path traversal"));
    }

    #[test]
    fn validate_path_component_rejects_backslash() {
        let err = validate_path_component("..\\windows\\system32", "service").unwrap_err();
        assert!(err.to_string().contains("path traversal"));
    }

    #[test]
    fn validate_path_component_rejects_double_dot() {
        let err = validate_path_component("foo..bar", "key").unwrap_err();
        assert!(err.to_string().contains("path traversal"));
    }

    #[test]
    fn validate_path_component_rejects_special_characters() {
        assert!(validate_path_component("key with spaces", "key").is_err());
        assert!(validate_path_component("key;rm", "key").is_err());
        assert!(validate_path_component("key$(cmd)", "key").is_err());
        assert!(validate_path_component("key`whoami`", "key").is_err());
    }

    // -- write_tokens path traversal prevention --

    #[test]
    fn write_tokens_rejects_traversal_in_service() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let tokens = HashMap::from([("key".to_string(), "value".to_string())]);
        let err = write_tokens(tmp.path(), "proj", "../escape", &tokens).unwrap_err();
        assert!(err.to_string().contains("path traversal"));
    }

    #[test]
    fn write_tokens_rejects_traversal_in_key() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let tokens = HashMap::from([("../../etc/shadow".to_string(), "value".to_string())]);
        let err = write_tokens(tmp.path(), "proj", "slack", &tokens).unwrap_err();
        assert!(err.to_string().contains("path traversal"));
    }

    #[test]
    fn write_tokens_rejects_slash_in_service() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let tokens = HashMap::from([("key".to_string(), "value".to_string())]);
        let err = write_tokens(tmp.path(), "proj", "a/b", &tokens).unwrap_err();
        assert!(err.to_string().contains("path traversal"));
    }

    #[test]
    fn write_tokens_rejects_traversal_in_project() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let tokens = HashMap::from([("key".to_string(), "value".to_string())]);
        let err = write_tokens(tmp.path(), "../escape", "slack", &tokens).unwrap_err();
        assert!(err.to_string().contains("path traversal"));
    }

    // -- atomic writes verification --

    #[test]
    fn save_to_is_atomic_no_tmp_left() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let path = tmp.path().join("setup_state.json");
        let state = SetupState {
            current_step: 3,
            runtime_ready: true,
            ..Default::default()
        };
        state.save_to(&path).expect("save should succeed");

        assert!(path.exists(), "state file should exist");
        assert!(
            !path.with_extension("json.tmp").exists(),
            "tmp file should not exist after atomic write"
        );

        let loaded = SetupState::load_from(&path).expect("load should succeed");
        assert_eq!(loaded.current_step, 3);
        assert!(loaded.runtime_ready);
    }

    #[test]
    fn wipe_is_atomic_no_tmp_left() {
        let tmp = tempfile::tempdir().expect("tempdir");
        wipe_state_and_config(tmp.path()).expect("wipe should succeed");

        let state_tmp = tmp.path().join("setup_state.json.tmp");
        let config_tmp = tmp.path().join("config.json.tmp");
        assert!(!state_tmp.exists(), "state tmp should not exist");
        assert!(!config_tmp.exists(), "config tmp should not exist");
    }

    // -- run_with_timeout tests ─────────────────────────────────────────────

    #[test]
    #[cfg(unix)]
    fn run_with_timeout_succeeds_for_fast_command() {
        use std::process::Command;
        use std::time::Duration;

        let result = run_with_timeout(Command::new("echo").arg("hello"), Duration::from_secs(5));
        assert!(result.is_ok(), "fast command should succeed");
        assert!(result.unwrap().success());
    }

    #[test]
    #[cfg(unix)]
    fn run_with_timeout_kills_slow_command() {
        use std::process::Command;
        use std::time::{Duration, Instant};

        let start = Instant::now();
        let result = run_with_timeout(Command::new("sleep").arg("60"), Duration::from_secs(1));
        let elapsed = start.elapsed();

        assert!(result.is_err(), "slow command should be killed");
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("timed out"),
            "error should mention timeout"
        );
        assert!(
            err_msg.contains("sleep"),
            "error should include program name 'sleep', got: {err_msg}"
        );
        assert!(
            elapsed < Duration::from_secs(5),
            "should not wait for the full 60s, elapsed: {elapsed:?}"
        );
    }

    // -- ps_escape tests (Windows PowerShell path escaping) --

    #[cfg(target_os = "windows")]
    mod ps_escape_tests {
        use super::super::ps_escape;
        use std::path::Path;

        #[test]
        fn plain_path_unchanged() {
            let p = Path::new(r"C:\Users\dev\speedwave");
            assert_eq!(ps_escape(p), r"C:\Users\dev\speedwave");
        }

        #[test]
        fn single_quote_doubled() {
            let p = Path::new(r"C:\Users\it's a path\file");
            assert_eq!(ps_escape(p), r"C:\Users\it''s a path\file");
        }

        #[test]
        fn multiple_single_quotes_all_doubled() {
            let p = Path::new(r"C:\a'b'c'd");
            assert_eq!(ps_escape(p), r"C:\a''b''c''d");
        }

        #[test]
        fn path_with_spaces_preserved() {
            let p = Path::new(r"C:\Program Files\Speedwave 2");
            assert_eq!(ps_escape(p), r"C:\Program Files\Speedwave 2");
        }

        #[test]
        fn empty_path_returns_empty() {
            let p = Path::new("");
            assert_eq!(ps_escape(p), "");
        }
    }

    // Portable ps_escape tests — run on all platforms using the same logic
    #[test]
    fn ps_escape_logic_plain_string() {
        let result = "simple-path".replace('\'', "''");
        assert_eq!(result, "simple-path");
    }

    #[test]
    fn ps_escape_logic_single_quotes_doubled() {
        let result = "it's a test".replace('\'', "''");
        assert_eq!(result, "it''s a test");
    }

    #[test]
    fn ps_escape_logic_multiple_quotes() {
        let result = "a'b'c".replace('\'', "''");
        assert_eq!(result, "a''b''c");
    }

    #[test]
    fn ps_escape_logic_empty_string() {
        let result = "".replace('\'', "''");
        assert_eq!(result, "");
    }

    #[test]
    fn ps_escape_logic_only_quotes() {
        let result = "'''".replace('\'', "''");
        assert_eq!(result, "''''''");
    }

    #[test]
    fn ps_escape_logic_spaces_and_special_chars() {
        let result = "path with spaces & (parens)".replace('\'', "''");
        assert_eq!(result, "path with spaces & (parens)");
    }

    // -- wsl_rootfs_for_arch tests --

    #[cfg(target_os = "windows")]
    mod wsl_rootfs_for_arch_tests {
        use super::super::wsl_rootfs_for_arch;

        #[test]
        fn returns_ok_for_current_arch() {
            // On Windows CI this will be x86_64 or aarch64 — both are valid
            let result = wsl_rootfs_for_arch();
            assert!(result.is_ok(), "should succeed on supported arch");
            let (url, sha) = result.unwrap();
            assert!(url.starts_with("https://"));
            assert_eq!(sha.len(), 64, "SHA256 hash must be 64 hex chars");
        }
    }

    // -- init_vm_linux helper tests (unix: macOS + Linux) --

    #[cfg(unix)]
    mod init_vm_linux_tests {
        use super::super::{check_uidmap, start_rootless_containerd, wait_for_containerd};
        use std::os::unix::fs::PermissionsExt;

        /// Creates an executable script in `dir` with given name and content.
        fn create_mock_script(
            dir: &std::path::Path,
            name: &str,
            content: &str,
        ) -> std::path::PathBuf {
            let path = dir.join(name);
            std::fs::write(&path, content).expect("write mock script");
            let mut perms = std::fs::metadata(&path).expect("metadata").permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&path, perms).expect("chmod");
            path
        }

        #[test]
        fn check_uidmap_missing_returns_error_with_install_instructions() {
            let tmp = tempfile::tempdir().expect("tempdir");
            let fake_bin = tmp.path().join("nonexistent-uidmap-binary");
            let result = check_uidmap(fake_bin.to_str().unwrap());
            assert!(result.is_err());
            let err = result.unwrap_err().to_string();
            assert!(
                err.contains("newuidmap not found"),
                "error should mention newuidmap: {err}"
            );
            assert!(
                err.contains("sudo apt-get install"),
                "error should include Debian instructions: {err}"
            );
            assert!(
                err.contains("sudo dnf install"),
                "error should include Fedora instructions: {err}"
            );
            assert!(
                err.contains("sudo zypper install"),
                "error should include openSUSE instructions: {err}"
            );
        }

        #[test]
        fn check_uidmap_success_when_binary_exists() {
            let tmp = tempfile::tempdir().expect("tempdir");
            let script = create_mock_script(tmp.path(), "newuidmap", "#!/bin/sh\nexit 0\n");
            let result = check_uidmap(script.to_str().unwrap());
            assert!(result.is_ok(), "should succeed when newuidmap exits 0");
        }

        #[test]
        fn start_rootless_containerd_success() {
            let tmp = tempfile::tempdir().expect("tempdir");
            let script = create_mock_script(
                tmp.path(),
                "containerd-rootless-setuptool.sh",
                "#!/bin/sh\nexit 0\n",
            );
            let result = start_rootless_containerd(script.to_str().unwrap());
            assert!(
                result.is_ok(),
                "should succeed when setup tool exits 0: {:?}",
                result.err()
            );
        }

        #[test]
        fn start_rootless_containerd_failure_includes_stderr() {
            let tmp = tempfile::tempdir().expect("tempdir");
            let script = create_mock_script(
                tmp.path(),
                "containerd-rootless-setuptool.sh",
                "#!/bin/sh\necho 'systemd not available' >&2\nexit 1\n",
            );
            let result = start_rootless_containerd(script.to_str().unwrap());
            assert!(result.is_err());
            let err = result.unwrap_err().to_string();
            assert!(
                err.contains("Failed to start rootless containerd"),
                "error should describe failure: {err}"
            );
            assert!(
                err.contains("systemd not available"),
                "error should include stderr: {err}"
            );
            assert!(
                err.contains("/etc/subuid"),
                "error should mention subuid config: {err}"
            );
        }

        #[test]
        fn wait_for_containerd_success_on_first_try() {
            let tmp = tempfile::tempdir().expect("tempdir");
            let script = create_mock_script(tmp.path(), "nerdctl", "#!/bin/sh\nexit 0\n");
            let result = wait_for_containerd(
                script.to_str().unwrap(),
                3,
                std::time::Duration::from_millis(10),
            );
            assert!(
                result.is_ok(),
                "should succeed when nerdctl info exits 0: {:?}",
                result.err()
            );
        }

        #[test]
        fn wait_for_containerd_timeout_when_never_ready() {
            let tmp = tempfile::tempdir().expect("tempdir");
            let script = create_mock_script(tmp.path(), "nerdctl", "#!/bin/sh\nexit 1\n");
            let result = wait_for_containerd(
                script.to_str().unwrap(),
                2,
                std::time::Duration::from_millis(10),
            );
            assert!(result.is_err());
            let err = result.unwrap_err().to_string();
            assert!(
                err.contains("did not become ready"),
                "error should describe timeout: {err}"
            );
            assert!(
                err.contains("containerd-rootless-setuptool.sh install"),
                "error should suggest remedy: {err}"
            );
        }

        #[test]
        fn wait_for_containerd_succeeds_after_retries() {
            let tmp = tempfile::tempdir().expect("tempdir");
            // Script that fails first 2 times, then succeeds on 3rd call.
            // Uses a counter file to track invocations.
            let counter_file = tmp.path().join("counter");
            std::fs::write(&counter_file, "0").expect("init counter");
            let script_content = format!(
                "#!/bin/sh\n\
                 COUNT=$(cat '{counter}')\n\
                 COUNT=$((COUNT + 1))\n\
                 echo $COUNT > '{counter}'\n\
                 if [ $COUNT -ge 3 ]; then exit 0; else exit 1; fi\n",
                counter = counter_file.display()
            );
            let script = create_mock_script(tmp.path(), "nerdctl", &script_content);
            let result = wait_for_containerd(
                script.to_str().unwrap(),
                5,
                std::time::Duration::from_millis(10),
            );
            assert!(
                result.is_ok(),
                "should succeed after retries: {:?}",
                result.err()
            );
        }
    }

    // ── copy_cli_binary tests ─────────────────────────────────────────────

    #[test]
    fn copy_cli_binary_copies_file() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let source_dir = tmp.path().join("source");
        std::fs::create_dir_all(&source_dir).expect("create source dir");

        let source = source_dir.join("speedwave");
        std::fs::write(&source, b"#!/bin/sh\necho hello").expect("write source");

        let target_dir = tmp.path().join("target");
        copy_cli_binary(&source, &target_dir).expect("copy should succeed");

        #[cfg(target_os = "windows")]
        let dest = target_dir.join("speedwave.exe");
        #[cfg(not(target_os = "windows"))]
        let dest = target_dir.join(consts::CLI_BINARY);
        assert!(dest.exists(), "copied binary should exist");
        assert_eq!(
            std::fs::read_to_string(&dest).expect("read"),
            "#!/bin/sh\necho hello"
        );
    }

    #[cfg(unix)]
    #[test]
    fn copy_cli_binary_sets_executable_permission() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::tempdir().expect("tempdir");
        let source = tmp.path().join("speedwave");
        std::fs::write(&source, b"#!/bin/sh\necho hello").expect("write source");

        let target_dir = tmp.path().join("bin");
        copy_cli_binary(&source, &target_dir).expect("copy should succeed");

        let dest = target_dir.join(consts::CLI_BINARY);
        let mode = std::fs::metadata(&dest)
            .expect("metadata")
            .permissions()
            .mode();
        assert_ne!(
            mode & 0o111,
            0,
            "copied binary should have executable permission"
        );
    }

    #[test]
    fn run_with_timeout_returns_error_for_nonexistent_command() {
        use std::process::Command;
        use std::time::Duration;

        let result = run_with_timeout(
            &mut Command::new("nonexistent-binary-xyz-12345"),
            Duration::from_secs(5),
        );
        assert!(result.is_err(), "nonexistent command should fail to spawn");
    }

    #[test]
    #[cfg(unix)]
    fn run_with_timeout_reports_nonzero_exit() {
        use std::process::Command;
        use std::time::Duration;

        let result = run_with_timeout(&mut Command::new("false"), Duration::from_secs(5));
        assert!(result.is_ok(), "command should finish (not timeout)");
        assert!(!result.unwrap().success(), "exit code should be non-zero");
    }

    #[test]
    #[cfg(unix)]
    fn run_with_timeout_zero_duration_kills_immediately() {
        use std::process::Command;
        use std::time::{Duration, Instant};

        let start = Instant::now();
        let result = run_with_timeout(Command::new("sleep").arg("60"), Duration::ZERO);
        let elapsed = start.elapsed();

        assert!(result.is_err(), "zero timeout should kill immediately");
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("timed out"),
            "error should mention timeout"
        );
        assert!(
            err_msg.contains("sleep"),
            "error should include program name 'sleep', got: {err_msg}"
        );
        assert!(
            elapsed < Duration::from_secs(2),
            "should kill near-instantly, elapsed: {elapsed:?}"
        );
    }

    #[test]
    fn copy_cli_binary_returns_error_when_source_missing() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let source = tmp.path().join("nonexistent");
        let target_dir = tmp.path().join("bin");

        let err = copy_cli_binary(&source, &target_dir).unwrap_err();
        assert!(
            err.to_string().contains("not found"),
            "error should mention source not found: {}",
            err
        );
    }

    // ── resolve_cli_source_from tests ─────────────────────────────────────

    #[cfg(target_os = "macos")]
    #[test]
    fn resolve_cli_source_finds_macos_bundle_path() {
        // Simulate: .app/Contents/MacOS/<exe> with Resources/cli/speedwave
        let tmp = tempfile::tempdir().expect("tempdir");
        let contents = tmp.path().join("Contents");
        let macos_dir = contents.join("MacOS");
        let resources_cli = contents.join("Resources").join("cli");
        std::fs::create_dir_all(&macos_dir).expect("create MacOS dir");
        std::fs::create_dir_all(&resources_cli).expect("create Resources/cli dir");
        std::fs::write(resources_cli.join(consts::CLI_BINARY), b"cli-binary")
            .expect("write cli binary");

        let result = resolve_cli_source_from(&macos_dir);
        assert!(result.is_some(), "should find CLI in macOS Resources");
        assert!(
            result
                .unwrap()
                .to_string_lossy()
                .contains("Resources/cli/speedwave"),
            "path should include Resources/cli/"
        );
    }

    #[cfg(not(target_os = "macos"))]
    #[test]
    fn resolve_cli_source_finds_resources_path() {
        // Simulate: <exe_dir>/resources/cli/speedwave
        let tmp = tempfile::tempdir().expect("tempdir");
        let exe_dir = tmp.path().join("exe_dir");
        let resources_cli = exe_dir.join("resources").join("cli");
        std::fs::create_dir_all(&resources_cli).expect("create resources/cli dir");

        #[cfg(target_os = "windows")]
        let binary_name = "speedwave.exe";
        #[cfg(not(target_os = "windows"))]
        let binary_name = consts::CLI_BINARY;

        std::fs::write(resources_cli.join(binary_name), b"cli-binary").expect("write cli binary");

        let result = resolve_cli_source_from(&exe_dir);
        assert!(result.is_some(), "should find CLI in resources");
        let resolved = result.unwrap();
        assert_eq!(
            resolved.parent().unwrap().file_name().unwrap(),
            "cli",
            "path should be in cli/ directory"
        );
        assert_eq!(
            resolved
                .parent()
                .unwrap()
                .parent()
                .unwrap()
                .file_name()
                .unwrap(),
            "resources",
            "cli/ should be under resources/"
        );
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn resolve_cli_source_finds_linux_appimage_path() {
        // Simulate AppImage layout: $APPDIR/usr/bin/<exe>,
        // $APPDIR/usr/lib/pl.speedwave.desktop/resources/cli/speedwave
        let tmp = tempfile::tempdir().expect("tempdir");
        let appdir = tmp.path();
        let usr_bin = appdir.join("usr").join("bin");
        let cli_dir = appdir
            .join("usr")
            .join("lib")
            .join("pl.speedwave.desktop")
            .join("resources")
            .join("cli");
        std::fs::create_dir_all(&usr_bin).expect("create usr/bin");
        std::fs::create_dir_all(&cli_dir).expect("create appimage cli dir");
        std::fs::write(cli_dir.join(consts::CLI_BINARY), b"cli-binary").expect("write cli binary");

        let result = resolve_cli_source_from(&usr_bin);
        assert!(result.is_some(), "should find CLI in AppImage layout");
        assert!(
            result
                .unwrap()
                .to_string_lossy()
                .contains("usr/lib/pl.speedwave.desktop"),
            "path should go through usr/lib/pl.speedwave.desktop"
        );
    }

    #[test]
    fn resolve_cli_source_finds_dev_fallback() {
        // Simulate: <exe_dir>/speedwave (dev mode)
        let tmp = tempfile::tempdir().expect("tempdir");
        let exe_dir = tmp.path().join("exe_dir");
        std::fs::create_dir_all(&exe_dir).expect("create exe dir");

        #[cfg(target_os = "windows")]
        let binary_name = "speedwave.exe";
        #[cfg(not(target_os = "windows"))]
        let binary_name = consts::CLI_BINARY;

        std::fs::write(exe_dir.join(binary_name), b"cli-binary").expect("write cli binary");

        let result = resolve_cli_source_from(&exe_dir);
        assert!(result.is_some(), "should find CLI in dev fallback");
    }

    #[test]
    fn resolve_cli_source_finds_dev_cli_dir() {
        // Simulate: desktop/src-tauri/target/debug/ as exe_dir,
        // desktop/src-tauri/cli/speedwave as CLI binary (placed by Makefile)
        let tmp = tempfile::tempdir().expect("tempdir");
        let src_tauri = tmp.path().join("desktop").join("src-tauri");
        let exe_dir = src_tauri.join("target").join("debug");
        let cli_dir = src_tauri.join("cli");
        std::fs::create_dir_all(&exe_dir).expect("create exe dir");
        std::fs::create_dir_all(&cli_dir).expect("create cli dir");

        #[cfg(target_os = "windows")]
        let binary_name = "speedwave.exe";
        #[cfg(not(target_os = "windows"))]
        let binary_name = consts::CLI_BINARY;

        std::fs::write(cli_dir.join(binary_name), b"cli-binary").expect("write cli binary");

        let result = resolve_cli_source_from(&exe_dir);
        assert!(result.is_some(), "should find CLI in dev cli/ dir");
        assert!(
            result
                .unwrap()
                .ends_with(std::path::Path::new("cli").join(binary_name)),
            "path should end with cli/{binary_name}"
        );
    }

    #[test]
    fn resolve_cli_source_returns_none_when_not_found() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let exe_dir = tmp.path().join("empty_dir");
        std::fs::create_dir_all(&exe_dir).expect("create empty dir");

        let result = resolve_cli_source_from(&exe_dir);
        assert!(result.is_none(), "should return None when CLI not found");
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn resolve_cli_source_prefers_bundle_over_dev() {
        // Both Resources/cli/speedwave and <exe_dir>/speedwave exist;
        // bundle path should be preferred.
        let tmp = tempfile::tempdir().expect("tempdir");
        let contents = tmp.path().join("Contents");
        let macos_dir = contents.join("MacOS");
        let resources_cli = contents.join("Resources").join("cli");
        std::fs::create_dir_all(&macos_dir).expect("create MacOS dir");
        std::fs::create_dir_all(&resources_cli).expect("create Resources/cli dir");
        std::fs::write(resources_cli.join(consts::CLI_BINARY), b"bundle")
            .expect("write bundle cli");
        std::fs::write(macos_dir.join(consts::CLI_BINARY), b"dev").expect("write dev cli");

        let result = resolve_cli_source_from(&macos_dir);
        assert!(result.is_some());
        let content = std::fs::read_to_string(result.unwrap()).expect("read resolved");
        assert_eq!(
            content, "bundle",
            "should prefer bundle path over dev fallback"
        );
    }

    // ── cli_install_path tests ─────────────────────────────────────────────

    #[test]
    fn cli_install_path_returns_platform_specific_path() {
        let path = cli_install_path().expect("should return a path");

        #[cfg(unix)]
        assert!(
            path.to_string_lossy().contains(".local/bin/speedwave"),
            "Unix path should contain .local/bin/speedwave: {}",
            path.display()
        );

        #[cfg(target_os = "windows")]
        assert!(
            path.to_string_lossy()
                .contains(".speedwave\\bin\\speedwave.exe"),
            "Windows path should contain .speedwave\\bin\\speedwave.exe: {}",
            path.display()
        );
    }

    // ── ensure_local_bin_on_path tests ────────────────────────────────────

    #[cfg(unix)]
    #[test]
    fn ensure_local_bin_on_path_appends_to_existing_rc_files() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();

        // Create .bashrc and .zshrc without .local/bin
        std::fs::write(home.join(".bashrc"), "# existing content\n").expect("write .bashrc");
        std::fs::write(home.join(".zshrc"), "# zsh config\n").expect("write .zshrc");

        ensure_local_bin_on_path(home).expect("should succeed");

        let bashrc = std::fs::read_to_string(home.join(".bashrc")).expect("read .bashrc");
        assert!(
            bashrc.contains(".local/bin"),
            ".bashrc should contain PATH export"
        );
        assert!(
            bashrc.contains("# Added by Speedwave setup"),
            ".bashrc should contain Speedwave comment"
        );

        let zshrc = std::fs::read_to_string(home.join(".zshrc")).expect("read .zshrc");
        assert!(
            zshrc.contains(".local/bin"),
            ".zshrc should contain PATH export"
        );
    }

    #[cfg(unix)]
    #[test]
    fn ensure_local_bin_on_path_skips_rc_already_containing_local_bin() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();

        let existing = "# existing\nexport PATH=\"$HOME/.local/bin:$PATH\"\n";
        std::fs::write(home.join(".bashrc"), existing).expect("write .bashrc");

        ensure_local_bin_on_path(home).expect("should succeed");

        let bashrc = std::fs::read_to_string(home.join(".bashrc")).expect("read .bashrc");
        assert_eq!(
            bashrc, existing,
            ".bashrc should not be modified when .local/bin already present"
        );
    }

    #[cfg(unix)]
    #[test]
    fn ensure_local_bin_on_path_skips_nonexistent_rc_files() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        // No rc files exist

        ensure_local_bin_on_path(home).expect("should succeed without error");

        // Verify no rc files were created
        assert!(!home.join(".bashrc").exists());
        assert!(!home.join(".zshrc").exists());
        assert!(!home.join(".profile").exists());
    }

    // ── copy_cli_binary overwrites existing binary ────────────────────────

    #[test]
    fn copy_cli_binary_overwrites_existing_file() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let source = tmp.path().join("speedwave");
        std::fs::write(&source, b"new-version").expect("write source");

        let target_dir = tmp.path().join("bin");
        std::fs::create_dir_all(&target_dir).expect("create target dir");

        #[cfg(target_os = "windows")]
        let binary_name = "speedwave.exe";
        #[cfg(not(target_os = "windows"))]
        let binary_name = consts::CLI_BINARY;

        std::fs::write(target_dir.join(binary_name), b"old-version").expect("write old binary");

        copy_cli_binary(&source, &target_dir).expect("copy should succeed");

        let content = std::fs::read_to_string(target_dir.join(binary_name)).expect("read");
        assert_eq!(content, "new-version", "should overwrite existing binary");
    }

    // ── link_cli_from tests ─────────────────────────────────────────────

    #[test]
    fn link_cli_from_returns_error_when_source_missing() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let source = tmp.path().join("nonexistent");
        let home = tmp.path().join("home");
        std::fs::create_dir_all(&home).expect("create home");

        let err = link_cli_from(&source, &home).unwrap_err();
        assert!(
            err.to_string().contains("not found"),
            "error should mention source not found: {}",
            err
        );

        // No files should be written to the destination
        #[cfg(unix)]
        assert!(
            !home.join(".local").join("bin").exists(),
            "target dir should not be created on failure"
        );
    }

    #[cfg(unix)]
    #[test]
    fn link_cli_from_copies_binary_and_updates_path() {
        let tmp = tempfile::tempdir().expect("tempdir");

        // Create mock CLI source binary
        let source = tmp.path().join("speedwave");
        std::fs::write(&source, b"cli-binary-content").expect("write source");

        // Create home with shell rc files
        let home = tmp.path().join("home");
        std::fs::create_dir_all(&home).expect("create home");
        std::fs::write(home.join(".bashrc"), "# existing bashrc\n").expect("write bashrc");
        std::fs::write(home.join(".zshrc"), "# existing zshrc\n").expect("write zshrc");

        link_cli_from(&source, &home).expect("link_cli_from should succeed");

        // Verify binary copied
        let dest = home.join(".local").join("bin").join(consts::CLI_BINARY);
        assert!(dest.exists(), "CLI binary should exist at destination");
        let content = std::fs::read_to_string(&dest).expect("read dest");
        assert_eq!(content, "cli-binary-content");

        // Verify executable permission
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(&dest)
            .expect("metadata")
            .permissions()
            .mode();
        assert!(mode & 0o111 != 0, "binary should be executable");

        // Verify PATH export appended to rc files
        let bashrc = std::fs::read_to_string(home.join(".bashrc")).expect("read bashrc");
        assert!(
            bashrc.contains(".local/bin"),
            "bashrc should contain .local/bin export"
        );
        let zshrc = std::fs::read_to_string(home.join(".zshrc")).expect("read zshrc");
        assert!(
            zshrc.contains(".local/bin"),
            "zshrc should contain .local/bin export"
        );
    }

    #[cfg(unix)]
    #[test]
    fn link_cli_from_is_idempotent() {
        let tmp = tempfile::tempdir().expect("tempdir");

        let source = tmp.path().join("speedwave");
        std::fs::write(&source, b"v2-binary").expect("write source");

        let home = tmp.path().join("home");
        std::fs::create_dir_all(&home).expect("create home");
        std::fs::write(home.join(".bashrc"), "# bashrc\n").expect("write bashrc");
        std::fs::write(home.join(".zshrc"), "# zshrc\n").expect("write zshrc");

        // Call twice
        link_cli_from(&source, &home).expect("first call");

        // Update source to simulate app update
        std::fs::write(&source, b"v3-binary").expect("update source");
        link_cli_from(&source, &home).expect("second call");

        // Binary should be the latest version
        let dest = home.join(".local").join("bin").join(consts::CLI_BINARY);
        let content = std::fs::read_to_string(&dest).expect("read dest");
        assert_eq!(content, "v3-binary", "should have latest binary content");

        // Shell rc files should have exactly one line referencing .local/bin
        let bashrc = std::fs::read_to_string(home.join(".bashrc")).expect("read bashrc");
        let count = bashrc.lines().filter(|l| l.contains(".local/bin")).count();
        assert_eq!(
            count, 1,
            "bashrc should have exactly one .local/bin line, got {count}"
        );

        let zshrc = std::fs::read_to_string(home.join(".zshrc")).expect("read zshrc");
        let count = zshrc.lines().filter(|l| l.contains(".local/bin")).count();
        assert_eq!(
            count, 1,
            "zshrc should have exactly one .local/bin line, got {count}"
        );
    }

    #[test]
    fn setup_state_preserves_fields_on_cli_linked_update() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let state_path = tmp.path().join("setup_state.json");

        // Pre-seed with cli_linked: false and other fields set
        let initial = SetupState {
            cli_linked: false,
            current_step: 3,
            runtime_ready: true,
            vm_ready: true,
            ..Default::default()
        };
        initial.save_to(&state_path).expect("save initial state");

        // Load, flip cli_linked, save — mirrors what link_cli() does
        let mut state = SetupState::load_from(&state_path).expect("load for update");
        assert!(!state.cli_linked, "cli_linked should start as false");
        state.cli_linked = true;
        state.save_to(&state_path).expect("save updated state");

        // Verify cli_linked changed and other fields preserved
        let final_state = SetupState::load_from(&state_path).expect("load final");
        assert!(
            final_state.cli_linked,
            "cli_linked should be true after update"
        );
        assert_eq!(
            final_state.current_step, 3,
            "current_step should be unchanged"
        );
        assert!(
            final_state.runtime_ready,
            "runtime_ready should be unchanged"
        );
        assert!(final_state.vm_ready, "vm_ready should be unchanged");
    }
}
