import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  effect,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { contextTokensFrom, type RateLimitInfo, type SessionStats } from '../../models/chat';
import { formatContextLabel } from '../../models/llm';
import type { PlanLimits } from '../../models/plan-limits';
import { IconComponent } from '../../shared/icon.component';
import { TooltipDirective } from '../../shared/tooltip.directive';
import { formatTokens, formatUsd } from '../../shared/format-number';
import { UsagePopoverComponent } from './usage-popover.component';
import { usageColor } from './usage-color';

const LIMIT_ALERT_STATUSES: readonly string[] = ['allowed_warning', 'rejected'];

/**
 * Terminal-minimal session stats strip below the composer: in, out, a context ring that opens the
 * context and plan-limits popover, git branch and conversation cost.
 */
@Component({
  selector: 'app-session-stats',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TooltipDirective, IconComponent, UsagePopoverComponent],
  host: { class: 'block', '(document:keydown.escape)': 'close()' },
  template: `
    <div
      data-testid="session-stats"
      class="mono flex flex-wrap items-center gap-x-3 gap-y-1 px-1 py-3 text-[10px] text-[var(--ink-mute)]"
    >
      <span
        class="whitespace-nowrap"
        appTooltip="New input tokens this turn (excludes history served from cache)"
        placement="top"
      >
        in: <span class="text-[var(--teal)]">{{ formatNum(inboundTokens()) }}</span>
      </span>
      <span
        class="whitespace-nowrap"
        appTooltip="Output tokens generated by the model"
        placement="top"
      >
        out:
        <span class="text-[var(--accent)]">{{ formatNum(stats()?.total_output_tokens ?? 0) }}</span>
      </span>

      @if (hasKnownWindow()) {
        <span class="relative hidden items-center sm:inline-flex">
          <button
            #ring
            type="button"
            data-testid="usage-ring"
            class="relative inline-flex h-4 w-4 items-center justify-center rounded-full focus:outline-none focus-visible:ring-1 focus-visible:ring-[var(--teal)]"
            aria-haspopup="dialog"
            [attr.aria-expanded]="open()"
            [attr.aria-label]="ringLabel()"
            [attr.title]="ringLabel()"
            (click)="toggle()"
          >
            <svg viewBox="0 0 16 16" class="h-3.5 w-3.5 -rotate-90" aria-hidden="true">
              <circle
                cx="8"
                cy="8"
                r="6"
                fill="none"
                stroke="var(--line-strong)"
                stroke-width="2.5"
              />
              <circle
                data-testid="usage-ring-fill"
                cx="8"
                cy="8"
                r="6"
                fill="none"
                stroke="currentColor"
                stroke-width="2.5"
                pathLength="100"
                [attr.stroke-dasharray]="(ctxPct() ?? 0) + ' 100'"
                [attr.class]="ringColor()"
              />
            </svg>
            @if (limitAlert(); as alert) {
              <span
                data-testid="usage-ring-warning"
                [attr.data-status]="alert"
                class="absolute -right-0.5 -top-0.5 h-1.5 w-1.5 rounded-full"
                [class]="alert === 'rejected' ? 'bg-red-500' : 'bg-[var(--amber)]'"
              ></span>
            }
          </button>
          @if (open()) {
            <button
              type="button"
              data-testid="usage-popover-backdrop"
              aria-label="Close usage details"
              tabindex="-1"
              class="fixed inset-0 z-30 cursor-default"
              (click)="close()"
            ></button>
            <div
              #popover
              data-testid="usage-popover"
              role="dialog"
              aria-label="Context window and plan usage limits"
              tabindex="-1"
              class="absolute bottom-full left-0 z-40 mb-2 overflow-hidden rounded border border-[var(--line-strong)] bg-[var(--bg-1)] shadow-[0_16px_40px_rgba(0,0,0,0.5)] focus:outline-none"
            >
              <app-usage-popover
                [used]="ctxTotal()"
                [max]="stats()?.context_window_size ?? null"
                [categories]="stats()?.context?.categories ?? []"
                [limits]="limits()"
                [now]="now()"
              />
            </div>
          }
        </span>
      }

      @if (branch(); as br) {
        <span
          class="ml-auto hidden items-center gap-1.5 whitespace-nowrap sm:inline-flex"
          data-testid="session-stats-branch"
          [appTooltip]="'Current git branch: ' + br"
          placement="top"
        >
          <app-icon name="git-branch" class="h-3 w-3" />
          <span class="text-[var(--ink-dim)]">{{ br }}</span>
        </span>
      }

      <span
        class="hidden whitespace-nowrap sm:inline"
        [class.ml-auto]="!branch()"
        appTooltip="Cost of this conversation (excludes subscription and local)"
        placement="top"
      >
        chat:
        <span class="text-[var(--ink-dim)]">{{ costLabel() }}</span>
      </span>
    </div>
  `,
})
export class SessionStatsComponent {
  /** Stats input (signal). */
  readonly stats = input<SessionStats | null>(null);

  /** Current git branch of the active project's working tree, or `null` when not a git repo. */
  readonly branch = input<string | null>(null);

  /** Plan usage limits for the popover; `null` for API-key users and when no data exists. */
  readonly limits = input<PlanLimits | null>(null);

  /** Latest `rate_limit_event`; a warning or rejected status marks the ring. */
  readonly limitSignal = input<RateLimitInfo | null>(null);

  /** Time the limits were last evaluated at, in epoch milliseconds. */
  readonly now = input(0);

  /** Fires when the popover opens, so the owner re-reads the limits. */
  readonly usageOpened = output<void>();

  protected readonly open = signal(false);

  private readonly ring = viewChild<ElementRef<HTMLButtonElement>>('ring');
  private readonly popover = viewChild<ElementRef<HTMLElement>>('popover');

  /** Moves focus into the popover as soon as it renders. */
  constructor() {
    effect(() => this.popover()?.nativeElement.focus());
  }

  /** Project cost label: `$X.XXXX` when priced, `—` when unpriced (subscription/local). */
  readonly costLabel = computed<string>(() => {
    const c = this.stats()?.total_cost;
    return typeof c === 'number' && Number.isFinite(c) ? formatUsd(c, 4) : '—';
  });

  /** New input tokens this turn — `input_tokens` only, excludes cached reads. */
  readonly inboundTokens = computed<number>(() => this.stats()?.usage?.input_tokens ?? 0);

  /**
   * Tokens occupying the context window: Claude Code's own count when it answered, else the last
   * main-chain API call (never the per-turn `usage`, which sums cache reads across calls).
   */
  readonly ctxTotal = computed<number>(() => {
    const stats = this.stats();
    if (stats?.context) return stats.context.total_tokens;
    return stats?.context_usage ? contextTokensFrom(stats.context_usage) : 0;
  });

  /**
   * Context usage as integer percent (0–100); `null` when the window is unknown (ring hidden,
   * never fabricated), 0 when known but unused.
   */
  readonly ctxPct = computed<number | null>(() => {
    const windowSize = this.stats()?.context_window_size;
    if (!windowSize || windowSize <= 0) return null;
    const total = this.ctxTotal();
    if (total <= 0) return 0;
    return Math.min(100, Math.round((total / windowSize) * 100));
  });

  /** True when the context window is known; the ring is meaningless without one. */
  readonly hasKnownWindow = computed<boolean>(() => {
    const windowSize = this.stats()?.context_window_size;
    return !!windowSize && windowSize > 0;
  });

  /** Stroke colour class of the ring fill, by the usage thresholds. */
  readonly ringColor = computed<string>(() => usageColor(this.ctxPct() ?? 0).text);

  /** `used/max` label (e.g. `116k/200k`); empty when usage or window is unknown. */
  readonly ctxUsedMax = computed<string>(() => {
    const total = this.ctxTotal();
    const windowSize = this.stats()?.context_window_size;
    if (total <= 0 || !windowSize || windowSize <= 0) return '';
    return `${formatContextLabel(total)}/${formatContextLabel(windowSize)}`;
  });

  /** `allowed_warning` or `rejected` while the signalled window has not reset yet, else `null`. */
  readonly limitAlert = computed<string | null>(() => {
    const signalled = this.limitSignal();
    if (!signalled || !LIMIT_ALERT_STATUSES.includes(signalled.status)) return null;
    if (signalled.resets_at !== null && signalled.resets_at * 1000 <= this.now()) return null;
    return signalled.status;
  });

  /** Accessible name and tooltip of the ring. */
  readonly ringLabel = computed<string>(() => {
    const used = this.ctxUsedMax();
    const context = `Context window ${this.ctxPct() ?? 0}% used${used ? ` (${used})` : ''}`;
    const alert = this.limitAlert();
    if (alert === 'rejected') return `${context}. Plan usage limit reached`;
    return alert ? `${context}. Plan usage limit warning` : context;
  });

  /** Opens the popover (announcing it to the owner) or closes it. */
  protected toggle(): void {
    if (this.open()) {
      this.close();
      return;
    }
    this.open.set(true);
    this.usageOpened.emit();
  }

  /** Closes the popover and hands focus back to the ring. */
  protected close(): void {
    if (!this.open()) return;
    this.open.set(false);
    this.ring()?.nativeElement.focus();
  }

  /**
   * Formats an integer with thousands separators.
   * @param n - Integer token count to format.
   */
  formatNum(n: number): string {
    return formatTokens(n);
  }
}
