import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import type { SessionStats } from '../../models/chat';
import { formatContextLabel } from '../../models/llm';
import { IconComponent } from '../../shared/icon.component';
import { TooltipDirective } from '../../shared/tooltip.directive';

/** Shared bar segment indices — module-level constant to avoid per-instance allocation. */
const BAR_INDICES: readonly number[] = [0, 1, 2, 3, 4];

/** Shared number formatter for thousands separators (Intl instances are not free). */
const NUMBER_FMT = new Intl.NumberFormat('en-US');

/** Terminal-minimal session stats strip — a single mono line below the composer. */
@Component({
  selector: 'app-session-stats',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, TooltipDirective, IconComponent],
  host: { class: 'block' },
  template: `
    @if (stats(); as s) {
      <div
        data-testid="session-stats"
        class="mono flex flex-wrap items-center gap-x-3 gap-y-1 px-1 py-3 text-[10px] text-[var(--ink-mute)]"
      >
        <!-- Tokens in/out -->
        @if (s.usage; as usage) {
          <span
            class="whitespace-nowrap"
            appTooltip="New input tokens this turn (excludes history served from cache)"
            placement="top"
          >
            in: <span class="text-[var(--teal)]">{{ formatNum(inboundTokens()) }}</span>
          </span>
          <span
            class="whitespace-nowrap"
            appTooltip="Output tokens generated by the model"
            placement="top"
          >
            out:
            <span class="text-[var(--accent)]">{{ formatNum(s.total_output_tokens) }}</span>
          </span>
        }

        <!-- Context bar (sm+) — hidden when ctxPct is null (unknown window). -->
        @if (ctxPct() !== null && ctxPct()! > 0) {
          <span
            class="hidden items-center gap-1.5 whitespace-nowrap sm:inline-flex"
            [appTooltip]="
              'Context window: ' +
              ctxPct() +
              '% used' +
              (ctxUsedMax() ? ' (' + ctxUsedMax() + ')' : '')
            "
            placement="top"
          >
            ctx
            <span class="flex gap-px" [attr.aria-label]="'Context: ' + ctxPct() + '% used'">
              @for (i of barIndices; track i) {
                <span
                  class="inline-block h-1.5 w-1.5"
                  [class]="i < ctxFilled() ? ctxBarColor() : 'bg-[var(--line-strong)]'"
                ></span>
              }
            </span>
            <span class="text-[var(--ink-dim)]">{{ ctxPct() }}%</span>
            @if (ctxUsedMax(); as um) {
              <span>· {{ um }}</span>
            }
          </span>
        }

        <!-- Rate-limit bar (md+) -->
        @if (s.rate_limit) {
          <span
            class="hidden items-center gap-1.5 whitespace-nowrap md:inline-flex"
            [appTooltip]="
              'Rate limit: ' +
              rlPct() +
              '% used' +
              (rlResetTime() ? ' · resets ' + rlResetTime() : '')
            "
            placement="top"
          >
            limit
            <span class="flex gap-px" [attr.aria-label]="'Rate limit: ' + rlPct() + '% used'">
              @for (i of barIndices; track i) {
                <span
                  class="inline-block h-1.5 w-1.5"
                  [class]="i < rlFilled() ? rlBarColor() : 'bg-[var(--line-strong)]'"
                ></span>
              }
            </span>
            <span class="text-[var(--ink-dim)]">{{ rlPct() }}%</span>
            @if (rlResetTime()) {
              <span>· resets {{ rlResetTime() }}</span>
            }
          </span>
        }

        <ng-container *ngTemplateOutlet="branchChip" />

        @if (s.total_cost > 0) {
          <span
            class="hidden whitespace-nowrap sm:inline"
            [class.ml-auto]="!branch()"
            appTooltip="Cumulative cost of this session"
            placement="top"
          >
            session:
            <span class="text-[var(--ink-dim)]">\${{ s.total_cost.toFixed(4) }}</span>
          </span>
        }
      </div>
    } @else {
      <!-- Zero-state: same row with all counters at 0. -->
      <div
        data-testid="session-stats-placeholder"
        class="mono flex flex-wrap items-center gap-x-3 gap-y-1 px-1 py-3 text-[10px] text-[var(--ink-mute)]"
      >
        <span
          class="whitespace-nowrap"
          appTooltip="New input tokens this turn (excludes history served from cache)"
          placement="top"
        >
          in: <span class="text-[var(--teal)]">0</span>
        </span>
        <span
          class="whitespace-nowrap"
          appTooltip="Output tokens generated by the model"
          placement="top"
        >
          out: <span class="text-[var(--accent)]">0</span>
        </span>
        <span
          class="hidden items-center gap-1.5 whitespace-nowrap sm:inline-flex"
          appTooltip="Context window: 0% used"
          placement="top"
        >
          ctx
          <span class="flex gap-px" aria-label="Context: 0% used">
            @for (i of barIndices; track i) {
              <span class="inline-block h-1.5 w-1.5 bg-[var(--line-strong)]"></span>
            }
          </span>
          <span class="text-[var(--ink-dim)]">0%</span>
        </span>
        <span
          class="hidden items-center gap-1.5 whitespace-nowrap md:inline-flex"
          appTooltip="Rate limit: 0% used"
          placement="top"
        >
          limit
          <span class="flex gap-px" aria-label="Rate limit: 0% used">
            @for (i of barIndices; track i) {
              <span class="inline-block h-1.5 w-1.5 bg-[var(--line-strong)]"></span>
            }
          </span>
          <span class="text-[var(--ink-dim)]">0%</span>
        </span>
        <ng-container *ngTemplateOutlet="branchChip" />
        <span
          class="hidden whitespace-nowrap sm:inline"
          [class.ml-auto]="!branch()"
          appTooltip="Cumulative cost of this session"
          placement="top"
        >
          session: <span class="text-[var(--ink-dim)]">$0.0000</span>
        </span>
      </div>
    }

    <ng-template #branchChip>
      @if (branch(); as br) {
        <span
          class="ml-auto hidden items-center gap-1.5 whitespace-nowrap sm:inline-flex"
          data-testid="session-stats-branch"
          [appTooltip]="'Current git branch: ' + br"
          placement="top"
        >
          <app-icon name="git-branch" class="h-3 w-3" />
          <span class="text-[var(--ink-dim)]">{{ br }}</span>
        </span>
      }
    </ng-template>
  `,
})
export class SessionStatsComponent {
  /** Shared segment indices exposed to the template. */
  readonly barIndices = BAR_INDICES;

  /** Stats input (signal). */
  readonly stats = input<SessionStats | null>(null);

  /** Current git branch of the active project's working tree, or `null` when not a git repo. */
  readonly branch = input<string | null>(null);

  /** New input tokens this turn — `input_tokens` only, excludes cached reads. */
  readonly inboundTokens = computed<number>(() => this.stats()?.usage?.input_tokens ?? 0);

  /** Total tokens occupying the context window: `input` + `cache_read` + `cache_write`. */
  readonly ctxTotal = computed<number>(() => {
    const usage = this.stats()?.usage;
    if (!usage) return 0;
    return usage.input_tokens + (usage.cache_read_tokens ?? 0) + (usage.cache_write_tokens ?? 0);
  });

  /** Context window usage as integer percent (0–100), or `null` when window is unknown. */
  readonly ctxPct = computed<number | null>(() => {
    const total = this.ctxTotal();
    if (total <= 0) return 0;
    const windowSize = this.stats()?.context_window_size;
    if (!windowSize || windowSize <= 0) return null;
    return Math.min(100, Math.round((total / windowSize) * 100));
  });

  /** Filled segments (0–5) for the context bar; 0 when ctxPct is null. */
  readonly ctxFilled = computed<number>(() => {
    const pct = this.ctxPct();
    return pct === null ? 0 : bucketFilled(pct);
  });

  /** Tailwind class for filled context-bar segments; empty when ctxPct is null. */
  readonly ctxBarColor = computed<string>(() => {
    const pct = this.ctxPct();
    return pct === null ? '' : barColor(pct);
  });

  /** `used/max` label (e.g. `116k/200k`), or `null` when the context window is unknown. */
  readonly ctxUsedMax = computed<string | null>(() => {
    const total = this.ctxTotal();
    if (total <= 0) return '';
    const windowSize = this.stats()?.context_window_size;
    if (!windowSize || windowSize <= 0) return null;
    return `${formatContextLabel(total)}/${formatContextLabel(windowSize)}`;
  });

  /** Rate-limit utilisation as an integer percentage (0–100). */
  readonly rlPct = computed<number>(() => {
    const stats = this.stats();
    return Math.round(stats?.rate_limit?.utilization ?? 0);
  });

  /** Filled segments (0–5) for the rate-limit bar. */
  readonly rlFilled = computed<number>(() => bucketFilled(this.rlPct()));

  /** Tailwind class for filled rate-limit-bar segments. */
  readonly rlBarColor = computed<string>(() => barColor(this.rlPct()));

  /** Reset time for rate limit formatted as HH:MM (local), or empty string. */
  readonly rlResetTime = computed<string>(() => {
    const epoch = this.stats()?.rate_limit?.resets_at;
    if (!epoch) return '';
    const d = new Date(epoch * 1000);
    return `${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}`;
  });

  /**
   * Formats an integer with `Intl.NumberFormat('en-US')` (thousands separators).
   * @param n - Integer token count to format.
   */
  formatNum(n: number): string {
    return NUMBER_FMT.format(n);
  }
}

/**
 * Bucket the percentage into one of three Tailwind bar-segment colors.
 * @param pct - Percentage in the range 0–100.
 */
function barColor(pct: number): string {
  if (pct >= 77) return 'bg-red-500';
  if (pct >= 50) return 'bg-[var(--amber)]';
  return 'bg-[var(--green)]';
}

/**
 * Converts a percentage (0–100) to the number of filled segments (0–5), rounded.
 * @param pct - Percentage in the range 0–100.
 */
function bucketFilled(pct: number): number {
  return Math.min(5, Math.round((pct / 100) * 5));
}
