FROM rust:1-alpine@sha256:f87aa870663e2b57ec8c69de82c7eedf7383bee987eef7612c0359635eaadb41 AS builder

RUN apk add --no-cache tzdata musl-dev

WORKDIR /build

COPY proxy /build/containers/proxy
COPY crates/pii-engine /build/crates/pii-engine
COPY mcp-servers/policies/rules.yaml /build/mcp-servers/policies/rules.yaml
WORKDIR /build/containers/proxy

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    cargo build --release --locked

FROM scratch

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo

COPY --from=builder /build/containers/proxy/target/release/proxy /proxy

ENTRYPOINT ["/proxy"]
