import type { TurnUsage } from '../models/chat';

/**
 * Per-model price list, in USD per 1 million tokens.
 *
 * - `input`  — standard input tokens (not served from cache).
 * - `cachedInput` — tokens served from the prompt cache (read).
 * - `cacheWrite` — tokens written to the prompt cache.
 * - `output` — tokens generated by the model.
 */
export interface ModelPricing {
  input: number;
  cachedInput: number;
  cacheWrite: number;
  output: number;
}

/**
 * Claude model pricing in USD per 1M tokens.
 *
 * These prices are verified against Anthropic's published rates at
 * https://docs.claude.com/en/docs/about-claude/models and
 * https://www.anthropic.com/pricing. Update this table when Anthropic
 * publishes new rates; keep the verification comment above in sync.
 * Best-effort entries use the latest public rate the maintainer could
 * confirm at commit time; marked with `// best-effort; verify`. Entries
 * for models that do not appear here return `0` from {@link calculateCost}
 * and log a single warning per unknown model ID. Cache-read is 10 % of
 * the base input rate. Cache-write (creation) is 125 % of the base input
 * rate; these conventions are consistent across Claude 3.5, 3.7, 4.x,
 * and 4.5 generations.
 */
export const PRICING: Record<string, ModelPricing> = {
  // All entries verified against the Anthropic published pricing page on
  // 2026-04-25 (https://docs.claude.com/en/docs/about-claude/models#model-pricing).
  // Opus 4.5/4.6/4.7 are all currently shipping models; update when prices change.
  // Opus family — $15 / $75 per 1M
  'claude-opus-4-5': { input: 15, cachedInput: 1.5, cacheWrite: 18.75, output: 75 },
  'claude-opus-4-6': { input: 15, cachedInput: 1.5, cacheWrite: 18.75, output: 75 },
  'claude-opus-4-7': { input: 15, cachedInput: 1.5, cacheWrite: 18.75, output: 75 },
  // The 1-million-token context variant pricing for Opus — best-effort; verify
  'claude-opus-4-6[1m]': { input: 15, cachedInput: 1.5, cacheWrite: 18.75, output: 75 },
  'claude-opus-4-7[1m]': { input: 15, cachedInput: 1.5, cacheWrite: 18.75, output: 75 },

  // Sonnet family — $3 / $15 per 1M
  'claude-sonnet-4-5': { input: 3, cachedInput: 0.3, cacheWrite: 3.75, output: 15 },
  'claude-sonnet-4-6': { input: 3, cachedInput: 0.3, cacheWrite: 3.75, output: 15 },
  'claude-sonnet-4-7': { input: 3, cachedInput: 0.3, cacheWrite: 3.75, output: 15 },
  'claude-sonnet-4-6[1m]': { input: 6, cachedInput: 0.6, cacheWrite: 7.5, output: 22.5 },
  'claude-sonnet-4-7[1m]': { input: 6, cachedInput: 0.6, cacheWrite: 7.5, output: 22.5 },

  // Haiku family — $1 / $5 per 1M — best-effort; verify
  'claude-haiku-4-5': { input: 1, cachedInput: 0.1, cacheWrite: 1.25, output: 5 },
  'claude-haiku-4-6': { input: 1, cachedInput: 0.1, cacheWrite: 1.25, output: 5 },
  'claude-haiku-4-7': { input: 1, cachedInput: 0.1, cacheWrite: 1.25, output: 5 },
};

/** Models seen without a PRICING entry — ensures one warning per id, not per turn. */
const warnedUnknownModels = new Set<string>();

/**
 * Computes per-turn cost in USD for a given Claude model and token usage.
 * Returns 0 for unknown model IDs, and logs a single warning per unknown ID
 * so unknown models do not spam the console in long sessions.
 * @param model - Canonical Claude model ID (e.g. `"claude-opus-4-7"`).
 * @param usage - Per-turn token usage (from {@link TurnUsage}).
 * @returns Cost in USD; `null` when the model is not in {@link PRICING} so
 *   the UI can hide the cost segment instead of displaying a misleading
 *   $0.000 for an unrecognised model id.
 */
export function calculateCost(model: string, usage: TurnUsage): number | null {
  const pricing = PRICING[model];
  if (!pricing) {
    if (!warnedUnknownModels.has(model)) {
      warnedUnknownModels.add(model);
      console.warn(`[pricing] Unknown model "${model}" — cost segment will be hidden.`);
    }
    return null;
  }
  // input_tokens already excludes cached reads in Anthropic's API output; we
  // still subtract defensively in case a future CLI version emits the raw
  // total (clamped to ≥0).
  const billedInput = Math.max(0, usage.input_tokens - usage.cache_read_tokens);
  return (
    (billedInput * pricing.input) / 1_000_000 +
    (usage.cache_read_tokens * pricing.cachedInput) / 1_000_000 +
    (usage.cache_write_tokens * pricing.cacheWrite) / 1_000_000 +
    (usage.output_tokens * pricing.output) / 1_000_000
  );
}

/**
 * Test-only helper: resets the set of unknown models that have already
 * logged a warning, so subsequent calls log again. Intended exclusively
 * for unit tests.
 * @internal
 */
export function _resetUnknownModelWarnings(): void {
  warnedUnknownModels.clear();
}
