import { warn as pluginLogWarn } from '@tauri-apps/plugin-log';
import type { TurnUsage } from '../models/chat';

/**
 * Per-model price list, in USD per 1 million tokens.
 *
 * - `input`  — standard input tokens (not served from cache).
 * - `cachedInput` — tokens served from the prompt cache (read).
 * - `cacheWrite` — tokens written to the prompt cache.
 * - `output` — tokens generated by the model.
 */
export interface ModelPricing {
  input: number;
  cachedInput: number;
  cacheWrite: number;
  output: number;
}

/**
 * Catalog entry from the Rust SSOT `defaults::AnthropicModelInfo`.
 * snake_case matches the serialized struct; `pricing_1m` is null for sub-1M families.
 */
export interface PricedAnthropicModel {
  id: string;
  context_tokens: number;
  pricing: ModelPricing;
  pricing_1m?: ModelPricing | null;
}

/**
 * Bootstrap pricing seed keyed by served model id, from `defaults.rs::ANTHROPIC_MODELS`.
 * Replaced by {@link setPricingCatalog} once the backend catalog loads; parity test in `pricing.spec.ts`.
 */
const SEED_PRICING: Readonly<Record<string, ModelPricing>> = {
  // Fable family — $10 / $50 per 1M; 1M context is the default ([1m] == base)
  'claude-fable-5': { input: 10, cachedInput: 1, cacheWrite: 12.5, output: 50 },
  'claude-fable-5[1m]': { input: 10, cachedInput: 1, cacheWrite: 12.5, output: 50 },

  // Opus family — $5 / $25 per 1M (1M window standard-priced → [1m] == base)
  'claude-opus-4-6': { input: 5, cachedInput: 0.5, cacheWrite: 6.25, output: 25 },
  'claude-opus-4-7': { input: 5, cachedInput: 0.5, cacheWrite: 6.25, output: 25 },
  'claude-opus-4-8': { input: 5, cachedInput: 0.5, cacheWrite: 6.25, output: 25 },
  'claude-opus-4-6[1m]': { input: 5, cachedInput: 0.5, cacheWrite: 6.25, output: 25 },
  'claude-opus-4-7[1m]': { input: 5, cachedInput: 0.5, cacheWrite: 6.25, output: 25 },
  'claude-opus-4-8[1m]': { input: 5, cachedInput: 0.5, cacheWrite: 6.25, output: 25 },

  // Sonnet family — $3 / $15 base, $6 / $22.5 for the 1M window
  'claude-sonnet-4-6': { input: 3, cachedInput: 0.3, cacheWrite: 3.75, output: 15 },
  'claude-sonnet-4-6[1m]': { input: 6, cachedInput: 0.6, cacheWrite: 7.5, output: 22.5 },

  // Haiku family — $1 / $5, no 1M variant
  'claude-haiku-4-5': { input: 1, cachedInput: 0.1, cacheWrite: 1.25, output: 5 },
};

/** Live pricing index keyed by served model id; seeded from {@link SEED_PRICING}. */
const PRICING = new Map<string, ModelPricing>(Object.entries(SEED_PRICING));

/**
 * Replaces the pricing index with backend catalog rates. Clears first; skips malformed entries.
 * @param models - Catalog entries from `list_anthropic_models`.
 */
export function setPricingCatalog(models: readonly PricedAnthropicModel[]): void {
  PRICING.clear();
  for (const m of models) {
    if (!m.pricing || typeof m.pricing.input !== 'number') continue;
    PRICING.set(m.id, m.pricing);
    if (m.context_tokens >= 1_000_000 && m.pricing_1m && typeof m.pricing_1m.input === 'number') {
      PRICING.set(`${m.id}[1m]`, m.pricing_1m);
    }
  }
}

/** Test-only: restores the index to the bootstrap seed between specs. */
export function _resetPricingToSeedForTest(): void {
  PRICING.clear();
  for (const [id, rate] of Object.entries(SEED_PRICING)) {
    PRICING.set(id, rate);
  }
}

/** Test-only: the bootstrap seed (for the parity assertion against the catalog). */
export const _SEED_PRICING_FOR_TEST = SEED_PRICING;

/** Test-only: current size of the pricing index. */
export function _pricingEntryCountForTest(): number {
  return PRICING.size;
}

/**
 * Normalizes a model id into a pricing-index key: strips snapshot date, re-prepends `claude-`, keeps `[1m]`.
 * @param model - Raw model id as reported in a turn's usage metadata.
 */
function normalizeModelId(model: string): string {
  const oneM = model.endsWith('[1m]') ? '[1m]' : '';
  let base = oneM ? model.slice(0, -oneM.length) : model;
  base = base.startsWith('claude-') ? base : `claude-${base.replace('.', '-')}`;
  // Drop a trailing snapshot date (`-YYYYMMDD`).
  base = base.replace(/-\d{8}$/, '');
  return `${base}${oneM}`;
}

/** Models seen without a PRICING entry — dedupes the unknown-model warning to one per id. */
export const _unknownModelWarningsForTest = new Set<string>();

/**
 * Computes per-turn cost in USD for a Claude model and token usage; warns once per unknown id.
 * @param model - Claude model id (e.g. `"claude-opus-4-7"`, `"opus-4.7"`,
 *   `"claude-sonnet-4-6[1m]"`).
 * @param usage - Per-turn token usage (from {@link TurnUsage}).
 * @returns Cost in USD; `null` when the model is not in the pricing index.
 */
export function calculateCost(model: string, usage: TurnUsage): number | null {
  const pricing = PRICING.get(model) ?? PRICING.get(normalizeModelId(model));
  if (!pricing) {
    if (!_unknownModelWarningsForTest.has(model)) {
      _unknownModelWarningsForTest.add(model);
      // Route through the tauri-plugin-log pipeline so the warning lands in the logs ZIP.
      pluginLogWarn(`[pricing] Unknown model "${model}" — cost segment will be hidden.`).catch(
        () => {}
      );
    }
    return null;
  }
  // Subtract cached reads defensively (clamped to ≥0).
  const billedInput = Math.max(0, usage.input_tokens - usage.cache_read_tokens);
  return (
    (billedInput * pricing.input) / 1_000_000 +
    (usage.cache_read_tokens * pricing.cachedInput) / 1_000_000 +
    (usage.cache_write_tokens * pricing.cacheWrite) / 1_000_000 +
    (usage.output_tokens * pricing.output) / 1_000_000
  );
}
