use serde::{Deserialize, Serialize};
use std::collections::HashMap;

pub const CLAUDE_VERSION: &str = "2.1.104";
/// Path inside the container where entrypoint.sh generates the MCP config.
pub const MCP_CONFIG_PATH: &str = "/home/speedwave/.claude/mcp-config.json";

/// Single source of truth for the Anthropic models surfaced in the
/// Settings → LLM Provider dropdown.
///
/// Sourced from the official catalog at
/// <https://platform.claude.com/docs/en/about-claude/models/overview>.
/// Bump this list when Anthropic ships a new family — every consumer
/// (frontend dropdown, future CLI flags, docs) reads from here.
///
/// `latest` flags the actively recommended families (rendered in the
/// "Latest" optgroup); the rest are legacy entries that still work but
/// should nudge users toward the current generation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AnthropicModelInfo {
    /// Stable API alias (no snapshot date). Sent to Claude Code via
    /// `ANTHROPIC_MODEL`. Pinning the dated form would force a config
    /// migration on every model snapshot — Anthropic guarantees the alias
    /// resolves to the current snapshot.
    pub id: &'static str,
    /// Display label shown in the dropdown ("Opus 4.7", "Sonnet 4.6", …).
    pub family: &'static str,
    /// Context window in tokens (1_000_000 for 1M-context models).
    pub context_tokens: u32,
    /// Whether this entry belongs to the "Latest" group. `false` for
    /// still-available legacy snapshots; deprecated/retired models are
    /// removed from the list outright.
    pub latest: bool,
}

/// Curated list of Anthropic models available via Claude Code.
/// **Order matters** — frontend renders this list as-is.
///
/// We surface only the actively-recommended generation. Legacy snapshots
/// can still be selected by typing the id manually (the frontend "(not in
/// catalog)" escape hatch handles existing configs that pin a removed
/// alias), but we don't pre-populate the dropdown with them — encouraging
/// their use was the opposite of what the `latest` flag intended.
pub const ANTHROPIC_MODELS: &[AnthropicModelInfo] = &[
    AnthropicModelInfo {
        id: "claude-opus-4-7",
        family: "Opus 4.7",
        context_tokens: 1_000_000,
        latest: true,
    },
    AnthropicModelInfo {
        id: "claude-sonnet-4-6",
        family: "Sonnet 4.6",
        context_tokens: 1_000_000,
        latest: true,
    },
    AnthropicModelInfo {
        id: "claude-haiku-4-5",
        family: "Haiku 4.5",
        context_tokens: 200_000,
        latest: true,
    },
];

pub const DEFAULT_FLAGS: &[&str] = &[
    // SECURITY RATIONALE: --dangerously-skip-permissions is safe in this context because:
    // 1. Claude runs in an isolated container (Lima VM / WSL2) — kernel-level isolation
    // 2. Container has read-only filesystem except /tmp (noexec,nosuid)
    // 3. Container runs with cap_drop: ALL, no-new-privileges
    // 4. Container has zero service tokens
    // 5. Container network is isolated per-project
    //
    // On Linux rootless nerdctl, containers run as UID 0 (mapped to host user via user
    // namespace). Claude Code refuses --dangerously-skip-permissions as root.
    // IS_SANDBOX=1 in base_env() signals a sandboxed environment, bypassing the root check.
    // See ADR-026 for the full security analysis.
    "--dangerously-skip-permissions",
    // Tells Claude Code where the MCP hub is (generated by entrypoint.sh)
    "--mcp-config",
    MCP_CONFIG_PATH,
    // Only use servers from --mcp-config, ignore any .mcp.json in workspace
    "--strict-mcp-config",
];

pub fn base_env() -> HashMap<String, String> {
    let mut env = HashMap::new();
    env.insert("CLAUDE_CODE_ENABLE_TELEMETRY".into(), "0".into());
    env.insert("DISABLE_AUTOUPDATER".into(), "1".into());
    // Signal sandboxed environment to Claude Code. On Linux rootless nerdctl,
    // containers run as UID 0 and Claude Code refuses --dangerously-skip-permissions
    // as root. IS_SANDBOX=1 bypasses this check. On macOS/Windows (UID 1000) it's a no-op.
    env.insert("IS_SANDBOX".into(), "1".into());
    // Claude Code focus-view mode: alt-screen + differential rendering emits smaller
    // ANSI updates instead of full-frame redraws on every stream chunk. Mitigates PTY
    // write-side backpressure in the CLI (ssh → nerdctl exec → claude) that caused
    // long streaming sessions to freeze. Introduced upstream in Claude Code 2.1.97.
    // See issue #451. Users can override via claude.env.CLAUDE_CODE_NO_FLICKER in
    // .speedwave.json if they prefer the legacy renderer.
    env.insert("CLAUDE_CODE_NO_FLICKER".into(), "1".into());
    env
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_version_is_pinned_semver() {
        // CLAUDE_VERSION must be a concrete semver — never "latest" or "stable".
        // The official installer (claude.ai/install.sh) downloads the exact version
        // and verifies its SHA256 against a version-pinned manifest.json from GCS.
        // Pinning ensures reproducible builds and limits attack surface to a known release.
        assert_ne!(CLAUDE_VERSION, "latest", "must not be 'latest'");
        assert_ne!(CLAUDE_VERSION, "stable", "must not be 'stable'");
        let re = regex::Regex::new(r"^[0-9]+\.[0-9]+\.[0-9]+$").unwrap();
        assert!(
            re.is_match(CLAUDE_VERSION),
            "CLAUDE_VERSION must be a semver (e.g. '2.1.76'), got: '{}'",
            CLAUDE_VERSION
        );
    }

    #[test]
    fn base_env_does_not_set_model() {
        let env = base_env();
        assert!(
            env.get("ANTHROPIC_MODEL").is_none(),
            "base_env() must not set ANTHROPIC_MODEL — the user's Claude Code model \
             selection must not be overridden. Users who want a specific model can set \
             claude.env.ANTHROPIC_MODEL in .speedwave.json or ~/.speedwave/config.json."
        );
    }

    #[test]
    fn base_env_disables_autoupdater() {
        let env = base_env();
        assert_eq!(
            env.get("DISABLE_AUTOUPDATER").map(|s| s.as_str()),
            Some("1")
        );
    }

    #[test]
    fn base_env_disables_telemetry() {
        let env = base_env();
        assert_eq!(
            env.get("CLAUDE_CODE_ENABLE_TELEMETRY").map(|s| s.as_str()),
            Some("0")
        );
    }

    #[test]
    fn base_env_enables_no_flicker() {
        let env = base_env();
        assert_eq!(
            env.get("CLAUDE_CODE_NO_FLICKER").map(|s| s.as_str()),
            Some("1"),
            "CLAUDE_CODE_NO_FLICKER=1 mitigates PTY backpressure by emitting smaller \
             ANSI updates via Claude Code's alt-screen renderer. See issue #451."
        );
    }

    #[test]
    fn base_env_sets_sandbox_flag() {
        let env = base_env();
        assert_eq!(
            env.get("IS_SANDBOX").map(|s| s.as_str()),
            Some("1"),
            "IS_SANDBOX=1 is required for Linux rootless nerdctl where containers run as \
             UID 0 (mapped to host user via user namespace). Without it, Claude Code refuses \
             --dangerously-skip-permissions as root. Defense-in-depth: container isolation \
             (cap_drop ALL, read-only FS, no tokens, per-project network) makes this safe. \
             See ADR-026 for full security analysis."
        );
    }

    #[test]
    fn mcp_config_path_points_to_claude_dir() {
        // entrypoint.sh generates mcp-config.json at this exact path.
        // If this changes, entrypoint.sh and DEFAULT_FLAGS must be updated together.
        assert_eq!(MCP_CONFIG_PATH, "/home/speedwave/.claude/mcp-config.json");
    }

    #[test]
    fn default_flags_include_permission_bypass() {
        assert!(DEFAULT_FLAGS.contains(&"--dangerously-skip-permissions"));
    }

    #[test]
    fn default_flags_include_mcp_config() {
        // Claude Code must receive --mcp-config pointing to the generated config file.
        // Without this, /mcp shows "No MCP servers configured".
        assert!(DEFAULT_FLAGS.contains(&"--mcp-config"));
        assert!(DEFAULT_FLAGS.contains(&MCP_CONFIG_PATH));
    }

    #[test]
    fn default_flags_mcp_config_before_strict() {
        // --mcp-config must come before --strict-mcp-config (Claude Code parses
        // flags sequentially; strict mode validates the config path exists).
        let mcp_pos = DEFAULT_FLAGS.iter().position(|f| *f == "--mcp-config");
        let strict_pos = DEFAULT_FLAGS
            .iter()
            .position(|f| *f == "--strict-mcp-config");
        assert!(
            mcp_pos.unwrap() < strict_pos.unwrap(),
            "--mcp-config must precede --strict-mcp-config in DEFAULT_FLAGS"
        );
    }

    #[test]
    fn default_flags_mcp_config_followed_by_path() {
        // --mcp-config must be immediately followed by the path (it's a flag + value pair).
        let mcp_pos = DEFAULT_FLAGS
            .iter()
            .position(|f| *f == "--mcp-config")
            .expect("--mcp-config must be in DEFAULT_FLAGS");
        assert_eq!(
            DEFAULT_FLAGS[mcp_pos + 1],
            MCP_CONFIG_PATH,
            "--mcp-config must be followed by MCP_CONFIG_PATH"
        );
    }

    #[test]
    fn anthropic_models_list_is_non_empty_and_starts_with_latest() {
        // The dropdown depends on at least one entry being available. The
        // first entry is what the UI surfaces as the topmost option in the
        // "Latest" group, so it must be flagged `latest = true`.
        assert!(!ANTHROPIC_MODELS.is_empty(), "model list must not be empty");
        assert!(
            ANTHROPIC_MODELS[0].latest,
            "first model must be in the Latest group so the dropdown opens with a current option"
        );
    }

    #[test]
    fn anthropic_model_ids_are_unique_and_well_formed() {
        // Duplicate IDs would render as duplicate <option>s; malformed IDs
        // would silently fail when written into ANTHROPIC_MODEL. Catch both
        // at compile-test time.
        let mut seen: std::collections::HashSet<&str> = std::collections::HashSet::new();
        for m in ANTHROPIC_MODELS {
            assert!(seen.insert(m.id), "duplicate model id: {}", m.id);
            assert!(
                m.id.starts_with("claude-"),
                "model id must start with 'claude-', got: {}",
                m.id
            );
            assert!(
                !m.family.is_empty(),
                "family label must not be empty for {}",
                m.id
            );
            // The smallest plausible Claude context window is 200k (Haiku).
            // A "couple hundred" tokens would clearly be wrong; we use a
            // floor that catches accidental zeros / typos without coupling
            // the test to current Anthropic context-window economics.
            assert!(
                m.context_tokens >= 1_000,
                "context_tokens looks too small for {}: {}",
                m.id,
                m.context_tokens
            );
        }
    }

    #[test]
    fn anthropic_models_have_at_least_one_latest_entry() {
        // The "Latest" optgroup must render something — without a flagged
        // entry the dropdown opens on a legacy id, defeating the point of
        // the flag. (The full Latest-before-Legacy ordering invariant is
        // checked by `anthropic_models_latest_entries_precede_legacy`.)
        assert!(
            ANTHROPIC_MODELS.iter().any(|m| m.latest),
            "at least one Latest entry required so the dropdown opens with a current option"
        );
    }

    #[test]
    fn anthropic_models_latest_entries_precede_legacy() {
        // Frontend renders the slice as-is into two optgroups. If a
        // `latest = false` entry appears before any `latest = true` entry
        // the optgroup boundary breaks. Guard the structural invariant
        // explicitly so the comment on `ANTHROPIC_MODELS` remains true
        // without manual review.
        let mut seen_legacy = false;
        for m in ANTHROPIC_MODELS {
            if !m.latest {
                seen_legacy = true;
            } else {
                assert!(
                    !seen_legacy,
                    "latest entry {} must not appear after a legacy entry",
                    m.id
                );
            }
        }
    }
}
