use std::collections::HashMap;

pub const CLAUDE_VERSION: &str = "latest";
pub const DEFAULT_MODEL: &str = "claude-sonnet-4-6";
/// Path inside the container where entrypoint.sh generates the MCP config.
pub const MCP_CONFIG_PATH: &str = "/home/speedwave/.claude/mcp-config.json";

pub const DEFAULT_FLAGS: &[&str] = &[
    // SECURITY RATIONALE: --dangerously-skip-permissions is safe in this context because:
    // 1. Claude runs in an isolated container (Lima VM / WSL2) — kernel-level isolation
    // 2. Container has read-only filesystem except /tmp (noexec,nosuid)
    // 3. Container runs with cap_drop: ALL, no-new-privileges
    // 4. Container has zero service tokens
    // 5. Container network is isolated per-project
    //
    // On Linux rootless nerdctl, containers run as UID 0 (mapped to host user via user
    // namespace). Claude Code refuses --dangerously-skip-permissions as root.
    // IS_SANDBOX=1 in base_env() signals a sandboxed environment, bypassing the root check.
    // See ADR-026 for the full security analysis.
    "--dangerously-skip-permissions",
    // Tells Claude Code where the MCP hub is (generated by entrypoint.sh)
    "--mcp-config",
    MCP_CONFIG_PATH,
    // Only use servers from --mcp-config, ignore any .mcp.json in workspace
    "--strict-mcp-config",
];

pub fn base_env() -> HashMap<String, String> {
    let mut env = HashMap::new();
    env.insert("ANTHROPIC_MODEL".into(), DEFAULT_MODEL.into());
    env.insert("CLAUDE_CODE_ENABLE_TELEMETRY".into(), "0".into());
    env.insert("DISABLE_AUTOUPDATER".into(), "1".into());
    // Signal sandboxed environment to Claude Code. On Linux rootless nerdctl,
    // containers run as UID 0 and Claude Code refuses --dangerously-skip-permissions
    // as root. IS_SANDBOX=1 bypasses this check. On macOS/Windows (UID 1000) it's a no-op.
    env.insert("IS_SANDBOX".into(), "1".into());
    env
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_version_is_latest_channel() {
        // Must be "latest" — pinning a specific version number causes 404 on install.
        // The native installer (claude.ai/install.sh) accepts "latest", "stable", or
        // a concrete semver. We use "latest" so the container always gets a valid build.
        assert_eq!(CLAUDE_VERSION, "latest");
    }

    #[test]
    fn base_env_disables_autoupdater() {
        let env = base_env();
        assert_eq!(
            env.get("DISABLE_AUTOUPDATER").map(|s| s.as_str()),
            Some("1")
        );
    }

    #[test]
    fn base_env_disables_telemetry() {
        let env = base_env();
        assert_eq!(
            env.get("CLAUDE_CODE_ENABLE_TELEMETRY").map(|s| s.as_str()),
            Some("0")
        );
    }

    #[test]
    fn base_env_sets_sandbox_flag() {
        let env = base_env();
        assert_eq!(
            env.get("IS_SANDBOX").map(|s| s.as_str()),
            Some("1"),
            "IS_SANDBOX must be set for Linux rootless nerdctl (UID 0 in container)"
        );
    }

    #[test]
    fn mcp_config_path_points_to_claude_dir() {
        // entrypoint.sh generates mcp-config.json at this exact path.
        // If this changes, entrypoint.sh and DEFAULT_FLAGS must be updated together.
        assert_eq!(MCP_CONFIG_PATH, "/home/speedwave/.claude/mcp-config.json");
    }

    #[test]
    fn default_flags_include_permission_bypass() {
        assert!(DEFAULT_FLAGS.contains(&"--dangerously-skip-permissions"));
    }

    #[test]
    fn default_flags_include_mcp_config() {
        // Claude Code must receive --mcp-config pointing to the generated config file.
        // Without this, /mcp shows "No MCP servers configured".
        assert!(DEFAULT_FLAGS.contains(&"--mcp-config"));
        assert!(DEFAULT_FLAGS.contains(&MCP_CONFIG_PATH));
    }

    #[test]
    fn default_flags_mcp_config_before_strict() {
        // --mcp-config must come before --strict-mcp-config (Claude Code parses
        // flags sequentially; strict mode validates the config path exists).
        let mcp_pos = DEFAULT_FLAGS.iter().position(|f| *f == "--mcp-config");
        let strict_pos = DEFAULT_FLAGS
            .iter()
            .position(|f| *f == "--strict-mcp-config");
        assert!(
            mcp_pos.unwrap() < strict_pos.unwrap(),
            "--mcp-config must precede --strict-mcp-config in DEFAULT_FLAGS"
        );
    }

    #[test]
    fn default_flags_mcp_config_followed_by_path() {
        // --mcp-config must be immediately followed by the path (it's a flag + value pair).
        let mcp_pos = DEFAULT_FLAGS
            .iter()
            .position(|f| *f == "--mcp-config")
            .expect("--mcp-config must be in DEFAULT_FLAGS");
        assert_eq!(
            DEFAULT_FLAGS[mcp_pos + 1],
            MCP_CONFIG_PATH,
            "--mcp-config must be followed by MCP_CONFIG_PATH"
        );
    }
}
