use std::collections::HashMap;

pub const CLAUDE_VERSION: &str = "2.1.81";
/// Path inside the container where entrypoint.sh generates the MCP config.
pub const MCP_CONFIG_PATH: &str = "/home/speedwave/.claude/mcp-config.json";

pub const DEFAULT_FLAGS: &[&str] = &[
    // SECURITY RATIONALE: --dangerously-skip-permissions is safe in this context because:
    // 1. Claude runs in an isolated container (Lima VM / WSL2) — kernel-level isolation
    // 2. Container has read-only filesystem except /tmp (noexec,nosuid)
    // 3. Container runs with cap_drop: ALL, no-new-privileges
    // 4. Container has zero service tokens
    // 5. Container network is isolated per-project
    //
    // On Linux rootless nerdctl, containers run as UID 0 (mapped to host user via user
    // namespace). Claude Code refuses --dangerously-skip-permissions as root.
    // IS_SANDBOX=1 in base_env() signals a sandboxed environment, bypassing the root check.
    // See ADR-026 for the full security analysis.
    "--dangerously-skip-permissions",
    // Tells Claude Code where the MCP hub is (generated by entrypoint.sh)
    "--mcp-config",
    MCP_CONFIG_PATH,
    // Only use servers from --mcp-config, ignore any .mcp.json in workspace
    "--strict-mcp-config",
];

pub fn base_env() -> HashMap<String, String> {
    let mut env = HashMap::new();
    env.insert("CLAUDE_CODE_ENABLE_TELEMETRY".into(), "0".into());
    env.insert("DISABLE_AUTOUPDATER".into(), "1".into());
    // Signal sandboxed environment to Claude Code. On Linux rootless nerdctl,
    // containers run as UID 0 and Claude Code refuses --dangerously-skip-permissions
    // as root. IS_SANDBOX=1 bypasses this check. On macOS/Windows (UID 1000) it's a no-op.
    env.insert("IS_SANDBOX".into(), "1".into());
    env
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_version_is_pinned_semver() {
        // CLAUDE_VERSION must be a concrete semver — never "latest" or "stable".
        // The official installer (claude.ai/install.sh) downloads the exact version
        // and verifies its SHA256 against a version-pinned manifest.json from GCS.
        // Pinning ensures reproducible builds and limits attack surface to a known release.
        assert_ne!(CLAUDE_VERSION, "latest", "must not be 'latest'");
        assert_ne!(CLAUDE_VERSION, "stable", "must not be 'stable'");
        let re = regex::Regex::new(r"^[0-9]+\.[0-9]+\.[0-9]+$").unwrap();
        assert!(
            re.is_match(CLAUDE_VERSION),
            "CLAUDE_VERSION must be a semver (e.g. '2.1.76'), got: '{}'",
            CLAUDE_VERSION
        );
    }

    #[test]
    fn base_env_does_not_set_model() {
        let env = base_env();
        assert!(
            env.get("ANTHROPIC_MODEL").is_none(),
            "base_env() must not set ANTHROPIC_MODEL — the user's Claude Code model \
             selection must not be overridden. Users who want a specific model can set \
             claude.env.ANTHROPIC_MODEL in .speedwave.json or ~/.speedwave/config.json."
        );
    }

    #[test]
    fn base_env_disables_autoupdater() {
        let env = base_env();
        assert_eq!(
            env.get("DISABLE_AUTOUPDATER").map(|s| s.as_str()),
            Some("1")
        );
    }

    #[test]
    fn base_env_disables_telemetry() {
        let env = base_env();
        assert_eq!(
            env.get("CLAUDE_CODE_ENABLE_TELEMETRY").map(|s| s.as_str()),
            Some("0")
        );
    }

    #[test]
    fn base_env_sets_sandbox_flag() {
        let env = base_env();
        assert_eq!(
            env.get("IS_SANDBOX").map(|s| s.as_str()),
            Some("1"),
            "IS_SANDBOX=1 is required for Linux rootless nerdctl where containers run as \
             UID 0 (mapped to host user via user namespace). Without it, Claude Code refuses \
             --dangerously-skip-permissions as root. Defense-in-depth: container isolation \
             (cap_drop ALL, read-only FS, no tokens, per-project network) makes this safe. \
             See ADR-026 for full security analysis."
        );
    }

    #[test]
    fn mcp_config_path_points_to_claude_dir() {
        // entrypoint.sh generates mcp-config.json at this exact path.
        // If this changes, entrypoint.sh and DEFAULT_FLAGS must be updated together.
        assert_eq!(MCP_CONFIG_PATH, "/home/speedwave/.claude/mcp-config.json");
    }

    #[test]
    fn default_flags_include_permission_bypass() {
        assert!(DEFAULT_FLAGS.contains(&"--dangerously-skip-permissions"));
    }

    #[test]
    fn default_flags_include_mcp_config() {
        // Claude Code must receive --mcp-config pointing to the generated config file.
        // Without this, /mcp shows "No MCP servers configured".
        assert!(DEFAULT_FLAGS.contains(&"--mcp-config"));
        assert!(DEFAULT_FLAGS.contains(&MCP_CONFIG_PATH));
    }

    #[test]
    fn default_flags_mcp_config_before_strict() {
        // --mcp-config must come before --strict-mcp-config (Claude Code parses
        // flags sequentially; strict mode validates the config path exists).
        let mcp_pos = DEFAULT_FLAGS.iter().position(|f| *f == "--mcp-config");
        let strict_pos = DEFAULT_FLAGS
            .iter()
            .position(|f| *f == "--strict-mcp-config");
        assert!(
            mcp_pos.unwrap() < strict_pos.unwrap(),
            "--mcp-config must precede --strict-mcp-config in DEFAULT_FLAGS"
        );
    }

    #[test]
    fn default_flags_mcp_config_followed_by_path() {
        // --mcp-config must be immediately followed by the path (it's a flag + value pair).
        let mcp_pos = DEFAULT_FLAGS
            .iter()
            .position(|f| *f == "--mcp-config")
            .expect("--mcp-config must be in DEFAULT_FLAGS");
        assert_eq!(
            DEFAULT_FLAGS[mcp_pos + 1],
            MCP_CONFIG_PATH,
            "--mcp-config must be followed by MCP_CONFIG_PATH"
        );
    }
}
