//! VM provisioning primitives (Lima / WSL2 / nerdctl).
//!
//! SSOT for the platform provisioning steps the setup wizard orchestrates:
//! the Lima VM YAML builder + migration check, WSL2 distro import,
//! nerdctl-full install, and the `.wslconfig` / `wsl.conf` mergers. Pure Rust,
//! no Tauri — callers in the desktop crate keep the wizard-state orchestration
//! and pass plain data in.

use crate::consts;
#[cfg(any(target_os = "windows", test))]
use std::path::PathBuf;

// ---------------------------------------------------------------------------
// Lima VM config (macOS)
// ---------------------------------------------------------------------------

/// Desired Lima VM memory as a Lima-compatible string (e.g. `"16GiB"`).
///
/// Uses adaptive scaling from [`crate::resources`]:
/// VM = host_ram / 2, clamped 8–32 GiB (≤50% of host RAM at/above the 16 GiB
/// minimum supported host; the 8 GiB floor makes the always-on set fit).
///
/// Older installs with lower values are auto-migrated by
/// [`ensure_lima_vm_config`].
#[cfg(any(target_os = "macos", test))]
pub fn desired_lima_vm_memory() -> String {
    let gib = crate::resources::desired_vm_memory_gib(crate::resources::host_total_memory_gib());
    format!("{gib}GiB")
}

/// Desired Lima VM vCPU count derived from host logical CPUs (macOS).
#[cfg(any(target_os = "macos", test))]
pub fn desired_lima_vm_cpus() -> u32 {
    crate::resources::desired_vm_cpus(crate::resources::host_logical_cpus())
}

/// Default Lima VM configuration for Speedwave.
/// Uses Apple Virtualization Framework (vz) with containerd + nerdctl.
/// Memory and CPU are adaptive based on host RAM/cores — see
/// [`desired_lima_vm_memory`] and [`desired_lima_vm_cpus`].
#[cfg(any(target_os = "macos", test))]
pub fn lima_config() -> String {
    format!(
        r#"# Speedwave Lima VM — auto-generated by setup wizard
vmType: vz
vmOpts:
  vz:
    rosetta:
      enabled: true
      binfmt: true
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
cpus: {}
memory: "{}"
disk: "50GiB"
mountType: virtiofs
networks:
  - vzNAT: true
mounts:
  - location: "~"
    writable: true
containerd:
  system: true
  user: false
provision:
  - mode: boot
    script: |
      #!/bin/sh
      # Make eth0 (vzNAT) the preferred default route, not lima0 (usernet).
      #
      # Why: Apple VZ NAT on eth0 inherits the macOS host routing table
      # transparently — both public Internet and every VPN tunnel the host
      # is connected to (IPSec, WireGuard, Tailscale). Lima's built-in
      # usernet (lima0) runs a user-mode TCP stack on the host and only
      # reaches services that need no host VPN; it silently times out on
      # corporate VPNs and on Tailscale subnet routes.
      #
      # Lima's stock netplan ships lima0 metric=100 (preferred) and
      # eth0 metric=200. We drop in a higher-numbered netplan file that
      # overrides metrics and disables DHCP-installed default routes on
      # lima0 — no edits to the lima-managed file, no hard-coded IPs.
      #
      # `mode: boot` maps to cloud-init's `bootcmd` — re-runs on every VM
      # start. Idempotent: the heredoc just rewrites the same file. This
      # guarantees existing VMs upgrading via `lima_vm_config_needs_update`
      # pick the fix up on their next restart without needing cloud-init
      # state reset.
      set -eu
      mkdir -p /etc/netplan
      cat > /etc/netplan/99-speedwave-prefer-vznat.yaml <<'YAML'
      network:
        version: 2
        ethernets:
          eth0:
            dhcp4-overrides:
              route-metric: 100
          lima0:
            dhcp4-overrides:
              route-metric: 300
              use-routes: false
      YAML
      chmod 600 /etc/netplan/99-speedwave-prefer-vznat.yaml
      netplan apply
"#,
        desired_lima_vm_cpus(),
        desired_lima_vm_memory()
    )
}

/// Returns a `Command` for `limactl` with bundled-binary resolution and
/// isolated `LIMA_HOME`. Delegates to [`crate::binary::command`] which resolves
/// the binary path and ensures LIMA_HOME is set.
#[cfg(target_os = "macos")]
fn limactl_command() -> std::process::Command {
    crate::binary::command("limactl")
}

/// Returns `true` if the Lima config needs regenerating: the VPN netplan
/// drop-in is missing, or `memory`/`cpus` drifted from the SSOT formulas.
/// Unparseable values are treated as no-drift (don't touch a hand-mangled file).
#[cfg(any(target_os = "macos", test))]
pub fn lima_vm_config_needs_update(config_content: &str) -> bool {
    use crate::resources;
    let desired_gib = resources::desired_vm_memory_gib(resources::host_total_memory_gib());
    lima_vm_config_needs_update_with(config_content, desired_gib, desired_lima_vm_cpus())
}

/// Testable variant: compares config content against explicit desired memory + cpus.
#[cfg(any(target_os = "macos", test))]
pub fn lima_vm_config_needs_update_with(
    config_content: &str,
    desired_gib: u32,
    desired_cpus: u32,
) -> bool {
    // Trigger migration when the VPN-aware netplan drop-in is absent —
    // existing pre-update installs (including ones with the old `ip route del`
    // provision) need the new netplan-based fix injected on next boot.
    // See `lima_config()` doc and lima-vm/lima#2984.
    if !config_content.contains("99-speedwave-prefer-vznat.yaml") {
        return true;
    }
    // Whether a `prefix` line exists at all (regardless of parseability).
    let line_present = |prefix: &str| config_content.lines().any(|l| l.trim().starts_with(prefix));
    // Parse a `memory: "8GiB"` or `cpus: 4` value to u32. `cpus` has no GiB
    // suffix, so strip it optionally; present-but-unparseable → None (don't
    // touch a hand-mangled value).
    let line_val = |prefix: &str| -> Option<u32> {
        config_content.lines().find_map(|line| {
            line.trim().strip_prefix(prefix).and_then(|rest| {
                let v = rest.trim().trim_matches('"').trim();
                v.strip_suffix("GiB").unwrap_or(v).parse::<u32>().ok()
            })
        })
    };
    // Regenerate if EITHER memory or cpus is absent (the SSOT line was never
    // written — e.g. a pre-adaptive-cpus config) or drifted from the formula.
    // Present-but-unparseable → "no drift" (don't clobber a hand-mangled value).
    let needs_update = |prefix: &str, desired: u32| -> bool {
        if !line_present(prefix) {
            return true; // line absent — regenerate to write the SSOT value
        }
        line_val(prefix).is_some_and(|current| current != desired)
    };
    needs_update("memory:", desired_gib) || needs_update("cpus:", desired_cpus)
}

/// Migrates the Lima VM config on existing installs when it drifts from the
/// SSOT (memory, cpus, or the VPN netplan drop-in — see
/// [`lima_vm_config_needs_update`]). Fully regenerates `lima.yaml` from
/// [`lima_config`] (a generated file — user edits are not preserved, per
/// ADR-068), rewrites source + instance config, and restarts the VM if running.
/// No-op on a fresh install (template absent) or when nothing drifted.
#[cfg(target_os = "macos")]
pub fn ensure_lima_vm_config() -> anyhow::Result<()> {
    use crate::binary;
    let data_dir = consts::data_dir();
    let source_template = data_dir.join("lima.yaml");

    // Fresh install — init_vm_macos will create it with correct config
    if !source_template.exists() {
        return Ok(());
    }

    let content = std::fs::read_to_string(&source_template)?;
    if !lima_vm_config_needs_update(&content) {
        return Ok(());
    }

    log::info!(
        "Lima VM config migration: regenerating from SSOT (memory {}, cpus {}; host_ram/2 + host_cores/2)",
        desired_lima_vm_memory(),
        desired_lima_vm_cpus()
    );

    // Check if VM exists
    let list_output = limactl_command()
        .args(["list", "--format", "{{.Name}}"])
        .output()?;
    let list_str = String::from_utf8_lossy(&list_output.stdout);
    let vm_exists = list_str
        .lines()
        .any(|line| line.trim() == consts::lima_vm_name());

    // Stop VM if running
    if vm_exists {
        let status_output = limactl_command()
            .args(["list", "--format", "{{.Status}}", consts::lima_vm_name()])
            .output()?;
        let status_str = String::from_utf8_lossy(&status_output.stdout);
        if status_str.trim().eq_ignore_ascii_case("running") {
            log::warn!(
                "Stopping VM for memory migration — any running Claude sessions will be interrupted"
            );
            let timeout = std::time::Duration::from_secs(30);
            let mut stop_cmd = limactl_command();
            stop_cmd.args(["stop", consts::lima_vm_name()]);
            if let Err(e) = binary::run_with_timeout(&mut stop_cmd, timeout) {
                log::warn!("graceful stop failed ({e}), forcing stop");
                let mut force_cmd = limactl_command();
                force_cmd.args(["stop", "--force", consts::lima_vm_name()]);
                if let Err(e2) = binary::run_with_timeout(&mut force_cmd, timeout) {
                    log::warn!("forced stop also failed: {e2}, continuing with config update");
                }
            }
        }
    }

    // Full regeneration from the SSOT `lima_config()` — both `cpus` and
    // `memory` (and the provision block) always reflect the current formula.
    // `lima.yaml` is a generated file (like compose.yml); user edits are not
    // preserved by design.
    let regenerated = lima_config();
    if content.trim() != regenerated.trim() {
        log::warn!(
            "Lima VM config at {} is regenerated from the SSOT template — any manual edits are discarded",
            source_template.display()
        );
    }
    std::fs::write(&source_template, &regenerated)?;

    // Update instance config too (may not exist if VM was never created).
    let instance_config = data_dir
        .join(consts::LIMA_SUBDIR)
        .join(consts::lima_vm_name())
        .join("lima.yaml");
    if instance_config.exists() {
        std::fs::write(&instance_config, &regenerated)?;
    }

    // Restart VM if it existed
    if vm_exists {
        log::info!("Starting VM after memory migration");
        init_vm_macos()?;
    }

    log::info!("Lima VM config migration complete");
    Ok(())
}

/// Creates the Lima VM (if absent), starts it, and waits for containerd to be
/// ready inside it. Writes the SSOT `lima.yaml` on first run.
#[cfg(target_os = "macos")]
pub fn init_vm_macos() -> anyhow::Result<()> {
    // Ensure lima.yaml exists
    let data_dir = consts::data_dir();
    std::fs::create_dir_all(data_dir)?;
    let lima_config_path = data_dir.join("lima.yaml");
    if !lima_config_path.exists() {
        std::fs::write(&lima_config_path, lima_config())?;
    }

    // Check if Lima VM exists
    let list_output = limactl_command()
        .args(["list", "--format", "{{.Name}}"])
        .output()?;
    let list_str = String::from_utf8_lossy(&list_output.stdout);

    if !list_str
        .lines()
        .any(|line| line.trim() == consts::lima_vm_name())
    {
        // VM does not exist — create it
        let output = limactl_command()
            .args([
                "create",
                &format!("--name={}", consts::lima_vm_name()),
                "--tty=false",
            ])
            .arg(&lima_config_path)
            .output()?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("limactl create failed: {}", stderr.trim());
        }
    }

    // Start VM if not running
    let info_output = limactl_command()
        .args(["list", "--format", "{{.Status}}", consts::lima_vm_name()])
        .output()?;
    let status_str = String::from_utf8_lossy(&info_output.stdout);

    if !status_str.trim().eq_ignore_ascii_case("running") {
        let output = limactl_command()
            .args(["start", consts::lima_vm_name()])
            .output()?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("limactl start failed: {}", stderr.trim());
        }
    }

    // Wait for containerd to be ready inside VM (up to 30s)
    let mut ready = false;
    for _ in 0..15 {
        let verify = limactl_command()
            .args([
                "shell",
                consts::lima_vm_name(),
                "--",
                "sudo",
                "nerdctl",
                "info",
            ])
            .output()?;
        if verify.status.success() {
            ready = true;
            break;
        }
        std::thread::sleep(std::time::Duration::from_secs(2));
    }
    if !ready {
        anyhow::bail!(
            "containerd did not become ready inside VM after 30s. \
             Try running: limactl shell {} -- sudo nerdctl info",
            consts::lima_vm_name()
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Windows / WSL2 provisioning
// ---------------------------------------------------------------------------

/// Escapes a path for safe interpolation inside PowerShell single-quoted strings.
/// PowerShell single-quoted strings only require doubling of single quotes.
#[cfg(target_os = "windows")]
fn ps_escape(path: &std::path::Path) -> String {
    path.display().to_string().replace('\'', "''")
}

/// Selects the rootfs URL and SHA256 hash for the current host architecture.
#[cfg(target_os = "windows")]
fn wsl_rootfs_for_arch() -> anyhow::Result<(&'static str, &'static str)> {
    match std::env::consts::ARCH {
        "x86_64" => Ok((
            consts::WSL_ROOTFS_URL_AMD64,
            consts::WSL_ROOTFS_SHA256_AMD64,
        )),
        "aarch64" => Ok((
            consts::WSL_ROOTFS_URL_ARM64,
            consts::WSL_ROOTFS_SHA256_ARM64,
        )),
        arch => anyhow::bail!("Unsupported architecture for WSL2 rootfs: {}", arch),
    }
}

/// Selects the nerdctl-full SHA256 hash for the current host architecture.
#[cfg(target_os = "windows")]
fn nerdctl_sha256_for_arch() -> anyhow::Result<&'static str> {
    match std::env::consts::ARCH {
        "x86_64" => Ok(consts::NERDCTL_FULL_SHA256_AMD64),
        "aarch64" => Ok(consts::NERDCTL_FULL_SHA256_ARM64),
        arch => anyhow::bail!("Unsupported architecture for nerdctl-full: {}", arch),
    }
}

/// Returns the path to a bundled resource file, if it exists.
/// Checks `SPEEDWAVE_RESOURCES_DIR` env var first (development/testing),
/// then the standard Tauri resource directory (production).
#[cfg(target_os = "windows")]
fn find_bundled_resource(relative_path: &str) -> Option<PathBuf> {
    // Check SPEEDWAVE_RESOURCES_DIR env var (development/testing)
    if let Ok(resources_dir) = std::env::var("SPEEDWAVE_RESOURCES_DIR") {
        let path = PathBuf::from(&resources_dir).join(relative_path);
        if path.exists() {
            return Some(path);
        }
    }
    // Check next to the current executable (Tauri production layout)
    if let Ok(exe) = std::env::current_exe() {
        if let Some(exe_dir) = exe.parent() {
            let path = exe_dir.join(relative_path);
            if path.exists() {
                return Some(path);
            }
        }
    }
    None
}

/// Verifies SHA256 of a file using PowerShell. Returns `true` if the hash matches.
#[cfg(target_os = "windows")]
fn verify_sha256_ps(file_path: &std::path::Path, expected_sha256: &str) -> bool {
    let escaped = ps_escape(file_path);
    let cmd = format!(
        "(Get-FileHash -Path '{}' -Algorithm SHA256).Hash.ToLower()",
        escaped
    );
    let output = crate::binary::system_command("powershell")
        .args(["-NoProfile", "-Command", &cmd])
        .output();
    match output {
        Ok(o) if o.status.success() => {
            let actual = String::from_utf8_lossy(&o.stdout).trim().to_string();
            actual == expected_sha256
        }
        _ => false,
    }
}

/// Runs the Windows VM provisioning sequence: WSL availability + auto-install,
/// `.wslconfig` VPN-compat keys, distro import/verify, nerdctl-full install.
#[cfg(target_os = "windows")]
pub fn init_vm_windows() -> anyhow::Result<()> {
    use crate::runtime::decode_wsl_output;

    // OS prerequisite check (SSOT: os_prereqs module)
    let violations = crate::os_prereqs::check_os_prereqs();
    if !violations.is_empty() {
        // WSL not available — attempt auto-install (always bails: restart or failure)
        attempt_wsl_install()?;
    }

    // Ensure %USERPROFILE%\.wslconfig enables WSL2 mirrored networking before
    // any distro starts — this is what lets containers see the host's
    // VPN tunnel. Logs but does not fail setup on error: an older Windows
    // build without mirrored-mode support still gets a working (if
    // VPN-incompatible) install.
    if let Err(e) = ensure_wslconfig_vpn_compat() {
        log::warn!("ensure_wslconfig_vpn_compat failed (non-fatal): {e}");
    }

    let list = crate::binary::system_command("wsl.exe")
        .args(["--list", "--quiet"])
        .output()?;
    // Decode WSL output — wsl.exe often outputs UTF-16LE on Windows
    let list_str = decode_wsl_output(&list.stdout);
    let distro_exists = list_str
        .lines()
        .any(|l| l.trim().trim_matches('\0') == consts::wsl_distro_name());

    if !distro_exists {
        import_wsl_distro()?;
    } else {
        verify_wsl_distro_origin()?;
    }

    install_nerdctl_full()?;

    Ok(())
}

/// Writes (or updates) `%USERPROFILE%\.wslconfig` so the `[wsl2]` section
/// declares `networkingMode=mirrored`, `dnsTunneling=true`, `autoProxy=true`.
/// These three keys together let WSL2 distros (including Speedwave's
/// `Speedwave` distro and its containers) reach services on the host's
/// corporate VPN without manual configuration.
///
/// Preserves all other user keys and sections — only the three load-bearing
/// keys in `[wsl2]` are added or rewritten. Missing file → fresh skeleton.
///
/// Requires Windows 11 22H2+. Older builds silently ignore the unknown keys
/// (legacy NAT mode stays active and VPN-protected services remain
/// unreachable from inside WSL2 until the user upgrades).
#[cfg(target_os = "windows")]
pub fn ensure_wslconfig_vpn_compat() -> anyhow::Result<()> {
    let home = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("cannot determine %USERPROFILE% for .wslconfig"))?;
    let path = home.join(".wslconfig");
    let existing = read_existing_wslconfig(std::fs::read_to_string(&path), &path)?;
    let updated = merge_wslconfig_vpn_keys(&existing);
    if updated != existing {
        crate::fs_perms::write_restricted_file_atomic(&path, &updated)?;
        log::info!(
            "ensure_wslconfig_vpn_compat: wrote VPN-compatible [wsl2] keys to {}",
            path.display()
        );
        // .wslconfig is read only on WSL2 boot. An existing WSL2 session
        // won't pick up the new keys until the user runs `wsl --shutdown`
        // (which restarts ALL WSL distros, not just Speedwave's). We log
        // a hint rather than triggering the shutdown automatically — it
        // would surprise users running unrelated WSL workloads.
        log::warn!(
            ".wslconfig changed — run `wsl --shutdown` from PowerShell to \
             activate mirrored-mode networking (required to reach \
             services on a corporate VPN from inside Speedwave's WSL distro)"
        );
    }
    Ok(())
}

/// Classifies a `.wslconfig` read so a non-NotFound failure (UTF-16, EACCES,
/// EBUSY) bails instead of being treated as empty — an empty merge would
/// REPLACE the user's global `[wsl2]` memory/processors/kernel for ALL distros.
/// Only `NotFound` maps to empty (fresh skeleton).
#[cfg(any(target_os = "windows", test))]
pub fn read_existing_wslconfig(
    read: std::io::Result<String>,
    path: &std::path::Path,
) -> anyhow::Result<String> {
    match read {
        Ok(content) => Ok(content),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(String::new()),
        Err(e) => Err(anyhow::anyhow!(e).context(format!(
            "cannot read {} (e.g. UTF-16 from PowerShell Out-File, locked, or no permission); \
             refusing to overwrite global [wsl2] settings — fix or delete .wslconfig and retry",
            path.display()
        ))),
    }
}

/// Pure transform: takes existing `.wslconfig` content (may be empty) and
/// returns a version with the three VPN-compat keys inserted/updated under
/// `[wsl2]`. All other sections and keys are preserved verbatim. Idempotent.
#[cfg(any(target_os = "windows", test))]
pub fn merge_wslconfig_vpn_keys(input: &str) -> String {
    const VPN_KEYS: &[(&str, &str)] = &[
        ("networkingMode", "mirrored"),
        ("dnsTunneling", "true"),
        ("autoProxy", "true"),
    ];

    // Match the dominant line ending of the input — `.wslconfig` written by
    // Notepad on Windows is CRLF; emitting bare LF for new keys would yield
    // a mixed-ending file (tolerated by WSL but cosmetically ugly).
    let nl = if input.contains("\r\n") { "\r\n" } else { "\n" };

    let mut out = String::with_capacity(input.len() + 128);
    let mut current_section: Option<String> = None;
    let mut wsl2_seen = false;
    let mut wsl2_key_present: std::collections::HashSet<String> = Default::default();
    let mut pending_inject: Vec<String> = Vec::new();

    let push_missing_keys = |present: &std::collections::HashSet<String>,
                             pending: &mut Vec<String>| {
        for (k, v) in VPN_KEYS {
            if !present.contains(&k.to_ascii_lowercase()) {
                pending.push(format!("{k}={v}{nl}"));
            }
        }
    };

    for line in input.split_inclusive('\n') {
        let trimmed = line.trim();
        if let Some(stripped) = trimmed.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            if current_section.as_deref() == Some("wsl2") {
                push_missing_keys(&wsl2_key_present, &mut pending_inject);
                for inj in pending_inject.drain(..) {
                    out.push_str(&inj);
                }
            }
            current_section = Some(stripped.trim().to_ascii_lowercase());
            if current_section.as_deref() == Some("wsl2") {
                wsl2_seen = true;
            }
            out.push_str(line);
            continue;
        }
        if current_section.as_deref() == Some("wsl2") {
            if let Some(eq) = trimmed.find('=') {
                let key = trimmed[..eq].trim().to_ascii_lowercase();
                if let Some((_, desired_val)) =
                    VPN_KEYS.iter().find(|(k, _)| k.eq_ignore_ascii_case(&key))
                {
                    let original_key = trimmed[..eq].trim_end();
                    out.push_str(&format!("{original_key}={desired_val}{nl}"));
                    wsl2_key_present.insert(key);
                    continue;
                }
                wsl2_key_present.insert(key);
            }
        }
        out.push_str(line);
    }

    if current_section.as_deref() == Some("wsl2") {
        push_missing_keys(&wsl2_key_present, &mut pending_inject);
        if !out.ends_with('\n') && !pending_inject.is_empty() {
            out.push_str(nl);
        }
        for inj in pending_inject {
            out.push_str(&inj);
        }
    } else if !wsl2_seen {
        if !out.is_empty() && !out.ends_with('\n') {
            out.push_str(nl);
        }
        if !out.is_empty() {
            out.push_str(nl);
        }
        out.push_str(&format!("[wsl2]{nl}"));
        for (k, v) in VPN_KEYS {
            out.push_str(&format!("{k}={v}{nl}"));
        }
    }

    out
}

/// Verifies that an existing WSL2 distro named [`consts::wsl_distro_name`] was
/// created by Speedwave, not pre-registered by an attacker.
///
/// WSL stores the virtual disk at the install directory passed to `wsl --import`.
/// Speedwave always imports into `~/.speedwave/wsl/Speedwave/`, so a legitimate
/// distro will have `ext4.vhdx` at that path. If the file is missing the distro
/// was registered from somewhere else — bail with a clear security error.
#[cfg(target_os = "windows")]
fn verify_wsl_distro_origin() -> anyhow::Result<()> {
    verify_wsl_distro_origin_in(consts::data_dir())
}

/// Data-dir-explicit variant of [`verify_wsl_distro_origin`].
#[cfg(any(target_os = "windows", test))]
pub fn verify_wsl_distro_origin_in(data_dir: &std::path::Path) -> anyhow::Result<()> {
    let expected_vhdx = expected_wsl_vhdx_path_in(data_dir);
    if !expected_vhdx.exists() {
        anyhow::bail!(
            "Security error: a WSL2 distribution named '{}' already exists but was \
             NOT created by Speedwave (expected disk image at {} is missing). \
             This may indicate a malicious distro was pre-registered. \
             Please run 'wsl --unregister {}' to remove it, then retry Speedwave setup.",
            consts::wsl_distro_name(),
            expected_vhdx.display(),
            consts::wsl_distro_name(),
        );
    }
    Ok(())
}

/// Data-dir-explicit variant returning the expected WSL2 virtual-disk path:
/// `<data_dir>/wsl/<distro>/ext4.vhdx`.
#[cfg(any(target_os = "windows", test))]
pub fn expected_wsl_vhdx_path_in(data_dir: &std::path::Path) -> PathBuf {
    data_dir
        .join("wsl")
        .join(consts::wsl_distro_name())
        .join("ext4.vhdx")
}

/// Attempts to install WSL2 via elevated PowerShell. Always bails: either
/// with a restart prompt (success) or an installation failure message.
/// Detection is handled by `os_prereqs::check_os_prereqs()` — this function
/// only performs the install action.
#[cfg(target_os = "windows")]
fn attempt_wsl_install() -> anyhow::Result<()> {
    let status = crate::binary::system_command("powershell")
        .args([
            "-Command",
            "Start-Process wsl.exe -ArgumentList '--install','--no-distribution' -Verb RunAs -Wait",
        ])
        .status()?;
    if !status.success() {
        anyhow::bail!(
            "WSL2 installation failed or was cancelled.\n\
             {}",
            consts::WSL_NOT_AVAILABLE_MSG
        );
    }
    anyhow::bail!(
        "WSL2 has been installed. Please restart your computer and run Speedwave setup again."
    );
}

/// Downloads the Ubuntu rootfs (with SHA256 verification) and imports it as a
/// dedicated WSL2 distribution. Checks for a bundled rootfs first (offline
/// install), then falls back to cached download, then fresh download.
#[cfg(target_os = "windows")]
fn import_wsl_distro() -> anyhow::Result<()> {
    use crate::runtime::decode_wsl_output;

    let data_dir = consts::data_dir();
    let wsl_dir = data_dir.join("wsl");
    let rootfs_path = wsl_dir.join("ubuntu-rootfs.tar.gz");
    std::fs::create_dir_all(&wsl_dir)?;

    let (rootfs_url, expected_sha256) = wsl_rootfs_for_arch()?;

    // Try bundled rootfs first (offline install from NSIS bundle)
    let mut have_valid_rootfs = false;

    if let Some(bundled) = find_bundled_resource("wsl/ubuntu-rootfs.tar.gz") {
        if verify_sha256_ps(&bundled, expected_sha256) {
            // Copy bundled rootfs to the cache location for wsl --import
            std::fs::copy(&bundled, &rootfs_path)?;
            have_valid_rootfs = true;
        }
    }

    // Check cached download
    if !have_valid_rootfs && rootfs_path.exists() {
        if verify_sha256_ps(&rootfs_path, expected_sha256) {
            have_valid_rootfs = true;
        } else {
            let _ = std::fs::remove_file(&rootfs_path);
        }
    }

    // Fall back to download
    if !have_valid_rootfs {
        let escaped_rootfs = ps_escape(&rootfs_path);
        let download_and_verify = format!(
            "$ProgressPreference = 'SilentlyContinue'; \
             Invoke-WebRequest -Uri '{}' -OutFile '{}'; \
             $hash = (Get-FileHash -Path '{}' -Algorithm SHA256).Hash.ToLower(); \
             if ($hash -ne '{}') {{ \
                 Remove-Item '{}' -Force; \
                 Write-Error \"SHA256 mismatch: expected {}, got $hash\"; \
                 exit 1 \
             }}",
            rootfs_url,
            escaped_rootfs,
            escaped_rootfs,
            expected_sha256,
            escaped_rootfs,
            expected_sha256
        );
        let download = crate::binary::system_command("powershell")
            .args(["-NoProfile", "-Command", &download_and_verify])
            .status()?;
        if !download.success() {
            anyhow::bail!(
                "Failed to download or verify Ubuntu rootfs for WSL2 \
                 (expected SHA256: {})",
                expected_sha256
            );
        }
    }

    let install_dir = wsl_dir.join(consts::wsl_distro_name());
    std::fs::create_dir_all(&install_dir)?;
    let status = crate::binary::system_command("wsl.exe")
        .args([
            "--import",
            consts::wsl_distro_name(),
            &install_dir.to_string_lossy(),
            &rootfs_path.to_string_lossy(),
        ])
        .status()?;
    if !status.success() {
        // Check if the distro was already registered (import failed because it exists)
        let recheck = crate::binary::system_command("wsl.exe")
            .args(["--list", "--quiet"])
            .output()?;
        let recheck_str = decode_wsl_output(&recheck.stdout);
        if recheck_str
            .lines()
            .any(|l| l.trim().trim_matches('\0') == consts::wsl_distro_name())
        {
            // Distro exists but we didn't create it — verify it's ours before
            // trusting it. An attacker could pre-register a malicious distro
            // with the same name to hijack the container runtime.
            verify_wsl_distro_origin()?;
            log::warn!(
                "WSL2 import failed but distro '{}' already exists and is verified — continuing",
                consts::wsl_distro_name()
            );
        } else {
            anyhow::bail!("Failed to import Speedwave WSL2 distribution");
        }
    }

    // Import path: safe to terminate (no containers yet); Err retried by IfIdle on next launch (ADR-052).
    use anyhow::Context as _;
    ensure_wsl_distro_metadata(TerminateOnChange::Yes)
        .context("configuring the imported WSL distro's automount failed")?;

    Ok(())
}

/// Whether `ensure_wsl_distro_metadata` may `wsl --terminate` to apply the change.
#[cfg(any(target_os = "windows", test))]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TerminateOnChange {
    /// Import path: no container runs yet, so terminating is always safe.
    Yes,
    /// Startup/post-update: terminate only when idle, else uid-1000 EACCES (ADR-052).
    IfIdle,
}

/// Pure terminate policy (testable without Windows); `has_running` only for `IfIdle`.
#[cfg(any(target_os = "windows", test))]
pub fn terminate_decision(terminate: TerminateOnChange, has_running: bool) -> bool {
    match terminate {
        TerminateOnChange::Yes => true,
        TerminateOnChange::IfIdle => !has_running,
    }
}

/// Unwraps a `read_wsl_conf` result, warning before defaulting to empty.
/// `read_wsl_conf` already maps a missing file to `Ok("")`, so any `Err` here
/// is a real spawn/IO failure (not NotFound) and must not be silent — empty
/// triggers a needless wsl.conf rewrite, but the post-write uid re-read still
/// guards correctness (ADR-052), so we degrade rather than bail.
#[cfg(any(target_os = "windows", test))]
pub fn wsl_conf_or_warn(read: anyhow::Result<String>, distro: &str, when: &str) -> String {
    match read {
        Ok(content) => content,
        Err(e) => {
            log::warn!("read_wsl_conf failed for {distro} ({when}); treating as empty: {e}");
            String::new()
        }
    }
}

/// Sets `/etc/wsl.conf` automount (`Yes` at import, `IfIdle` at startup; `Err` if the write didn't land — ADR-052).
#[cfg(target_os = "windows")]
pub fn ensure_wsl_distro_metadata(terminate: TerminateOnChange) -> anyhow::Result<()> {
    let distro = consts::wsl_distro_name();
    let opts = consts::wsl_automount_options();
    let (uid, _gid) = consts::container_uid_gid();

    let existing = wsl_conf_or_warn(read_wsl_conf(distro), distro, "initial read");
    let updated = merge_wsl_conf_automount(&existing, &opts);

    if updated == existing {
        log::debug!("ensure_wsl_distro_metadata: automount options already current in {distro}");
        return Ok(());
    }

    write_wsl_conf(distro, &updated)?;

    // Verify the change landed; a read-only wsl.conf silently fails otherwise.
    let verify = wsl_conf_or_warn(read_wsl_conf(distro), distro, "post-write verify");
    if !wsl_conf_automount_has_uid(&verify, uid) {
        anyhow::bail!(
            "wrote /etc/wsl.conf for {distro} but uid={uid} is NOT present on re-read; \
             the uid-1000 container will hit EACCES on the drvfs mount and fail to start \
             (login/onboarding broken). Check that /etc/wsl.conf is writable as root"
        );
    }

    // Probe lazily (only IfIdle, only now that a real change exists) then decide.
    let has_running =
        matches!(terminate, TerminateOnChange::IfIdle) && wsl_distro_has_running_containers(distro);
    if terminate_decision(terminate, has_running) {
        let terminated = crate::binary::system_command("wsl.exe")
            .args(["--terminate", distro])
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if terminated {
            log::info!(
                "ensure_wsl_distro_metadata: enabled metadata automount for {distro} (terminated to apply)"
            );
        } else {
            log::warn!(
                "ensure_wsl_distro_metadata: wrote metadata automount for {distro} but `wsl --terminate` failed; applies on next WSL restart"
            );
        }
    } else {
        log::info!(
            "ensure_wsl_distro_metadata: enabled metadata automount for {distro} (containers running; applies on next WSL restart)"
        );
    }
    Ok(())
}

/// Reads `/etc/wsl.conf` as root; `Ok("")` if absent, `Err` only on spawn failure.
#[cfg(target_os = "windows")]
fn read_wsl_conf(distro: &str) -> anyhow::Result<String> {
    let out = crate::binary::system_command("wsl.exe")
        .args(["-d", distro, "-u", "root", "--", "cat", "/etc/wsl.conf"])
        .output()?;
    // `cat` on a missing file exits non-zero — treat that as empty, not an error.
    Ok(if out.status.success() {
        String::from_utf8_lossy(&out.stdout).into_owned()
    } else {
        String::new()
    })
}

/// Writes `content` to `/etc/wsl.conf` via `tee` (stdin), as root in the distro.
#[cfg(target_os = "windows")]
fn write_wsl_conf(distro: &str, content: &str) -> anyhow::Result<()> {
    use std::io::Write;
    use std::process::Stdio;
    let mut child = crate::binary::system_command("wsl.exe")
        .args(["-d", distro, "-u", "root", "--", "tee", "/etc/wsl.conf"])
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .spawn()?;
    child
        .stdin
        .take()
        .ok_or_else(|| anyhow::anyhow!("failed to open stdin for tee /etc/wsl.conf"))?
        .write_all(content.as_bytes())?;
    let status = child.wait()?;
    if !status.success() {
        anyhow::bail!("`tee /etc/wsl.conf` exited with {status} in {distro}");
    }
    Ok(())
}

/// `true` if any container runs in the distro (containerd-down ⇒ idle; spawn failure ⇒ fail-safe busy).
#[cfg(target_os = "windows")]
fn wsl_distro_has_running_containers(distro: &str) -> bool {
    // Session is already `-u root`, so no `sudo` (not always in root's PATH).
    let out = crate::binary::system_command("wsl.exe")
        .args(["-d", distro, "-u", "root", "--", "nerdctl", "ps", "-q"])
        .output();
    match out {
        Ok(o) => running_containers_from_probe(
            o.status.success(),
            &String::from_utf8_lossy(&o.stdout),
            &String::from_utf8_lossy(&o.stderr),
        ),
        Err(e) => {
            log::warn!(
                "wsl_distro_has_running_containers: spawn failed for {distro}; assuming busy: {e}"
            );
            true
        }
    }
}

/// Interprets a `nerdctl ps -q` probe: running, idle, or (on containerd-down stderr) idle; else fail-safe busy.
#[cfg(any(target_os = "windows", test))]
pub fn running_containers_from_probe(success: bool, stdout: &str, stderr: &str) -> bool {
    if success {
        return !stdout.trim().is_empty();
    }
    let lower = stderr.to_ascii_lowercase();
    let daemon_down = lower.contains("connection refused")
        || lower.contains("cannot connect")
        || lower.contains("failed to connect")
        || lower.contains("no such file or directory") // containerd.sock absent
        || lower.contains("is the containerd daemon running");
    if daemon_down {
        false // daemon not up ⇒ nothing running ⇒ idle
    } else {
        log::warn!(
            "wsl_distro_has_running_containers: nerdctl ps failed (assuming busy): {stderr}"
        );
        true
    }
}

/// `true` if `[automount].options` contains `uid={uid}` as a full token (anchored, not substring).
#[cfg(any(target_os = "windows", test))]
pub fn wsl_conf_automount_has_uid(content: &str, uid: u32) -> bool {
    automount_options_line(content).is_some_and(|opts| options_has_uid(opts, uid))
}

/// Value of the `options =` key in the first `[automount]` section (comments ignored); `None` if absent.
#[cfg(any(target_os = "windows", test))]
pub fn automount_options_line(content: &str) -> Option<&str> {
    let mut in_automount = false;
    for raw in content.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(sec) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            in_automount = sec.trim().eq_ignore_ascii_case("automount");
            continue;
        }
        if in_automount {
            if let Some((k, v)) = line.split_once('=') {
                if k.trim().eq_ignore_ascii_case("options") {
                    return Some(v.trim().trim_matches('"'));
                }
            }
        }
    }
    None
}

/// `true` if a comma-separated options string contains `uid={uid}` as a whole token.
#[cfg(any(target_os = "windows", test))]
pub fn options_has_uid(options: &str, uid: u32) -> bool {
    let needle = format!("uid={uid}");
    options.split(',').any(|tok| tok.trim() == needle)
}

/// Sets `[automount].options` to `opts`, replacing only that key; all other keys/sections preserved. CRLF-aware, idempotent.
#[cfg(any(target_os = "windows", test))]
pub fn merge_wsl_conf_automount(input: &str, opts: &str) -> String {
    let nl = if input.contains("\r\n") { "\r\n" } else { "\n" };
    let mut out = String::with_capacity(input.len() + 64);
    // `Some(true)` = first [automount] (keep its keys); `Some(false)` = a
    // duplicate [automount] (drop its whole body); `None` = some other section.
    let mut in_automount: Option<bool> = None;
    let mut automount_seen = false;
    let mut options_written = false;

    for line in input.split_inclusive('\n') {
        let trimmed = line.trim();
        if let Some(sec) = trimmed
            .strip_prefix('[')
            .and_then(|s| s.strip_suffix(']'))
            .map(|s| s.trim().to_ascii_lowercase())
        {
            if sec == "automount" {
                if automount_seen {
                    in_automount = Some(false); // duplicate — drop header + body
                    continue;
                }
                automount_seen = true;
                in_automount = Some(true);
                out.push_str(line);
                // Emit our options line right after the first header.
                let line_nl = if line.ends_with('\n') { nl } else { "" };
                out.push_str(&format!("options = \"{opts}\"{line_nl}"));
                options_written = true;
                continue;
            }
            in_automount = None;
            out.push_str(line);
            continue;
        }
        match in_automount {
            // First [automount] body: drop only the old options line, keep the rest.
            Some(true) => {
                let is_options = trimmed
                    .split_once('=')
                    .is_some_and(|(k, _)| k.trim().eq_ignore_ascii_case("options"));
                if !is_options {
                    out.push_str(line);
                }
            }
            // Duplicate [automount] body — drop entirely.
            Some(false) => {}
            None => out.push_str(line),
        }
    }

    if !options_written {
        // No [automount] section existed — append a fresh one.
        if !out.is_empty() && !out.ends_with('\n') {
            out.push_str(nl);
        }
        out.push_str(&format!("[automount]{nl}options = \"{opts}\"{nl}"));
    }
    out
}

/// Makes the project's `claude-home` tree owned by the container user so the
/// uid-1000 entrypoint can write `/home/speedwave` (mkdir/ln under `set -e`).
///
/// This is the **load-bearing** half of the Windows mount-ownership fix. The
/// WSL drvfs `/mnt/c` mount is owned by uid 0 (the imported distro has no
/// default user, and WSL's prepended default-user uid beats the `uid=` automount
/// option), so a uid-1000 mkdir under a root-owned parent gets EACCES and the
/// container exits(1) ("cannot exec in a stopped state"). With `metadata` on,
/// `chown` writes per-file ownership that drvfs honors for access.
///
/// MUST run **after** `compose_up_recreate`: `compose up` auto-creates the
/// `/home/speedwave/.claude` bind mount-point (for the read-only ide-bridge
/// mount) as ROOT, so a chown done *before* compose is silently undone by the
/// start. Chowning after the mount-points exist, then letting
/// `ensure_exec_healthy`'s recovery recreate re-run the entrypoint against the
/// now-1000-owned tree, is what actually fixes it. Verified on the live distro.
///
/// uid/gid come from the [`consts::container_uid_gid`] SSOT (same value as the
/// compose `user:` field). Idempotent and cheap. Fail-open: a chown failure
/// only logs.
#[cfg(target_os = "windows")]
pub fn ensure_claude_home_owner(project: &str) -> anyhow::Result<()> {
    let distro = consts::wsl_distro_name();
    let (uid, gid) = consts::container_uid_gid();
    let host_path = crate::claude_home::claude_home_dir(consts::data_dir(), project);
    let wsl_path = crate::engine_path::to_engine_path(&host_path)?;
    let uidgid = format!("{uid}:{gid}");
    // Pass the path as its OWN argv token to each tool (mkdir/chown/chmod) — no
    // `sh -c` wrapper, no shell variable. `wsl.exe` re-parses a `sh -c "<script>"`
    // string and drops the `$d` variable, so inlining via argv (the way compose
    // passes mount paths) is the reliable form. Three small invocations.
    let run = |args: &[&str]| {
        crate::binary::system_command("wsl.exe")
            .args(["-d", distro, "-u", "root", "--"])
            .args(args)
            .output()
    };
    let steps: [(&str, Vec<&str>); 3] = [
        ("mkdir", vec!["mkdir", "-p", &wsl_path]),
        ("chown", vec!["chown", "-R", &uidgid, &wsl_path]),
        ("chmod", vec!["chmod", "-R", "u+rwX", &wsl_path]),
    ];
    let mut all_ok = true;
    for (name, args) in &steps {
        match run(args) {
            Ok(o) if o.status.success() => {}
            Ok(o) => {
                all_ok = false;
                log::warn!(
                    "ensure_claude_home_owner: {name} failed (non-fatal): {}",
                    String::from_utf8_lossy(&o.stderr).trim()
                );
            }
            Err(e) => {
                all_ok = false;
                log::warn!("ensure_claude_home_owner: {name} spawn failed (non-fatal): {e}");
            }
        }
    }
    if all_ok {
        log::info!("ensure_claude_home_owner: chowned {wsl_path} to {uidgid}");
    } else {
        log::warn!(
            "ensure_claude_home_owner: {wsl_path} NOT fully chowned to {uidgid} (see warnings)"
        );
    }
    Ok(())
}

/// `true` if a `nerdctl --version` line reports exactly `NERDCTL_FULL_VERSION`.
/// Output shape is `nerdctl version 2.2.2` (tokens after "version").
#[cfg(any(target_os = "windows", test))]
fn nerdctl_version_matches_pin(version_line: &str) -> bool {
    version_line
        .split_whitespace()
        .any(|tok| tok == consts::NERDCTL_FULL_VERSION)
}

/// Installs nerdctl-full (containerd + nerdctl + CNI + BuildKit) inside the
/// Speedwave WSL2 distribution if the pinned version is not already present.
/// Checks for a bundled tarball first (offline install), falling back to
/// download if not found. Re-installs when the in-distro version differs from
/// `NERDCTL_FULL_VERSION` so an upgrade actually upgrades the guest (ADR-071).
/// `true` when a failed version probe means nerdctl is genuinely absent
/// (vs a transient wsl.exe transport error that must not trigger reinstall).
#[cfg_attr(not(target_os = "windows"), allow(dead_code))]
fn probe_indicates_absent(code: Option<i32>, stderr: &str) -> bool {
    code == Some(127) || stderr.contains("not found") || stderr.contains("No such file")
}

#[cfg(target_os = "windows")]
fn install_nerdctl_full() -> anyhow::Result<()> {
    let nerdctl_check = crate::binary::system_command("wsl.exe")
        .args([
            "-d",
            consts::wsl_distro_name(),
            "--",
            "nerdctl",
            "--version",
        ])
        .output()?;
    if nerdctl_check.status.success() {
        let version_line = String::from_utf8_lossy(&nerdctl_check.stdout);
        if nerdctl_version_matches_pin(&version_line) {
            return Ok(());
        }
        log::info!(
            "in-distro nerdctl is not the pinned {} (got: {}); reinstalling",
            consts::NERDCTL_FULL_VERSION,
            version_line.trim()
        );
    } else {
        // Probe failed: distinguish "nerdctl genuinely absent" (exit 127 /
        // not-found) from a transient wsl.exe transport error — a transient
        // failure must NOT trigger a daemon-stopping reinstall.
        let stderr = String::from_utf8_lossy(&nerdctl_check.stderr);
        let absent = probe_indicates_absent(nerdctl_check.status.code(), &stderr);
        if !absent {
            anyhow::bail!(
                "nerdctl version probe failed transiently (status {:?}: {}); skipping reinstall",
                nerdctl_check.status.code(),
                stderr.trim()
            );
        }
        log::info!(
            "in-distro nerdctl absent; installing {}",
            consts::NERDCTL_FULL_VERSION
        );
    }

    // Try bundled nerdctl-full tarball first (offline install from NSIS bundle).
    // If valid, convert its path to WSL and use `cp` instead of `curl` inside the distro.
    let expected_sha256 = nerdctl_sha256_for_arch()?;
    let mut bundled_wsl_path: Option<String> = None;

    if let Some(bundled) = find_bundled_resource("wsl/nerdctl-full.tar.gz") {
        if verify_sha256_ps(&bundled, expected_sha256) {
            // Translate the bundled tarball's host path to its WSL path via the
            // SSOT (engine_path::to_engine_path) — one path-translation mechanism,
            // not a second `wslpath` round-trip. On translation failure fall
            // through to the curl download branch rather than abort the install.
            match crate::engine_path::to_engine_path(&bundled) {
                Ok(wsl) => bundled_wsl_path = Some(wsl),
                Err(e) => log::warn!(
                    "could not translate bundled nerdctl path to WSL ({e}); will download instead"
                ),
            }
        }
    }

    // Build install script: use bundled file if available, otherwise download
    let source_commands = if let Some(ref wsl_path) = bundled_wsl_path {
        let escaped = wsl_path.replace('\'', "'\\''");
        format!(
            "mkdir -p /tmp/nerdctl-install\ncp '{}' \"/tmp/nerdctl-install/${{TARBALL}}\"",
            escaped
        )
    } else {
        "mkdir -p /tmp/nerdctl-install\ncurl -fsSL \"$URL\" -o \"/tmp/nerdctl-install/${TARBALL}\""
            .to_string()
    };

    let install_script = format!(
        r#"set -e
ARCH=$(uname -m)
case "$ARCH" in
  x86_64) ARCH="amd64"; EXPECTED="{sha256_amd64}" ;;
  aarch64) ARCH="arm64"; EXPECTED="{sha256_arm64}" ;;
  *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac
VERSION="{version}"
TARBALL="nerdctl-full-${{VERSION}}-linux-${{ARCH}}.tar.gz"
URL="https://github.com/containerd/nerdctl/releases/download/v${{VERSION}}/${{TARBALL}}"
{source_commands}
ACTUAL=$(sha256sum "/tmp/nerdctl-install/${{TARBALL}}" | awk '{{print $1}}')
if [ "$EXPECTED" != "$ACTUAL" ]; then
  echo "SHA256 MISMATCH: expected $EXPECTED, got $ACTUAL"
  rm -rf /tmp/nerdctl-install
  exit 1
fi
# Pre-existing installs carry a unit WITHOUT KillMode=process — stopping it
# would cgroup-kill every running container. Patch via override BEFORE stop
# so user containers survive the upgrade (shims keep them; the new daemon
# re-attaches). No-op on fresh install.
if [ -f /etc/systemd/system/containerd.service ]; then
  mkdir -p /etc/systemd/system/containerd.service.d
  printf '[Service]\nKillMode=process\nDelegate=yes\n' > /etc/systemd/system/containerd.service.d/10-speedwave-killmode.conf
  command -v systemctl >/dev/null 2>&1 && systemctl daemon-reload 2>/dev/null || true
fi
# Stop daemons before unpacking — tar over live binaries fails ETXTBSY on a
# reinstall (ADR-071). No is-system-running gate (skips on `degraded`); pkill
# covers the `$exec &` non-systemd fallback. No-op on fresh install.
command -v systemctl >/dev/null 2>&1 && systemctl stop buildkit containerd 2>/dev/null || true
pkill -x buildkitd 2>/dev/null || true
pkill -x containerd 2>/dev/null || true
tar -C /usr/local --unlink-first --recursive-unlink -xzf "/tmp/nerdctl-install/${{TARBALL}}"
rm -rf /tmp/nerdctl-install
# Install iptables — required by CNI bridge plugin for container networking.
# nerdctl-full bundles CNI plugins but iptables is a system dependency.
if ! command -v iptables >/dev/null 2>&1; then
  apt-get update -qq && apt-get install -y -qq iptables >/dev/null
fi
# install_service NAME EXEC AFTER REQUIRES CHECK_CMD [CHECK_ARGS...]
# Installs a systemd service unit file, starts it, and waits up to 30s for readiness.
install_service() {{
  local name="$1" exec="$2" after="$3" requires="$4"
  shift 4
  local check_cmd="$@"
  mkdir -p /etc/systemd/system
  cat > "/etc/systemd/system/${{name}}.service" <<UNIT
[Unit]
Description=${{name}} daemon
${{after:+After=$after}}
${{requires:+Requires=$requires}}
[Service]
ExecStart=$exec
Restart=always
KillMode=process
Delegate=yes
[Install]
WantedBy=multi-user.target
UNIT
  # Try systemd unconditionally — gating on overall system state skips unit
  # installation forever on the common WSL2 `degraded` state.
  if command -v systemctl >/dev/null 2>&1 \
     && systemctl daemon-reload >/dev/null 2>&1 \
     && systemctl enable --now "$name" >/dev/null 2>&1; then
    :
  else
    # Detach from inherited stdio — daemons holding the caller's pipes would
    # block the host's wait_with_output() forever (post-upgrade hang).
    setsid $exec </dev/null >>"/var/log/${{name}}.log" 2>&1 &
  fi
  for i in $(seq 1 15); do
    if $check_cmd >/dev/null 2>&1; then return 0; fi
    sleep 2
  done
  echo "$name did not become ready after 30s" >&2
  exit 1
}}
# Configure containerd as a system service so it starts on every WSL session
install_service containerd /usr/local/bin/containerd network.target "" nerdctl info
# Start buildkitd — required for `nerdctl build` (image building).
# On WSL2 we run as root (not rootless), so install as a systemd system service.
install_service buildkit "/usr/local/bin/buildkitd --oci-worker=false --containerd-worker=true" containerd.service containerd.service buildctl debug workers
"#,
        version = consts::NERDCTL_FULL_VERSION,
        sha256_amd64 = consts::NERDCTL_FULL_SHA256_AMD64,
        sha256_arm64 = consts::NERDCTL_FULL_SHA256_ARM64,
        source_commands = source_commands
    );
    // Write the install script inside WSL via stdin to avoid argument
    // length/escaping issues with wsl.exe -- bash -c "...".
    // Pipe the script through stdin: echo "$script" | wsl bash -s
    let install = crate::binary::system_command("wsl.exe")
        .args(["-d", consts::wsl_distro_name(), "--", "bash", "-s"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()?;
    use std::io::Write;
    let mut child = install;
    if let Some(mut stdin) = child.stdin.take() {
        stdin.write_all(install_script.as_bytes())?;
        // Drop stdin to close the pipe and let bash finish
    }
    let output = child.wait_with_output()?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        log::error!(
            "nerdctl-full install failed (exit {}): stdout={}, stderr={}",
            output.status,
            stdout.trim(),
            stderr.trim()
        );
        anyhow::bail!(
            "Failed to install nerdctl-full inside {} WSL2 distribution: {}",
            consts::wsl_distro_name(),
            stderr.trim()
        );
    }

    Ok(())
}

/// Reinstalls the in-distro nerdctl if it drifted from the pin (ADR-071).
/// Warn-only, once-per-process: a failed reinstall must not churn on retry.
#[cfg(target_os = "windows")]
pub fn ensure_nerdctl_version() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        if let Err(e) = install_nerdctl_full() {
            log::warn!("could not align in-distro nerdctl to the pin: {e}");
        }
    });
}

/// No-op off Windows: macOS gets nerdctl from Lima (`.lima-version`).
#[cfg(not(target_os = "windows"))]
pub fn ensure_nerdctl_version() {}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    // ── nerdctl version-pin matching ────────────────────────────────────────

    #[test]
    fn nerdctl_version_matches_exact_pin() {
        let line = format!("nerdctl version {}", consts::NERDCTL_FULL_VERSION);
        assert!(nerdctl_version_matches_pin(&line));
        assert!(nerdctl_version_matches_pin(&format!("{line}\n")));
    }

    #[test]
    fn nerdctl_version_rejects_other_version() {
        // A non-exact version (older, or longer like 2.2.20) must NOT match.
        assert!(!nerdctl_version_matches_pin("nerdctl version 2.1.2"));
        assert!(!nerdctl_version_matches_pin("nerdctl version 2.2.20"));
        assert!(!nerdctl_version_matches_pin(""));
        assert!(!nerdctl_version_matches_pin("command not found"));
    }

    /// Structural: the install script must stop the daemons BEFORE `tar`
    /// unpacks into /usr/local — on a reinstall the live containerd/buildkitd
    /// binaries would otherwise be overwritten while executing (ETXTBSY),
    /// failing the upgrade. The stop must precede the unpack, must NOT gate on
    /// `is-system-running` (false in `degraded` state), and must `pkill` the
    /// bare-background daemons (install_service's non-systemd `$exec &` path).
    #[test]
    fn nerdctl_install_stops_services_before_tar() {
        let src = include_str!("provision.rs");
        let stop_pos = src
            .find("systemctl stop buildkit containerd")
            .expect("install script must stop daemons before unpacking");
        let killmode_pos = src
            .find("10-speedwave-killmode.conf")
            .expect("old-unit KillMode override must exist");
        assert!(
            killmode_pos < stop_pos,
            "KillMode override must be written BEFORE the stop, or the first \
             migration cgroup-kills every running container"
        );
        let pkill_pos = src
            .find("pkill -x containerd")
            .expect("install script must pkill bare-background daemons");
        let tar_pos = src
            .find("tar -C /usr/local --unlink-first --recursive-unlink -xzf")
            .expect("install script must untar with --unlink-first (ETXTBSY on busy shims)");
        assert!(
            stop_pos < tar_pos && pkill_pos < tar_pos,
            "daemon stop+pkill (at {stop_pos}/{pkill_pos}) must precede tar (at {tar_pos})"
        );
        // The stop must not be gated by is-system-running (skips on `degraded`).
        let stop_line_end = src[stop_pos..]
            .find('\n')
            .map(|i| stop_pos + i)
            .unwrap_or(src.len());
        let stop_line_start = src[..stop_pos].rfind('\n').map(|i| i + 1).unwrap_or(0);
        let stop_line = &src[stop_line_start..stop_line_end];
        assert!(
            !stop_line.contains("is-system-running"),
            "the daemon-stop line must not gate on is-system-running: {stop_line}"
        );
    }

    #[test]
    fn probe_absent_on_exit_127_or_not_found() {
        assert!(probe_indicates_absent(Some(127), ""));
        assert!(probe_indicates_absent(Some(1), "nerdctl: not found"));
        assert!(probe_indicates_absent(Some(2), "No such file or directory"));
    }

    #[test]
    fn probe_transient_errors_do_not_mean_absent() {
        // wsl.exe transport failures: no daemon-stopping reinstall.
        assert!(!probe_indicates_absent(
            Some(1),
            "The system cannot find the distro"
        ));
        assert!(!probe_indicates_absent(None, "killed by signal"));
        assert!(!probe_indicates_absent(Some(-1), ""));
    }

    #[test]
    fn version_probe_failure_discriminates_absent_from_transient() {
        let source = include_str!("provision.rs");
        let anchor = source
            .find("probe failed transiently")
            .expect("transient-probe bail must exist");
        let window_start = anchor.saturating_sub(900);
        let window = &source[window_start..anchor];
        assert!(
            window.contains("probe_indicates_absent"),
            "the bail path must gate on the pure discriminator"
        );
    }

    #[test]
    fn nerdctl_install_fallback_detaches_daemon_stdio() {
        let src = include_str!("provision.rs");
        let fallback = src
            .find("setsid $exec </dev/null >>")
            .expect("non-systemd fallback must detach stdio (inherited pipes hang the host)");
        let fi = src[fallback..].find("fi").map(|i| fallback + i).unwrap();
        assert!(
            src[fallback..fi].contains("2>&1 &"),
            "fallback must redirect stderr and background the daemon"
        );
        // A bare `$exec &` (no redirection) must not exist anywhere.
        assert!(
            !src.contains("\n    $exec &\n"),
            "bare $exec & inherits the Rust pipes and deadlocks wait_with_output"
        );
    }

    #[test]
    fn install_service_does_not_gate_systemd_on_is_system_running() {
        let src = include_str!("provision.rs");
        let unit = src.find("ExecStart=$exec").expect("unit heredoc");
        let window = &src[unit..unit + 1200];
        assert!(
            window.contains("systemctl enable --now") && !window.contains("is-system-running"),
            "systemd path must be attempted unconditionally (degraded state is common on WSL2)"
        );
    }

    #[test]
    fn nerdctl_service_unit_has_killmode_process() {
        let src = include_str!("provision.rs");
        let unit = src
            .find("ExecStart=$exec")
            .expect("install_service unit heredoc must exist");
        let tail = &src[unit..unit + 200];
        assert!(
            tail.contains("KillMode=process") && tail.contains("Delegate=yes"),
            "containerd unit needs KillMode=process + Delegate=yes or a stop cgroup-kills every container"
        );
    }

    // ── Lima VM config migration tests ──────────────────────────────────────

    #[test]
    fn lima_vm_config_detects_old_8gib() {
        let config = "vmType: vz\ncpus: 4\nmemory: \"8GiB\"\ndisk: \"30GiB\"\n";
        assert!(lima_vm_config_needs_update_with(config, 12, 4));
    }

    /// Test helper — appends the VPN-aware provision sentinel so fixtures
    /// model a fully-migrated config; tests focused on memory comparison
    /// would otherwise also trigger the provision-absent migration branch.
    fn with_provision_sentinel(base: &str) -> String {
        format!(
            "{base}provision:\n  - mode: boot\n    script: |\n      cat > /etc/netplan/99-speedwave-prefer-vznat.yaml <<'YAML'\n"
        )
    }

    #[test]
    fn lima_vm_config_current_no_update() {
        let config =
            with_provision_sentinel("vmType: vz\ncpus: 4\nmemory: \"12GiB\"\ndisk: \"30GiB\"\n");
        assert!(!lima_vm_config_needs_update_with(&config, 12, 4));
    }

    #[test]
    fn lima_vm_config_higher_memory_triggers_downgrade() {
        // After the VM formula was reduced, existing VMs with more RAM than
        // desired must be migrated down to reclaim host memory.
        let config = "vmType: vz\ncpus: 4\nmemory: \"16GiB\"\ndisk: \"30GiB\"\n";
        assert!(lima_vm_config_needs_update_with(config, 12, 4));
    }

    #[test]
    fn lima_vm_config_lower_memory_triggers_update() {
        let config = "vmType: vz\ncpus: 4\nmemory: \"4GiB\"\ndisk: \"30GiB\"\n";
        assert!(lima_vm_config_needs_update_with(config, 12, 4));
    }

    /// Generated lima.yaml must include a provision script that demotes lima0
    /// (usernet) below eth0 (vzNAT) so traffic flows through vzNAT where the
    /// macOS host's VPN routing applies. Without this, corporate-VPN-protected
    /// services are unreachable from inside the VM. See lima-vm/lima#2984.
    #[test]
    fn lima_config_includes_vpn_aware_provision_script() {
        let yaml = lima_config();
        assert!(
            yaml.contains("provision:"),
            "lima.yaml must declare a provision section"
        );
        // `mode: boot` maps to cloud-init's bootcmd — re-runs on every VM
        // start. `mode: system` would only run on first boot, which would
        // skip the fix for users upgrading an existing VM.
        assert!(
            yaml.contains("mode: boot"),
            "provision must use `mode: boot` so the fix re-applies on \
             every VM restart, including post-upgrade existing VMs"
        );
        // The drop-in netplan file declaratively overrides DHCP route metrics
        // — eth0 to 100 (preferred), lima0 to 300 with `use-routes: false`.
        assert!(
            yaml.contains("99-speedwave-prefer-vznat.yaml"),
            "provision must drop in a higher-priority netplan file that \
             demotes lima0 and promotes eth0 (vzNAT) as default egress"
        );
        assert!(
            yaml.contains("use-routes: false"),
            "lima0 must have `use-routes: false` so DHCP cannot re-install \
             a default route through it after renew"
        );
        assert!(
            yaml.contains("route-metric: 100"),
            "eth0 must be promoted to route-metric 100 (preferred)"
        );
        // Sanity: provision must `netplan apply` so changes take effect
        // without requiring a reboot.
        assert!(
            yaml.contains("netplan apply"),
            "provision must apply the new netplan config immediately"
        );
    }

    /// Negative guard: must not contain the obsolete `lima0`-only routing
    /// that breaks VPN. The fix above is the only sanctioned config.
    #[test]
    fn lima_config_does_not_silently_drop_provision_section() {
        let yaml = lima_config();
        // Both vzNAT and the provision script are load-bearing; removing
        // either re-introduces the VPN-incompatibility regression.
        assert!(yaml.contains("vzNAT: true"));
        assert!(yaml.contains("provision:"));
    }

    #[test]
    fn lima_vm_config_unparseable_memory_no_update() {
        let config =
            with_provision_sentinel("vmType: vz\ncpus: 4\nmemory: \"plenty\"\ndisk: \"30GiB\"\n");
        assert!(!lima_vm_config_needs_update_with(&config, 12, 4));
    }

    #[test]
    fn lima_vm_config_unparseable_cpus_no_update() {
        // Symmetric to the memory case: a present-but-garbage `cpus:` value is a
        // hand-mangled file, not a missing SSOT line — don't clobber it.
        let config =
            with_provision_sentinel("vmType: vz\ncpus: lots\nmemory: \"12GiB\"\ndisk: \"30GiB\"\n");
        assert!(!lima_vm_config_needs_update_with(&config, 12, 4));
    }

    #[test]
    fn lima_vm_config_adaptive_upgrade_needed() {
        // 32 GiB host → desired 16 GiB → old 12 GiB config needs upgrade
        let config = "vmType: vz\ncpus: 4\nmemory: \"12GiB\"\ndisk: \"30GiB\"\n";
        assert!(lima_vm_config_needs_update_with(config, 16, 4));
    }

    #[test]
    fn lima_vm_config_downgrade_from_12_to_8() {
        // 16 GiB host: old formula gave 12 GiB VM, new formula gives 8 GiB.
        // The migration must trigger to reclaim 4 GiB for the host.
        let config = "vmType: vz\ncpus: 4\nmemory: \"12GiB\"\ndisk: \"30GiB\"\n";
        assert!(lima_vm_config_needs_update_with(config, 8, 4));
    }

    #[test]
    fn lima_vm_config_no_op_when_current_equals_desired() {
        // Already at the desired value (mem AND cpus) — must not trigger (idempotent).
        let config =
            with_provision_sentinel("vmType: vz\ncpus: 4\nmemory: \"8GiB\"\ndisk: \"30GiB\"\n");
        assert!(!lima_vm_config_needs_update_with(&config, 8, 4));
    }

    #[test]
    fn lima_vm_config_cpus_drift_triggers_update() {
        // Memory matches but cpus drifted (bigger host → desired 8) → migrate
        // so existing users pick up the adaptive vCPU count on upgrade.
        let config =
            with_provision_sentinel("vmType: vz\ncpus: 4\nmemory: \"8GiB\"\ndisk: \"30GiB\"\n");
        assert!(lima_vm_config_needs_update_with(&config, 8, 8));
    }

    #[test]
    fn lima_vm_config_missing_cpus_triggers_update() {
        // Pre-adaptive-cpus config: no `cpus:` line at all. Absent ≠ "no drift"
        // — regenerate to write the SSOT vCPU count (matched memory must not mask it).
        let config = with_provision_sentinel("vmType: vz\nmemory: \"8GiB\"\ndisk: \"30GiB\"\n");
        assert!(lima_vm_config_needs_update_with(&config, 8, 4));
    }

    #[test]
    fn lima_vm_config_missing_memory_triggers_update() {
        // Symmetric: no `memory:` line — regenerate to write the SSOT value
        // even though cpus already matches.
        let config = with_provision_sentinel("vmType: vz\ncpus: 4\ndisk: \"30GiB\"\n");
        assert!(lima_vm_config_needs_update_with(&config, 8, 4));
    }

    /// Regression guard for the VPN routing fix — installs pre-dating the
    /// provision-script must trigger migration even if memory matches.
    #[test]
    fn lima_vm_config_without_provision_script_triggers_migration() {
        let config = "vmType: vz\ncpus: 4\nmemory: \"12GiB\"\ndisk: \"30GiB\"\n";
        assert!(
            lima_vm_config_needs_update_with(config, 12, 4),
            "configs missing the VPN-aware provision script must be migrated"
        );
    }

    #[test]
    #[cfg(target_os = "macos")]
    fn lima_config_function_has_correct_memory() {
        let config = lima_config();
        let desired = desired_lima_vm_memory();
        assert!(
            config.contains(&format!("memory: \"{}\"", desired)),
            "lima_config() must use desired_lima_vm_memory() ({desired}), \
             but the memory line doesn't match. Config:\n{config}"
        );
    }

    #[test]
    #[cfg(target_os = "macos")]
    fn lima_config_function_has_correct_cpus() {
        let config = lima_config();
        let desired = desired_lima_vm_cpus();
        assert!(
            config.contains(&format!("cpus: {desired}")),
            "lima_config() must use desired_lima_vm_cpus() ({desired}), \
             but the cpus line doesn't match. Config:\n{config}"
        );
        // Adaptive floor: never below the historical 4-vCPU baseline.
        assert!(desired >= 4, "vCPU floor regressed below 4");
    }

    // ── Windows .wslconfig VPN-compat merger tests ──────────────────────────

    /// Empty/missing .wslconfig → produces a fresh `[wsl2]` section with all
    /// three VPN-compat keys.
    #[test]
    fn merge_wslconfig_empty_input_produces_full_section() {
        let out = merge_wslconfig_vpn_keys("");
        assert!(out.contains("[wsl2]"));
        assert!(out.contains("networkingMode=mirrored"));
        assert!(out.contains("dnsTunneling=true"));
        assert!(out.contains("autoProxy=true"));
    }

    /// Existing file with unrelated `[experimental]` section — must be
    /// preserved verbatim, and `[wsl2]` appended at the end.
    #[test]
    fn merge_wslconfig_preserves_other_sections() {
        let input = "[experimental]\nfoo=bar\n";
        let out = merge_wslconfig_vpn_keys(input);
        assert!(out.contains("[experimental]"));
        assert!(out.contains("foo=bar"));
        assert!(out.contains("[wsl2]"));
        assert!(out.contains("networkingMode=mirrored"));
    }

    /// Existing `[wsl2]` with `memory=8GB` — keeps memory, inserts all three
    /// VPN keys at the end of the section before the next section starts.
    #[test]
    fn merge_wslconfig_preserves_user_keys_in_wsl2_section() {
        let input = "[wsl2]\nmemory=8GB\nprocessors=4\n\n[experimental]\nbar=baz\n";
        let out = merge_wslconfig_vpn_keys(input);
        assert!(out.contains("memory=8GB"), "user keys must be preserved");
        assert!(out.contains("processors=4"));
        assert!(out.contains("networkingMode=mirrored"));
        assert!(out.contains("[experimental]"));
        assert!(out.contains("bar=baz"));
    }

    /// `networkingMode=NAT` already present → must be **rewritten** to
    /// `mirrored`. We deliberately overwrite because a stale NAT setting
    /// re-introduces the VPN-incompatibility regression.
    #[test]
    fn merge_wslconfig_overwrites_stale_networking_mode() {
        let input = "[wsl2]\nnetworkingMode=NAT\nmemory=8GB\n";
        let out = merge_wslconfig_vpn_keys(input);
        assert!(
            out.contains("networkingMode=mirrored"),
            "stale NAT must be replaced: {out}"
        );
        assert!(
            !out.contains("networkingMode=NAT"),
            "old value must not linger: {out}"
        );
        assert!(out.contains("memory=8GB"));
    }

    /// Calling the merger twice on its own output must be a no-op (idempotent).
    #[test]
    fn merge_wslconfig_idempotent() {
        let first = merge_wslconfig_vpn_keys("[wsl2]\nmemory=8GB\n");
        let second = merge_wslconfig_vpn_keys(&first);
        assert_eq!(first, second, "merger must be idempotent");
    }

    /// Case-insensitive key match — user wrote `NetworkingMode=NAT` with
    /// different casing. The merger must still rewrite it, not duplicate.
    #[test]
    fn merge_wslconfig_case_insensitive_key_match() {
        let input = "[wsl2]\nNetworkingMode=NAT\n";
        let out = merge_wslconfig_vpn_keys(input);
        let mirrored_count = out.matches("=mirrored").count();
        assert_eq!(mirrored_count, 1, "must rewrite, not duplicate: {out}");
    }

    /// `.wslconfig` on Windows is typically CRLF — the merger must produce
    /// valid output regardless of input line endings and must NOT mix LF and
    /// CRLF in the result (cosmetic but reviewers care).
    #[test]
    fn merge_wslconfig_handles_crlf_line_endings() {
        let input = "[wsl2]\r\nmemory=8GB\r\nnetworkingMode=NAT\r\n";
        let out = merge_wslconfig_vpn_keys(input);
        assert!(out.contains("networkingMode=mirrored"));
        assert!(!out.contains("networkingMode=NAT"));
        assert!(out.contains("memory=8GB"));
        assert_eq!(out.matches("[wsl2]").count(), 1, "no duplicate sections");
        // Every newline in the output must be preceded by CR (no bare LF mixed in).
        let lone_lf = out
            .as_bytes()
            .windows(2)
            .filter(|w| w[1] == b'\n' && w[0] != b'\r')
            .count();
        let starts_with_lf = out.as_bytes().first() == Some(&b'\n');
        assert_eq!(
            lone_lf + if starts_with_lf { 1 } else { 0 },
            0,
            "CRLF input must not produce mixed line endings, got: {out:?}"
        );
    }

    /// Pure-LF input must not get CRLF injected for the new VPN keys.
    #[test]
    fn merge_wslconfig_preserves_lf_input_as_lf() {
        let out = merge_wslconfig_vpn_keys("[wsl2]\nmemory=8GB\nnetworkingMode=NAT\n");
        assert!(out.contains("networkingMode=mirrored"));
        // No CR characters anywhere.
        assert!(!out.contains('\r'), "LF input must stay LF: {out:?}");
    }

    /// Input ending without a trailing newline must still produce well-formed
    /// output (no concatenation of the appended `[wsl2]` to a preceding key).
    #[test]
    fn merge_wslconfig_handles_input_without_trailing_newline() {
        let input = "[experimental]\nfoo=bar";
        let out = merge_wslconfig_vpn_keys(input);
        assert!(out.contains("foo=bar"));
        assert!(out.contains("[wsl2]"));
        // The boundary between `foo=bar` and `[wsl2]` must be a newline.
        assert!(!out.contains("foo=bar[wsl2]"));
    }

    // ── read_existing_wslconfig: never treat a non-NotFound read error as empty ─

    /// Happy path: an existing readable file is returned verbatim.
    #[test]
    fn read_existing_wslconfig_returns_content_on_ok() {
        let path = std::path::Path::new("C:/Users/x/.wslconfig");
        let got = read_existing_wslconfig(Ok("[wsl2]\nmemory=8GB\n".to_string()), path)
            .expect("ok content must pass through");
        assert_eq!(got, "[wsl2]\nmemory=8GB\n");
    }

    /// Missing file → fresh skeleton (empty), the only error mapped to empty.
    #[test]
    fn read_existing_wslconfig_notfound_maps_to_empty() {
        let path = std::path::Path::new("C:/Users/x/.wslconfig");
        let err = std::io::Error::new(std::io::ErrorKind::NotFound, "no such file");
        let got = read_existing_wslconfig(Err(err), path).expect("NotFound must map to empty");
        assert_eq!(got, "", "missing .wslconfig must produce a fresh skeleton");
    }

    /// Invalid UTF-8 (UTF-16 .wslconfig from PowerShell `Out-File`) must BAIL —
    /// treating it as empty would overwrite the user's global [wsl2] settings.
    #[test]
    fn read_existing_wslconfig_invalid_utf8_bails() {
        let path = std::path::Path::new("C:/Users/x/.wslconfig");
        let err = std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "stream did not contain valid UTF-8",
        );
        let result = read_existing_wslconfig(Err(err), path);
        assert!(
            result.is_err(),
            "invalid UTF-8 must not be treated as empty"
        );
        let msg = format!("{:#}", result.unwrap_err());
        assert!(
            msg.contains("fix or delete .wslconfig"),
            "hint missing: {msg}"
        );
        assert!(msg.contains(".wslconfig"), "path context missing: {msg}");
    }

    /// EACCES (no permission) must BAIL, not silently overwrite.
    #[test]
    fn read_existing_wslconfig_permission_denied_bails() {
        let path = std::path::Path::new("C:/Users/x/.wslconfig");
        let err = std::io::Error::new(std::io::ErrorKind::PermissionDenied, "access denied");
        assert!(
            read_existing_wslconfig(Err(err), path).is_err(),
            "EACCES must bail, not overwrite global [wsl2]"
        );
    }

    /// EBUSY (file locked) must BAIL, not silently overwrite.
    #[test]
    fn read_existing_wslconfig_busy_bails() {
        let path = std::path::Path::new("C:/Users/x/.wslconfig");
        let err = std::io::Error::new(std::io::ErrorKind::ResourceBusy, "resource busy");
        assert!(
            read_existing_wslconfig(Err(err), path).is_err(),
            "EBUSY must bail, not overwrite global [wsl2]"
        );
    }

    // ── wsl_conf_or_warn: degrade to empty on spawn failure, but warn ──────────

    /// Ok read passes through unchanged.
    #[test]
    fn wsl_conf_or_warn_passes_ok_through() {
        let got = wsl_conf_or_warn(
            Ok("[automount]\nenabled=true\n".to_string()),
            "Speedwave",
            "initial read",
        );
        assert_eq!(got, "[automount]\nenabled=true\n");
    }

    /// Err (spawn/IO failure) degrades to empty so the post-write uid re-read
    /// still guards correctness — but the caller logs a warning (not silent).
    #[test]
    fn wsl_conf_or_warn_err_degrades_to_empty() {
        let err = anyhow::anyhow!("wsl.exe not found");
        let got = wsl_conf_or_warn(Err(err), "Speedwave", "post-write verify");
        assert_eq!(got, "", "spawn failure must degrade to empty");
    }

    // ── TerminateOnChange policy + probe interpretation ─────────────────────

    // Guards the "cannot exec in a stopped state" regression: Yes vs IfIdle stay distinct.
    #[test]
    fn terminate_variants_are_distinct() {
        assert_ne!(TerminateOnChange::IfIdle, TerminateOnChange::Yes);
        assert_eq!(TerminateOnChange::IfIdle, TerminateOnChange::IfIdle);
    }

    #[test]
    fn terminate_is_copy_and_debug() {
        let y = TerminateOnChange::Yes;
        let copied = y; // Copy: original still usable below
        assert_eq!(y, copied);
        assert_eq!(format!("{:?}", TerminateOnChange::Yes), "Yes");
        assert_eq!(format!("{:?}", TerminateOnChange::IfIdle), "IfIdle");
    }

    // Yes always terminates; IfIdle only when no container runs.
    #[test]
    fn yes_always_terminates() {
        assert!(terminate_decision(TerminateOnChange::Yes, false));
        assert!(terminate_decision(TerminateOnChange::Yes, true));
    }

    #[test]
    fn ifidle_terminates_only_when_no_containers_run() {
        assert!(
            terminate_decision(TerminateOnChange::IfIdle, false),
            "idle distro must terminate so metadata applies before first start"
        );
        assert!(
            !terminate_decision(TerminateOnChange::IfIdle, true),
            "must NOT terminate while containers run (would kill them)"
        );
    }

    #[test]
    fn probe_empty_stdout_means_no_containers() {
        assert!(!running_containers_from_probe(true, "", ""));
        assert!(!running_containers_from_probe(true, "   \n  ", ""));
    }

    #[test]
    fn probe_nonempty_stdout_means_running() {
        assert!(running_containers_from_probe(true, "abc123\n", ""));
    }

    // containerd down (cold start) ⇒ idle, so IfIdle can terminate and apply.
    #[test]
    fn probe_daemon_down_means_idle() {
        assert!(!running_containers_from_probe(
            false,
            "",
            "failed to connect to containerd: connection refused"
        ));
        assert!(!running_containers_from_probe(
            false,
            "",
            "cannot connect to containerd.sock: No such file or directory"
        ));
    }

    // A non-daemon-down failure stays fail-safe to busy (never terminate on doubt).
    #[test]
    fn probe_other_failure_assumes_busy() {
        assert!(running_containers_from_probe(
            false,
            "",
            "some unexpected error"
        ));
    }

    // ── wsl.conf automount mergers (pure transforms) ────────────────────────

    const OPTS: &str = "metadata,uid=1000,gid=1000,umask=022";

    #[test]
    fn merge_adds_section_when_absent() {
        let out = merge_wsl_conf_automount("[boot]\nsystemd=true\n", OPTS);
        assert!(out.contains("[automount]"));
        assert!(out.contains(&format!("options = \"{OPTS}\"")));
        assert!(wsl_conf_automount_has_uid(&out, 1000));
    }

    #[test]
    fn merge_on_empty_input() {
        let out = merge_wsl_conf_automount("", OPTS);
        assert_eq!(out, format!("[automount]\noptions = \"{OPTS}\"\n"));
        assert!(wsl_conf_automount_has_uid(&out, 1000));
    }

    // [automount] present but with NO options line → insert it, keeping other keys.
    #[test]
    fn merge_inserts_options_and_keeps_other_keys() {
        let out = merge_wsl_conf_automount("[automount]\nenabled = false\nroot = /m/\n", OPTS);
        assert_eq!(automount_options_line(&out), Some(OPTS));
        assert!(
            out.contains("enabled = false"),
            "other [automount] keys preserved"
        );
        assert!(
            out.contains("root = /m/"),
            "other [automount] keys preserved"
        );
    }

    // Existing wrong options line is replaced, not duplicated.
    #[test]
    fn merge_replaces_existing_options() {
        let out = merge_wsl_conf_automount("[automount]\noptions = \"metadata,uid=0\"\n", OPTS);
        assert_eq!(out.matches("options =").count(), 1);
        assert!(wsl_conf_automount_has_uid(&out, 1000));
    }

    // Interleaved duplicate [automount]: collapse to one, and a key from the
    // dropped duplicate must NOT be misplaced under the intervening section.
    #[test]
    fn merge_dedups_duplicate_sections() {
        let input = "[automount]\nenabled=true\n[network]\nx=1\n[automount]\nroot=/m/\n";
        let out = merge_wsl_conf_automount(input, OPTS);
        assert_eq!(out.matches("[automount]").count(), 1);
        assert_eq!(out.matches("options =").count(), 1);
        assert!(out.contains("[network]"), "other sections preserved");
        // The duplicate's `root=/m/` must not leak under [network].
        let net = out.find("[network]").unwrap();
        assert!(
            !out[net..].contains("root=/m/"),
            "duplicate-section body must not be reattributed to [network]: {out:?}"
        );
    }

    #[test]
    fn merge_is_idempotent() {
        let once = merge_wsl_conf_automount("[boot]\nsystemd=true\n", OPTS);
        let twice = merge_wsl_conf_automount(&once, OPTS);
        assert_eq!(once, twice);
    }

    #[test]
    fn merge_preserves_crlf() {
        let out = merge_wsl_conf_automount("[boot]\r\nsystemd=true\r\n", OPTS);
        assert!(out.contains("\r\n"));
        assert!(!out.contains("\n\n") || out.contains("\r\n"));
        assert!(wsl_conf_automount_has_uid(&out, 1000));
    }

    // Anchored verification: uid=1000 must NOT match uid=10000 or a comment.
    #[test]
    fn uid_check_is_anchored_not_substring() {
        assert!(options_has_uid("metadata,uid=1000,gid=1000", 1000));
        assert!(!options_has_uid("metadata,uid=10000,gid=1000", 1000));
        assert!(!options_has_uid("metadata,uid=100000", 1000));
    }

    #[test]
    fn verify_ignores_commented_uid_and_other_sections() {
        // uid=1000 only in a comment / a different section → not satisfied.
        assert!(!wsl_conf_automount_has_uid(
            "# uid=1000\n[automount]\nx=1\n",
            1000
        ));
        assert!(!wsl_conf_automount_has_uid(
            "[other]\noptions=\"uid=1000\"\n[automount]\nx=1\n",
            1000
        ));
    }

    #[test]
    fn options_line_lookup_skips_comments() {
        assert_eq!(
            automount_options_line("[automount]\n# options = \"x\"\noptions = \"real\"\n"),
            Some("real")
        );
        assert_eq!(automount_options_line("[boot]\noptions = \"x\"\n"), None);
    }

    // ── verify_wsl_distro_origin (data-dir-explicit, tempdir-isolated) ──────

    #[test]
    fn verify_wsl_distro_origin_passes_when_vhdx_exists() {
        let data_dir = tempfile::tempdir().expect("tempdir");
        let vhdx_dir = data_dir.path().join("wsl").join(consts::wsl_distro_name());
        std::fs::create_dir_all(&vhdx_dir).expect("create dirs");
        std::fs::write(vhdx_dir.join("ext4.vhdx"), b"fake vhdx").expect("write marker");

        let result = verify_wsl_distro_origin_in(data_dir.path());

        assert!(
            result.is_ok(),
            "expected Ok when ext4.vhdx exists, got: {result:?}"
        );
    }

    #[test]
    fn verify_wsl_distro_origin_fails_when_vhdx_missing() {
        // Empty tempdir — the vhdx file does not exist.
        let data_dir = tempfile::tempdir().expect("tempdir");
        let result = verify_wsl_distro_origin_in(data_dir.path());
        let err_msg = result
            .expect_err("expected Err when vhdx missing")
            .to_string();
        assert!(
            err_msg.contains("Security error"),
            "error should mention 'Security error', got: {err_msg}"
        );
    }

    #[test]
    fn verify_wsl_distro_origin_rejects_empty_directory() {
        // Create the wsl distro directory without the ext4.vhdx file.
        let data_dir = tempfile::tempdir().expect("tempdir");
        let vhdx_dir = data_dir.path().join("wsl").join(consts::wsl_distro_name());
        std::fs::create_dir_all(&vhdx_dir).expect("create dirs");

        let result = verify_wsl_distro_origin_in(data_dir.path());

        let err_msg = result
            .expect_err("expected Err when vhdx missing in empty dir")
            .to_string();
        assert!(
            err_msg.contains("Security error"),
            "error should mention 'Security error', got: {err_msg}"
        );
    }

    #[test]
    fn expected_wsl_vhdx_path_structure() {
        let data_dir = tempfile::tempdir().expect("tempdir");
        let path = expected_wsl_vhdx_path_in(data_dir.path());
        let path_str = path.to_string_lossy();
        let data_dir_str = data_dir.path().to_string_lossy().to_string();
        assert!(
            path_str.contains(&data_dir_str),
            "path should contain data dir ({data_dir_str}): {path_str}"
        );
        assert!(
            path_str.contains("wsl"),
            "path should contain 'wsl': {path_str}"
        );
        assert!(
            path_str.contains(consts::wsl_distro_name()),
            "path should contain distro name: {path_str}"
        );
        assert!(
            path_str.ends_with("ext4.vhdx"),
            "path should end with ext4.vhdx: {path_str}"
        );
    }

    // ── wsl_rootfs_for_arch ─────────────────────────────────────────────────

    #[cfg(target_os = "windows")]
    #[test]
    fn wsl_rootfs_for_arch_returns_ok_for_current_arch() {
        // On Windows CI this will be x86_64 or aarch64 — both are valid
        let result = wsl_rootfs_for_arch();
        assert!(result.is_ok(), "should succeed on supported arch");
        let (url, sha) = result.unwrap();
        assert!(url.starts_with("https://"));
        assert_eq!(sha.len(), 64, "SHA256 hash must be 64 hex chars");
    }

    // ── ps_escape (Windows PowerShell path escaping) ────────────────────────

    #[cfg(target_os = "windows")]
    mod ps_escape_tests {
        use super::super::ps_escape;
        use std::path::Path;

        #[test]
        fn plain_path_unchanged() {
            let p = Path::new(r"C:\Users\dev\speedwave");
            assert_eq!(ps_escape(p), r"C:\Users\dev\speedwave");
        }

        #[test]
        fn single_quote_doubled() {
            let p = Path::new(r"C:\Users\it's a path\file");
            assert_eq!(ps_escape(p), r"C:\Users\it''s a path\file");
        }

        #[test]
        fn multiple_single_quotes_all_doubled() {
            let p = Path::new(r"C:\a'b'c'd");
            assert_eq!(ps_escape(p), r"C:\a''b''c''d");
        }

        #[test]
        fn path_with_spaces_preserved() {
            let p = Path::new(r"C:\Program Files\Speedwave 2");
            assert_eq!(ps_escape(p), r"C:\Program Files\Speedwave 2");
        }

        #[test]
        fn empty_path_returns_empty() {
            let p = Path::new("");
            assert_eq!(ps_escape(p), "");
        }
    }
}
