# setup-dev-windows.ps1 -- installs the Windows dev toolchain via Chocolatey (admin;
# self-elevates) and writes the MSVC/Git Bash config `make dev` needs. Idempotent.
# See docs/contributing/development-setup.md "Windows dev setup".

$ErrorActionPreference = 'Stop'

# --- Self-elevate: Chocolatey + VS Build Tools install machine-wide (admin). ----
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)) {
    Write-Host "Elevating (Chocolatey + VS Build Tools require admin)..."
    Start-Process -FilePath 'powershell' -Verb RunAs -Wait -ArgumentList @(
        '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', "`"$PSCommandPath`""
    )
    exit 0
}

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
Write-Host "Speedwave Windows dev setup (repo: $repoRoot)"

# --- Chocolatey ----------------------------------------------------------------
if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
    Write-Host "== Installing Chocolatey =="
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = 3072
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    $env:Path = [Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
                [Environment]::GetEnvironmentVariable('Path', 'User')
}

# Non-obvious picks: `make` must be GNU Make 4.4 (GnuWin32 3.81 breaks $(VAR)); cmake
# + llvm build whisper.cpp/bindgen (audio-transcription). Rationale: development-setup.md.
Write-Host "== choco install toolchain (this is large: VS Build Tools) =="
choco install -y git make rustup.install nodejs-lts cmake llvm `
    visualstudio2022buildtools visualstudio2022-workload-vctools bats-core

$env:Path = [Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
            [Environment]::GetEnvironmentVariable('Path', 'User')

# --- Rust toolchain (from rust-toolchain.toml) + cargo-tauri -------------------
$cargoBin = Join-Path $env:USERPROFILE '.cargo\bin'
$rustup = Join-Path $cargoBin 'rustup.exe'
$cargo = Join-Path $cargoBin 'cargo.exe'
if (Test-Path $rustup) {
    Write-Host "== Materializing pinned Rust toolchain =="
    Push-Location $repoRoot
    & $rustup show | Out-Null
    Pop-Location
    if ((Test-Path $cargo) -and -not (Test-Path (Join-Path $cargoBin 'cargo-tauri.exe'))) {
        Write-Host "== cargo install tauri-cli =="
        & $cargo install tauri-cli --locked
    }
}

# --- Locate MSVC + Windows SDK -------------------------------------------------
$vsBase = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools"
$msvcRoot = Join-Path $vsBase 'VC\Tools\MSVC'
$msvcVer = if (Test-Path $msvcRoot) {
    (Get-ChildItem $msvcRoot -Directory | Sort-Object Name -Descending | Select-Object -First 1).Name
}
$sdkBinRoot = "${env:ProgramFiles(x86)}\Windows Kits\10\bin"
$sdkVer = if (Test-Path $sdkBinRoot) {
    (Get-ChildItem $sdkBinRoot -Directory -Filter '10.*' | Sort-Object Name -Descending | Select-Object -First 1).Name
}

function ConvertTo-BashPath([string]$p) {
    if ($p -match '^([A-Za-z]):\\(.*)$') { return '/' + $Matches[1].ToLower() + '/' + ($Matches[2] -replace '\\', '/') }
    return $p
}

# --- .cargo/config.toml: pin the MSVC linker (gitignored, per-machine) ---------
# Without it, cargo on Git Bash resolves cygwin's /usr/bin/link before MSVC
# link.exe -> LNK1146/LNK1170/LNK1206-class failures.
if ($msvcVer) {
    $linker = "$msvcRoot\$msvcVer\bin\HostX64\x64\link.exe"
    $cargoDir = Join-Path $repoRoot '.cargo'
    New-Item -ItemType Directory -Force $cargoDir | Out-Null
    $linkerToml = $linker -replace '\\', '\\'
    $toml = "# Generated by scripts/setup-dev-windows.ps1 -- per-machine, gitignored.`n" +
            "[target.x86_64-pc-windows-msvc]`n" +
            "linker = `"$linkerToml`"`n"
    Set-Content -Path (Join-Path $cargoDir 'config.toml') -Value $toml -Encoding ascii -NoNewline
    Write-Host "Wrote .cargo/config.toml (MSVC $msvcVer linker)"
}

# --- ~/msvc-env.sh sourced from ~/.bashrc: INCLUDE/LIB + cl.exe/link.exe on PATH -
# cargo build scripts (cc: whisper-rs-sys, ring) need cl.exe + the MSVC/SDK
# INCLUDE/LIB; bindgen needs libclang (LIBCLANG_PATH).
$vcvars = Join-Path $vsBase 'VC\Auxiliary\Build\vcvars64.bat'
if ((Test-Path $vcvars) -and $msvcVer) {
    Write-Host "== Generating ~/msvc-env.sh for Git Bash =="
    $envLines = cmd /c "`"$vcvars`" >nul 2>&1 && set"
    $get = { param($k) ($envLines | Where-Object { $_ -like "$k=*" } | Select-Object -First 1) -replace "^$k=", '' }
    $include = & $get 'INCLUDE'
    $lib = & $get 'LIB'
    $libpath = & $get 'LIBPATH'

    $pathAdds = @("$msvcRoot\$msvcVer\bin\HostX64\x64")
    if ($sdkVer) { $pathAdds += "$sdkBinRoot\$sdkVer\x64" }
    $llvmBin = "$env:ProgramFiles\LLVM\bin"
    if (Test-Path $llvmBin) { $pathAdds += $llvmBin }
    $bashPath = ($pathAdds | ForEach-Object { ConvertTo-BashPath $_ }) -join ':'

    $sh = @()
    $sh += "# Generated by scripts/setup-dev-windows.ps1 -- MSVC env for cargo/cc + bindgen."
    $sh += "export INCLUDE='$include'"
    $sh += "export LIB='$lib'"
    $sh += "export LIBPATH='$libpath'"
    if (Test-Path $llvmBin) { $sh += "export LIBCLANG_PATH='$llvmBin'" }
    $sh += "export PATH=`"$bashPath`:`$PATH`""
    $home_ = $env:USERPROFILE
    $envShWin = Join-Path $home_ 'msvc-env.sh'
    Set-Content -Path $envShWin -Value ($sh -join "`n") -Encoding ascii
    Write-Host "Wrote $envShWin"

    # Ensure ~/.bashrc sources it (idempotent).
    $bashrc = Join-Path $home_ '.bashrc'
    $sourceLine = '[ -f ~/msvc-env.sh ] && . ~/msvc-env.sh'
    $existing = if (Test-Path $bashrc) { Get-Content $bashrc -Raw } else { '' }
    if ($existing -notmatch 'msvc-env\.sh') {
        Add-Content -Path $bashrc -Value "`n$sourceLine`n" -Encoding ascii
        Write-Host "Appended msvc-env.sh source to ~/.bashrc"
    }
}

Write-Host ""
Write-Host "== Done. Next steps =="
Write-Host "  1. Open a NEW Git Bash window (to pick up PATH + ~/.bashrc)."
Write-Host "  2. cd into the repo and run:  make setup-dev   (install project deps)"
Write-Host "  3. then:  make dev"
Write-Host "  (First whisper.cpp build is slow; subsequent builds are incremental.)"
